/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as shared from "../shared";
import * as z from "zod";

export type C1ApiAppV1AppResourceTypeServiceListRequest = {
    appId: string;
    pageSize?: number | undefined;
    pageToken?: string | undefined;
};

export type C1ApiAppV1AppResourceTypeServiceListResponse = {
    /**
     * The AppResourceTypeServiceListResponse message contains a list of results and a nextPageToken if applicable.
     */
    appResourceTypeServiceListResponse?: shared.AppResourceTypeServiceListResponse | undefined;
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
};

/** @internal */
export namespace C1ApiAppV1AppResourceTypeServiceListRequest$ {
    export type Inbound = {
        app_id: string;
        page_size?: number | undefined;
        page_token?: string | undefined;
    };

    export const inboundSchema: z.ZodType<
        C1ApiAppV1AppResourceTypeServiceListRequest,
        z.ZodTypeDef,
        Inbound
    > = z
        .object({
            app_id: z.string(),
            page_size: z.number().int().optional(),
            page_token: z.string().optional(),
        })
        .transform((v) => {
            return {
                appId: v.app_id,
                ...(v.page_size === undefined ? null : { pageSize: v.page_size }),
                ...(v.page_token === undefined ? null : { pageToken: v.page_token }),
            };
        });

    export type Outbound = {
        app_id: string;
        page_size?: number | undefined;
        page_token?: string | undefined;
    };

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        C1ApiAppV1AppResourceTypeServiceListRequest
    > = z
        .object({
            appId: z.string(),
            pageSize: z.number().int().optional(),
            pageToken: z.string().optional(),
        })
        .transform((v) => {
            return {
                app_id: v.appId,
                ...(v.pageSize === undefined ? null : { page_size: v.pageSize }),
                ...(v.pageToken === undefined ? null : { page_token: v.pageToken }),
            };
        });
}

/** @internal */
export namespace C1ApiAppV1AppResourceTypeServiceListResponse$ {
    export type Inbound = {
        AppResourceTypeServiceListResponse?:
            | shared.AppResourceTypeServiceListResponse$.Inbound
            | undefined;
        ContentType: string;
        StatusCode: number;
        RawResponse: Response;
    };

    export const inboundSchema: z.ZodType<
        C1ApiAppV1AppResourceTypeServiceListResponse,
        z.ZodTypeDef,
        Inbound
    > = z
        .object({
            AppResourceTypeServiceListResponse:
                shared.AppResourceTypeServiceListResponse$.inboundSchema.optional(),
            ContentType: z.string(),
            StatusCode: z.number().int(),
            RawResponse: z.instanceof(Response),
        })
        .transform((v) => {
            return {
                ...(v.AppResourceTypeServiceListResponse === undefined
                    ? null
                    : { appResourceTypeServiceListResponse: v.AppResourceTypeServiceListResponse }),
                contentType: v.ContentType,
                statusCode: v.StatusCode,
                rawResponse: v.RawResponse,
            };
        });

    export type Outbound = {
        AppResourceTypeServiceListResponse?:
            | shared.AppResourceTypeServiceListResponse$.Outbound
            | undefined;
        ContentType: string;
        StatusCode: number;
        RawResponse: never;
    };

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        C1ApiAppV1AppResourceTypeServiceListResponse
    > = z
        .object({
            appResourceTypeServiceListResponse:
                shared.AppResourceTypeServiceListResponse$.outboundSchema.optional(),
            contentType: z.string(),
            statusCode: z.number().int(),
            rawResponse: z.instanceof(Response).transform(() => {
                throw new Error("Response cannot be serialized");
            }),
        })
        .transform((v) => {
            return {
                ...(v.appResourceTypeServiceListResponse === undefined
                    ? null
                    : { AppResourceTypeServiceListResponse: v.appResourceTypeServiceListResponse }),
                ContentType: v.contentType,
                StatusCode: v.statusCode,
                RawResponse: v.rawResponse,
            };
        });
}
