/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as shared from "../shared";
import * as z from "zod";

export type C1ApiDirectoryV1DirectoryServiceGetRequest = {
    appId: string;
};

export type C1ApiDirectoryV1DirectoryServiceGetResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * The Directory Service Get Response returns a directory view with a directory and JSONPATHs indicating the
     *
     * @remarks
     *  location in the expanded array that items are expanded as indicated by the expand mask in the request.
     */
    directoryServiceGetResponse?: shared.DirectoryServiceGetResponse | undefined;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
};

/** @internal */
export namespace C1ApiDirectoryV1DirectoryServiceGetRequest$ {
    export type Inbound = {
        app_id: string;
    };

    export const inboundSchema: z.ZodType<
        C1ApiDirectoryV1DirectoryServiceGetRequest,
        z.ZodTypeDef,
        Inbound
    > = z
        .object({
            app_id: z.string(),
        })
        .transform((v) => {
            return {
                appId: v.app_id,
            };
        });

    export type Outbound = {
        app_id: string;
    };

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        C1ApiDirectoryV1DirectoryServiceGetRequest
    > = z
        .object({
            appId: z.string(),
        })
        .transform((v) => {
            return {
                app_id: v.appId,
            };
        });
}

/** @internal */
export namespace C1ApiDirectoryV1DirectoryServiceGetResponse$ {
    export type Inbound = {
        ContentType: string;
        DirectoryServiceGetResponse?: shared.DirectoryServiceGetResponse$.Inbound | undefined;
        StatusCode: number;
        RawResponse: Response;
    };

    export const inboundSchema: z.ZodType<
        C1ApiDirectoryV1DirectoryServiceGetResponse,
        z.ZodTypeDef,
        Inbound
    > = z
        .object({
            ContentType: z.string(),
            DirectoryServiceGetResponse:
                shared.DirectoryServiceGetResponse$.inboundSchema.optional(),
            StatusCode: z.number().int(),
            RawResponse: z.instanceof(Response),
        })
        .transform((v) => {
            return {
                contentType: v.ContentType,
                ...(v.DirectoryServiceGetResponse === undefined
                    ? null
                    : { directoryServiceGetResponse: v.DirectoryServiceGetResponse }),
                statusCode: v.StatusCode,
                rawResponse: v.RawResponse,
            };
        });

    export type Outbound = {
        ContentType: string;
        DirectoryServiceGetResponse?: shared.DirectoryServiceGetResponse$.Outbound | undefined;
        StatusCode: number;
        RawResponse: never;
    };

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        C1ApiDirectoryV1DirectoryServiceGetResponse
    > = z
        .object({
            contentType: z.string(),
            directoryServiceGetResponse:
                shared.DirectoryServiceGetResponse$.outboundSchema.optional(),
            statusCode: z.number().int(),
            rawResponse: z.instanceof(Response).transform(() => {
                throw new Error("Response cannot be serialized");
            }),
        })
        .transform((v) => {
            return {
                ContentType: v.contentType,
                ...(v.directoryServiceGetResponse === undefined
                    ? null
                    : { DirectoryServiceGetResponse: v.directoryServiceGetResponse }),
                StatusCode: v.statusCode,
                RawResponse: v.rawResponse,
            };
        });
}
