/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import {
  collectExtraKeys as collectExtraKeys$,
  safeParse,
} from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  AccessReviewView,
  AccessReviewView$inboundSchema,
  AccessReviewView$Outbound,
  AccessReviewView$outboundSchema,
} from "./accessreviewview.js";

/**
 * Contains an arbitrary serialized message along with a @type that describes the type of the serialized message.
 */
export type AccessReviewServiceListResponseExpanded = {
  /**
   * The type of the serialized message.
   */
  atType?: string | undefined;
  additionalProperties?: { [k: string]: any } | undefined;
};

/**
 * The AccessReviewServiceListResponse message.
 */
export type AccessReviewServiceListResponse = {
  /**
   * The expanded field.
   */
  expanded?: Array<AccessReviewServiceListResponseExpanded> | null | undefined;
  /**
   * The list field.
   */
  list?: Array<AccessReviewView> | null | undefined;
  /**
   * The nextPageToken field.
   */
  nextPageToken?: string | undefined;
};

/** @internal */
export const AccessReviewServiceListResponseExpanded$inboundSchema: z.ZodType<
  AccessReviewServiceListResponseExpanded,
  z.ZodTypeDef,
  unknown
> = collectExtraKeys$(
  z.object({
    "@type": z.string().optional(),
  }).catchall(z.any()),
  "additionalProperties",
  true,
).transform((v) => {
  return remap$(v, {
    "@type": "atType",
  });
});

/** @internal */
export type AccessReviewServiceListResponseExpanded$Outbound = {
  "@type"?: string | undefined;
  [additionalProperties: string]: unknown;
};

/** @internal */
export const AccessReviewServiceListResponseExpanded$outboundSchema: z.ZodType<
  AccessReviewServiceListResponseExpanded$Outbound,
  z.ZodTypeDef,
  AccessReviewServiceListResponseExpanded
> = z.object({
  atType: z.string().optional(),
  additionalProperties: z.record(z.any()).optional(),
}).transform((v) => {
  return {
    ...v.additionalProperties,
    ...remap$(v, {
      atType: "@type",
      additionalProperties: null,
    }),
  };
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AccessReviewServiceListResponseExpanded$ {
  /** @deprecated use `AccessReviewServiceListResponseExpanded$inboundSchema` instead. */
  export const inboundSchema =
    AccessReviewServiceListResponseExpanded$inboundSchema;
  /** @deprecated use `AccessReviewServiceListResponseExpanded$outboundSchema` instead. */
  export const outboundSchema =
    AccessReviewServiceListResponseExpanded$outboundSchema;
  /** @deprecated use `AccessReviewServiceListResponseExpanded$Outbound` instead. */
  export type Outbound = AccessReviewServiceListResponseExpanded$Outbound;
}

export function accessReviewServiceListResponseExpandedToJSON(
  accessReviewServiceListResponseExpanded:
    AccessReviewServiceListResponseExpanded,
): string {
  return JSON.stringify(
    AccessReviewServiceListResponseExpanded$outboundSchema.parse(
      accessReviewServiceListResponseExpanded,
    ),
  );
}

export function accessReviewServiceListResponseExpandedFromJSON(
  jsonString: string,
): SafeParseResult<
  AccessReviewServiceListResponseExpanded,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      AccessReviewServiceListResponseExpanded$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'AccessReviewServiceListResponseExpanded' from JSON`,
  );
}

/** @internal */
export const AccessReviewServiceListResponse$inboundSchema: z.ZodType<
  AccessReviewServiceListResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  expanded: z.nullable(
    z.array(
      z.lazy(() => AccessReviewServiceListResponseExpanded$inboundSchema),
    ),
  ).optional(),
  list: z.nullable(z.array(AccessReviewView$inboundSchema)).optional(),
  nextPageToken: z.string().optional(),
});

/** @internal */
export type AccessReviewServiceListResponse$Outbound = {
  expanded?:
    | Array<AccessReviewServiceListResponseExpanded$Outbound>
    | null
    | undefined;
  list?: Array<AccessReviewView$Outbound> | null | undefined;
  nextPageToken?: string | undefined;
};

/** @internal */
export const AccessReviewServiceListResponse$outboundSchema: z.ZodType<
  AccessReviewServiceListResponse$Outbound,
  z.ZodTypeDef,
  AccessReviewServiceListResponse
> = z.object({
  expanded: z.nullable(
    z.array(
      z.lazy(() => AccessReviewServiceListResponseExpanded$outboundSchema),
    ),
  ).optional(),
  list: z.nullable(z.array(AccessReviewView$outboundSchema)).optional(),
  nextPageToken: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AccessReviewServiceListResponse$ {
  /** @deprecated use `AccessReviewServiceListResponse$inboundSchema` instead. */
  export const inboundSchema = AccessReviewServiceListResponse$inboundSchema;
  /** @deprecated use `AccessReviewServiceListResponse$outboundSchema` instead. */
  export const outboundSchema = AccessReviewServiceListResponse$outboundSchema;
  /** @deprecated use `AccessReviewServiceListResponse$Outbound` instead. */
  export type Outbound = AccessReviewServiceListResponse$Outbound;
}

export function accessReviewServiceListResponseToJSON(
  accessReviewServiceListResponse: AccessReviewServiceListResponse,
): string {
  return JSON.stringify(
    AccessReviewServiceListResponse$outboundSchema.parse(
      accessReviewServiceListResponse,
    ),
  );
}

export function accessReviewServiceListResponseFromJSON(
  jsonString: string,
): SafeParseResult<AccessReviewServiceListResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AccessReviewServiceListResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AccessReviewServiceListResponse' from JSON`,
  );
}
