/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  ActionTargetAutomation,
  ActionTargetAutomation$inboundSchema,
  ActionTargetAutomation$Outbound,
  ActionTargetAutomation$outboundSchema,
} from "./actiontargetautomation.js";

/**
 * The Action message.
 *
 * @remarks
 *
 * This message contains a oneof named target. Only a single field of the following list may be set at a time:
 *   - automation
 */
export type Action = {
  /**
   * The ActionTargetAutomation message.
   */
  actionTargetAutomation?: ActionTargetAutomation | null | undefined;
};

/** @internal */
export const Action$inboundSchema: z.ZodType<Action, z.ZodTypeDef, unknown> = z
  .object({
    automation: z.nullable(ActionTargetAutomation$inboundSchema).optional(),
  }).transform((v) => {
    return remap$(v, {
      "automation": "actionTargetAutomation",
    });
  });
/** @internal */
export type Action$Outbound = {
  automation?: ActionTargetAutomation$Outbound | null | undefined;
};

/** @internal */
export const Action$outboundSchema: z.ZodType<
  Action$Outbound,
  z.ZodTypeDef,
  Action
> = z.object({
  actionTargetAutomation: z.nullable(ActionTargetAutomation$outboundSchema)
    .optional(),
}).transform((v) => {
  return remap$(v, {
    actionTargetAutomation: "automation",
  });
});

export function actionToJSON(action: Action): string {
  return JSON.stringify(Action$outboundSchema.parse(action));
}
export function actionFromJSON(
  jsonString: string,
): SafeParseResult<Action, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Action$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Action' from JSON`,
  );
}
