/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

/**
 * Empty request body. Just placeholder for the generate app report request which uses URL values for input.
 */
export type AppActionsServiceGenerateReportRequest = {};

/** @internal */
export type AppActionsServiceGenerateReportRequest$Outbound = {};

/** @internal */
export const AppActionsServiceGenerateReportRequest$outboundSchema: z.ZodType<
  AppActionsServiceGenerateReportRequest$Outbound,
  z.ZodTypeDef,
  AppActionsServiceGenerateReportRequest
> = z.object({});

export function appActionsServiceGenerateReportRequestToJSON(
  appActionsServiceGenerateReportRequest:
    AppActionsServiceGenerateReportRequest,
): string {
  return JSON.stringify(
    AppActionsServiceGenerateReportRequest$outboundSchema.parse(
      appActionsServiceGenerateReportRequest,
    ),
  );
}
