/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Which side of the conflict monitor (A or B) this entitlement is assigned to.
 */
export const AppEntitlementMonitorBindingEntitlementGroup = {
  EntitlementGroupUnspecified: "ENTITLEMENT_GROUP_UNSPECIFIED",
  EntitlementGroupA: "ENTITLEMENT_GROUP_A",
  EntitlementGroupB: "ENTITLEMENT_GROUP_B",
} as const;
/**
 * Which side of the conflict monitor (A or B) this entitlement is assigned to.
 */
export type AppEntitlementMonitorBindingEntitlementGroup = OpenEnum<
  typeof AppEntitlementMonitorBindingEntitlementGroup
>;

/**
 * Represents the association of an app entitlement with one side (A or B) of a conflict monitor.
 */
export type AppEntitlementMonitorBinding = {
  /**
   * The unique identifier of the bound app entitlement.
   */
  appEntitlementId?: string | null | undefined;
  /**
   * The unique identifier of the application containing the entitlement.
   */
  appId?: string | null | undefined;
  createdAt?: Date | null | undefined;
  deletedAt?: Date | null | undefined;
  /**
   * Which side of the conflict monitor (A or B) this entitlement is assigned to.
   */
  entitlementGroup?:
    | AppEntitlementMonitorBindingEntitlementGroup
    | null
    | undefined;
  /**
   * The unique identifier of the conflict monitor this binding belongs to.
   */
  monitorId?: string | null | undefined;
  updatedAt?: Date | null | undefined;
};

/** @internal */
export const AppEntitlementMonitorBindingEntitlementGroup$inboundSchema:
  z.ZodType<
    AppEntitlementMonitorBindingEntitlementGroup,
    z.ZodTypeDef,
    unknown
  > = openEnums.inboundSchema(AppEntitlementMonitorBindingEntitlementGroup);

/** @internal */
export const AppEntitlementMonitorBinding$inboundSchema: z.ZodType<
  AppEntitlementMonitorBinding,
  z.ZodTypeDef,
  unknown
> = z.object({
  appEntitlementId: z.nullable(z.string()).optional(),
  appId: z.nullable(z.string()).optional(),
  createdAt: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
  deletedAt: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
  entitlementGroup: z.nullable(
    AppEntitlementMonitorBindingEntitlementGroup$inboundSchema,
  ).optional(),
  monitorId: z.nullable(z.string()).optional(),
  updatedAt: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
});

export function appEntitlementMonitorBindingFromJSON(
  jsonString: string,
): SafeParseResult<AppEntitlementMonitorBinding, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AppEntitlementMonitorBinding$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AppEntitlementMonitorBinding' from JSON`,
  );
}
