/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  AppEntitlementAutomationLastRunStatus,
  AppEntitlementAutomationLastRunStatus$inboundSchema,
} from "./appentitlementautomationlastrunstatus.js";
import {
  AppEntitlementAutomationRuleBasic,
  AppEntitlementAutomationRuleBasic$inboundSchema,
} from "./appentitlementautomationrulebasic.js";
import {
  AppEntitlementAutomationRuleCEL,
  AppEntitlementAutomationRuleCEL$inboundSchema,
} from "./appentitlementautomationrulecel.js";
import {
  AppEntitlementAutomationRuleEntitlement,
  AppEntitlementAutomationRuleEntitlement$inboundSchema,
} from "./appentitlementautomationruleentitlement.js";
import {
  AppEntitlementAutomationRuleNone,
  AppEntitlementAutomationRuleNone$inboundSchema,
} from "./appentitlementautomationrulenone.js";

/**
 * The AppEntitlementAutomation message.
 *
 * @remarks
 *
 * This message contains a oneof named conditions. Only a single field of the following list may be set at a time:
 *   - none
 *   - entitlements
 *   - cel
 *   - basic
 */
export type AppEntitlementAutomation = {
  /**
   * The unique ID for the App Entitlement.
   */
  appEntitlementId?: string | null | undefined;
  /**
   * The ID of the app that is associated with the app entitlement.
   */
  appId?: string | null | undefined;
  basic?: AppEntitlementAutomationRuleBasic | null | undefined;
  cel?: AppEntitlementAutomationRuleCEL | null | undefined;
  createdAt?: Date | null | undefined;
  deletedAt?: Date | null | undefined;
  /**
   * The description of the app entitlement.
   */
  description?: string | null | undefined;
  /**
   * The display name of the app entitlement.
   */
  displayName?: string | null | undefined;
  entitlements?: AppEntitlementAutomationRuleEntitlement | null | undefined;
  lastRunStatus?: AppEntitlementAutomationLastRunStatus | null | undefined;
  none?: AppEntitlementAutomationRuleNone | null | undefined;
  updatedAt?: Date | null | undefined;
};

/** @internal */
export const AppEntitlementAutomation$inboundSchema: z.ZodType<
  AppEntitlementAutomation,
  z.ZodTypeDef,
  unknown
> = z.object({
  appEntitlementId: z.nullable(z.string()).optional(),
  appId: z.nullable(z.string()).optional(),
  basic: z.nullable(AppEntitlementAutomationRuleBasic$inboundSchema).optional(),
  cel: z.nullable(AppEntitlementAutomationRuleCEL$inboundSchema).optional(),
  createdAt: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
  deletedAt: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
  description: z.nullable(z.string()).optional(),
  displayName: z.nullable(z.string()).optional(),
  entitlements: z.nullable(
    AppEntitlementAutomationRuleEntitlement$inboundSchema,
  ).optional(),
  lastRunStatus: z.nullable(AppEntitlementAutomationLastRunStatus$inboundSchema)
    .optional(),
  none: z.nullable(AppEntitlementAutomationRuleNone$inboundSchema).optional(),
  updatedAt: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
});

export function appEntitlementAutomationFromJSON(
  jsonString: string,
): SafeParseResult<AppEntitlementAutomation, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AppEntitlementAutomation$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AppEntitlementAutomation' from JSON`,
  );
}
