/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { safeParse } from "../../../lib/schemas.js";
import { AppResource$inboundSchema, AppResource$outboundSchema, } from "./appresource.js";
import { AppResourceExpandMask$inboundSchema, AppResourceExpandMask$outboundSchema, } from "./appresourceexpandmask.js";
/** @internal */
export const AppResourceServiceUpdateRequest$inboundSchema = z.object({
    appResource: z.nullable(AppResource$inboundSchema).optional(),
    expandMask: z.nullable(AppResourceExpandMask$inboundSchema).optional(),
    updateMask: z.nullable(z.string()).optional(),
});
/** @internal */
export const AppResourceServiceUpdateRequest$outboundSchema = z.object({
    appResource: z.nullable(AppResource$outboundSchema).optional(),
    expandMask: z.nullable(AppResourceExpandMask$outboundSchema).optional(),
    updateMask: z.nullable(z.string()).optional(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export var AppResourceServiceUpdateRequest$;
(function (AppResourceServiceUpdateRequest$) {
    /** @deprecated use `AppResourceServiceUpdateRequest$inboundSchema` instead. */
    AppResourceServiceUpdateRequest$.inboundSchema = AppResourceServiceUpdateRequest$inboundSchema;
    /** @deprecated use `AppResourceServiceUpdateRequest$outboundSchema` instead. */
    AppResourceServiceUpdateRequest$.outboundSchema = AppResourceServiceUpdateRequest$outboundSchema;
})(AppResourceServiceUpdateRequest$ || (AppResourceServiceUpdateRequest$ = {}));
export function appResourceServiceUpdateRequestToJSON(appResourceServiceUpdateRequest) {
    return JSON.stringify(AppResourceServiceUpdateRequest$outboundSchema.parse(appResourceServiceUpdateRequest));
}
export function appResourceServiceUpdateRequestFromJSON(jsonString) {
    return safeParse(jsonString, (x) => AppResourceServiceUpdateRequest$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'AppResourceServiceUpdateRequest' from JSON`);
}
