/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * The ApprovalNeededPreference message.
 */
export type ApprovalNeededPreference = {
  /**
   * The enabled field.
   */
  enabled?: boolean | undefined;
  /**
   * The locked field.
   */
  locked?: boolean | undefined;
};

/** @internal */
export const ApprovalNeededPreference$inboundSchema: z.ZodType<
  ApprovalNeededPreference,
  z.ZodTypeDef,
  unknown
> = z.object({
  enabled: z.boolean().optional(),
  locked: z.boolean().optional(),
});
/** @internal */
export type ApprovalNeededPreference$Outbound = {
  enabled?: boolean | undefined;
  locked?: boolean | undefined;
};

/** @internal */
export const ApprovalNeededPreference$outboundSchema: z.ZodType<
  ApprovalNeededPreference$Outbound,
  z.ZodTypeDef,
  ApprovalNeededPreference
> = z.object({
  enabled: z.boolean().optional(),
  locked: z.boolean().optional(),
});

export function approvalNeededPreferenceToJSON(
  approvalNeededPreference: ApprovalNeededPreference,
): string {
  return JSON.stringify(
    ApprovalNeededPreference$outboundSchema.parse(approvalNeededPreference),
  );
}
export function approvalNeededPreferenceFromJSON(
  jsonString: string,
): SafeParseResult<ApprovalNeededPreference, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApprovalNeededPreference$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApprovalNeededPreference' from JSON`,
  );
}
