/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import {
  collectExtraKeys as collectExtraKeys$,
  safeParse,
} from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  AppResourceTypeView,
  AppResourceTypeView$inboundSchema,
} from "./appresourcetypeview.js";

/**
 * Contains an arbitrary serialized message along with a @type that describes the type of the serialized message.
 */
export type AppResourceTypeServiceListResponseExpanded = {
  /**
   * The type of the serialized message.
   */
  atType?: string | undefined;
  additionalProperties?: { [k: string]: any } | undefined;
};

/**
 * The AppResourceTypeServiceListResponse message contains a list of results and a nextPageToken if applicable.
 */
export type AppResourceTypeServiceListResponse = {
  /**
   * List of serialized related objects.
   */
  expanded?:
    | Array<AppResourceTypeServiceListResponseExpanded>
    | null
    | undefined;
  /**
   * The list of results containing up to X results, where X is the page size defined in the request.
   */
  list?: Array<AppResourceTypeView> | null | undefined;
  /**
   * The nextPageToken is shown for the next page if the number of results is larger than the max page size.
   *
   * @remarks
   *  The server returns one page of results and the nextPageToken until all results are retreived.
   *  To retrieve the next page, use the same request and append a pageToken field with the value of nextPageToken shown on the previous page.
   */
  nextPageToken?: string | null | undefined;
};

/** @internal */
export const AppResourceTypeServiceListResponseExpanded$inboundSchema:
  z.ZodType<AppResourceTypeServiceListResponseExpanded, z.ZodTypeDef, unknown> =
    collectExtraKeys$(
      z.object({
        "@type": z.string().optional(),
      }).catchall(z.any()),
      "additionalProperties",
      true,
    ).transform((v) => {
      return remap$(v, {
        "@type": "atType",
      });
    });

export function appResourceTypeServiceListResponseExpandedFromJSON(
  jsonString: string,
): SafeParseResult<
  AppResourceTypeServiceListResponseExpanded,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      AppResourceTypeServiceListResponseExpanded$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'AppResourceTypeServiceListResponseExpanded' from JSON`,
  );
}

/** @internal */
export const AppResourceTypeServiceListResponse$inboundSchema: z.ZodType<
  AppResourceTypeServiceListResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  expanded: z.nullable(
    z.array(z.lazy(() =>
      AppResourceTypeServiceListResponseExpanded$inboundSchema
    )),
  ).optional(),
  list: z.nullable(z.array(AppResourceTypeView$inboundSchema)).optional(),
  nextPageToken: z.nullable(z.string()).optional(),
});

export function appResourceTypeServiceListResponseFromJSON(
  jsonString: string,
): SafeParseResult<AppResourceTypeServiceListResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      AppResourceTypeServiceListResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AppResourceTypeServiceListResponse' from JSON`,
  );
}
