/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  AppUserCredential,
  AppUserCredential$inboundSchema,
  AppUserCredential$Outbound,
  AppUserCredential$outboundSchema,
} from "./appusercredential.js";

/**
 * The AppUserServiceListCredentialsResponse message.
 */
export type AppUserServiceListCredentialsResponse = {
  /**
   * The list field.
   */
  list?: Array<AppUserCredential> | null | undefined;
  /**
   * The nextPageToken field.
   */
  nextPageToken?: string | null | undefined;
};

/** @internal */
export const AppUserServiceListCredentialsResponse$inboundSchema: z.ZodType<
  AppUserServiceListCredentialsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  list: z.nullable(z.array(AppUserCredential$inboundSchema)).optional(),
  nextPageToken: z.nullable(z.string()).optional(),
});

/** @internal */
export type AppUserServiceListCredentialsResponse$Outbound = {
  list?: Array<AppUserCredential$Outbound> | null | undefined;
  nextPageToken?: string | null | undefined;
};

/** @internal */
export const AppUserServiceListCredentialsResponse$outboundSchema: z.ZodType<
  AppUserServiceListCredentialsResponse$Outbound,
  z.ZodTypeDef,
  AppUserServiceListCredentialsResponse
> = z.object({
  list: z.nullable(z.array(AppUserCredential$outboundSchema)).optional(),
  nextPageToken: z.nullable(z.string()).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AppUserServiceListCredentialsResponse$ {
  /** @deprecated use `AppUserServiceListCredentialsResponse$inboundSchema` instead. */
  export const inboundSchema =
    AppUserServiceListCredentialsResponse$inboundSchema;
  /** @deprecated use `AppUserServiceListCredentialsResponse$outboundSchema` instead. */
  export const outboundSchema =
    AppUserServiceListCredentialsResponse$outboundSchema;
  /** @deprecated use `AppUserServiceListCredentialsResponse$Outbound` instead. */
  export type Outbound = AppUserServiceListCredentialsResponse$Outbound;
}

export function appUserServiceListCredentialsResponseToJSON(
  appUserServiceListCredentialsResponse: AppUserServiceListCredentialsResponse,
): string {
  return JSON.stringify(
    AppUserServiceListCredentialsResponse$outboundSchema.parse(
      appUserServiceListCredentialsResponse,
    ),
  );
}

export function appUserServiceListCredentialsResponseFromJSON(
  jsonString: string,
): SafeParseResult<AppUserServiceListCredentialsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      AppUserServiceListCredentialsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AppUserServiceListCredentialsResponse' from JSON`,
  );
}
