/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

/**
 * The DeleteAutomationRequest message.
 */
export type AutomationsDeleteAutomationRequest = {};

/** @internal */
export type AutomationsDeleteAutomationRequest$Outbound = {};

/** @internal */
export const AutomationsDeleteAutomationRequest$outboundSchema: z.ZodType<
  AutomationsDeleteAutomationRequest$Outbound,
  z.ZodTypeDef,
  AutomationsDeleteAutomationRequest
> = z.object({});

export function automationsDeleteAutomationRequestToJSON(
  automationsDeleteAutomationRequest: AutomationsDeleteAutomationRequest,
): string {
  return JSON.stringify(
    AutomationsDeleteAutomationRequest$outboundSchema.parse(
      automationsDeleteAutomationRequest,
    ),
  );
}
