/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * C1BuiltInProviderConfig selects the ConductorOne built-in email provider.
 *
 * @remarks
 *  Emails are sent from no-reply@conductorone.com via the platform SendGrid account.
 *  Only supports sending to C1 users — external email addresses are not supported.
 *  No configuration fields required.
 */
export type C1BuiltInProviderConfig = {};

/** @internal */
export const C1BuiltInProviderConfig$inboundSchema: z.ZodType<
  C1BuiltInProviderConfig,
  z.ZodTypeDef,
  unknown
> = z.object({});
/** @internal */
export type C1BuiltInProviderConfig$Outbound = {};

/** @internal */
export const C1BuiltInProviderConfig$outboundSchema: z.ZodType<
  C1BuiltInProviderConfig$Outbound,
  z.ZodTypeDef,
  C1BuiltInProviderConfig
> = z.object({});

export function c1BuiltInProviderConfigToJSON(
  c1BuiltInProviderConfig: C1BuiltInProviderConfig,
): string {
  return JSON.stringify(
    C1BuiltInProviderConfig$outboundSchema.parse(c1BuiltInProviderConfig),
  );
}
export function c1BuiltInProviderConfigFromJSON(
  jsonString: string,
): SafeParseResult<C1BuiltInProviderConfig, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => C1BuiltInProviderConfig$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'C1BuiltInProviderConfig' from JSON`,
  );
}
