/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * C1ConnectorSyncProgressComponent renders a live connector sync status card.
 *
 * @remarks
 *  Subscribes to WebSocket updates for real-time sync lifecycle status.
 */
export type C1ConnectorSyncProgressComponent = {
  /**
   * The appId field.
   */
  appId?: string | null | undefined;
  /**
   * The connectorId field.
   */
  connectorId?: string | null | undefined;
  /**
   * The title field.
   */
  title?: string | null | undefined;
};

/** @internal */
export const C1ConnectorSyncProgressComponent$inboundSchema: z.ZodType<
  C1ConnectorSyncProgressComponent,
  z.ZodTypeDef,
  unknown
> = z.object({
  appId: z.nullable(z.string()).optional(),
  connectorId: z.nullable(z.string()).optional(),
  title: z.nullable(z.string()).optional(),
});

export function c1ConnectorSyncProgressComponentFromJSON(
  jsonString: string,
): SafeParseResult<C1ConnectorSyncProgressComponent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => C1ConnectorSyncProgressComponent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'C1ConnectorSyncProgressComponent' from JSON`,
  );
}
