/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { ConnectorCredential } from "./connectorcredential";
import { Expose, Type } from "class-transformer";

/**
 * The ConnectorServiceGetCredentialsResponse message.
 */
export class ConnectorServiceGetCredentialsResponse extends SpeakeasyBase {
    /**
     * The ConnectorCredential message.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "credential" })
    @Type(() => ConnectorCredential)
    connectorCredential?: ConnectorCredential;
}
