/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

/**
 * The CreateComplianceFrameworkAttributeValueRequest message.
 */
export type CreateComplianceFrameworkAttributeValueRequest = {
  /**
   * The value field.
   */
  value?: string | null | undefined;
};

/** @internal */
export type CreateComplianceFrameworkAttributeValueRequest$Outbound = {
  value?: string | null | undefined;
};

/** @internal */
export const CreateComplianceFrameworkAttributeValueRequest$outboundSchema:
  z.ZodType<
    CreateComplianceFrameworkAttributeValueRequest$Outbound,
    z.ZodTypeDef,
    CreateComplianceFrameworkAttributeValueRequest
  > = z.object({
    value: z.nullable(z.string()).optional(),
  });

export function createComplianceFrameworkAttributeValueRequestToJSON(
  createComplianceFrameworkAttributeValueRequest:
    CreateComplianceFrameworkAttributeValueRequest,
): string {
  return JSON.stringify(
    CreateComplianceFrameworkAttributeValueRequest$outboundSchema.parse(
      createComplianceFrameworkAttributeValueRequest,
    ),
  );
}
