/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import {
  FindingRoutingRule,
  FindingRoutingRule$Outbound,
  FindingRoutingRule$outboundSchema,
} from "./findingroutingrule.js";

/**
 * The CreateFindingRoutingRuleRequest message.
 */
export type CreateFindingRoutingRuleRequest = {
  /**
   * The FindingRoutingRule message.
   */
  findingRoutingRule?: FindingRoutingRule | undefined;
};

/** @internal */
export type CreateFindingRoutingRuleRequest$Outbound = {
  routingRule?: FindingRoutingRule$Outbound | undefined;
};

/** @internal */
export const CreateFindingRoutingRuleRequest$outboundSchema: z.ZodType<
  CreateFindingRoutingRuleRequest$Outbound,
  z.ZodTypeDef,
  CreateFindingRoutingRuleRequest
> = z.object({
  findingRoutingRule: FindingRoutingRule$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    findingRoutingRule: "routingRule",
  });
});

export function createFindingRoutingRuleRequestToJSON(
  createFindingRoutingRuleRequest: CreateFindingRoutingRuleRequest,
): string {
  return JSON.stringify(
    CreateFindingRoutingRuleRequest$outboundSchema.parse(
      createFindingRoutingRuleRequest,
    ),
  );
}
