/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { Decoy, Decoy$inboundSchema } from "./decoy.js";

/**
 * The DecoyServiceUpdateResponse message.
 */
export type DecoyServiceUpdateResponse = {
  decoy?: Decoy | null | undefined;
};

/** @internal */
export const DecoyServiceUpdateResponse$inboundSchema: z.ZodType<
  DecoyServiceUpdateResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  decoy: z.nullable(Decoy$inboundSchema).optional(),
});

export function decoyServiceUpdateResponseFromJSON(
  jsonString: string,
): SafeParseResult<DecoyServiceUpdateResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DecoyServiceUpdateResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DecoyServiceUpdateResponse' from JSON`,
  );
}
