/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * DeleteAppEntitlementEntitlementOwnerResponse is the empty response for deleting an entitlement ownership source on an entitlement.
 */
export type DeleteAppEntitlementEntitlementOwnerResponse = {};

/** @internal */
export const DeleteAppEntitlementEntitlementOwnerResponse$inboundSchema:
  z.ZodType<
    DeleteAppEntitlementEntitlementOwnerResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({});

export function deleteAppEntitlementEntitlementOwnerResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  DeleteAppEntitlementEntitlementOwnerResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      DeleteAppEntitlementEntitlementOwnerResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'DeleteAppEntitlementEntitlementOwnerResponse' from JSON`,
  );
}
