/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * The DelegatedProvision message.
 */
export class DelegatedProvision extends SpeakeasyBase {
    /**
     * The appId field.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "appId" })
    appId?: string;

    /**
     * The entitlementId field.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "entitlementId" })
    entitlementId?: string;
}
