/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import {
  UserRef,
  UserRef$Outbound,
  UserRef$outboundSchema,
} from "./userref.js";

/**
 * DeleteUserOwnerRequest is the request for deleting a user ownership source.
 */
export type DeleteAppUserOwnerRequest = {
  /**
   * A reference to a user.
   */
  userRef?: UserRef | undefined;
};

/** @internal */
export type DeleteAppUserOwnerRequest$Outbound = {
  userRef?: UserRef$Outbound | undefined;
};

/** @internal */
export const DeleteAppUserOwnerRequest$outboundSchema: z.ZodType<
  DeleteAppUserOwnerRequest$Outbound,
  z.ZodTypeDef,
  DeleteAppUserOwnerRequest
> = z.object({
  userRef: UserRef$outboundSchema.optional(),
});

export function deleteAppUserOwnerRequestToJSON(
  deleteAppUserOwnerRequest: DeleteAppUserOwnerRequest,
): string {
  return JSON.stringify(
    DeleteAppUserOwnerRequest$outboundSchema.parse(deleteAppUserOwnerRequest),
  );
}
