/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import {
  UserRef,
  UserRef$Outbound,
  UserRef$outboundSchema,
} from "./userref.js";

/**
 * DeleteAppResourceUserOwnerRequest is the request for deleting a user ownership source on a resource.
 */
export type DeleteAppResourceUserOwnerRequest = {
  /**
   * A reference to a user.
   */
  userRef?: UserRef | undefined;
};

/** @internal */
export type DeleteAppResourceUserOwnerRequest$Outbound = {
  userRef?: UserRef$Outbound | undefined;
};

/** @internal */
export const DeleteAppResourceUserOwnerRequest$outboundSchema: z.ZodType<
  DeleteAppResourceUserOwnerRequest$Outbound,
  z.ZodTypeDef,
  DeleteAppResourceUserOwnerRequest
> = z.object({
  userRef: UserRef$outboundSchema.optional(),
});

export function deleteAppResourceUserOwnerRequestToJSON(
  deleteAppResourceUserOwnerRequest: DeleteAppResourceUserOwnerRequest,
): string {
  return JSON.stringify(
    DeleteAppResourceUserOwnerRequest$outboundSchema.parse(
      deleteAppResourceUserOwnerRequest,
    ),
  );
}
