/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  DirectoryAccountFilterAll,
  DirectoryAccountFilterAll$inboundSchema,
} from "./directoryaccountfilterall.js";
import {
  DirectoryAccountFilterCel,
  DirectoryAccountFilterCel$inboundSchema,
} from "./directoryaccountfiltercel.js";
import {
  DirectoryMergeConfig,
  DirectoryMergeConfig$inboundSchema,
} from "./directorymergeconfig.js";

/**
 * This object indicates that an app is also a directory.
 *
 * @remarks
 *
 * This message contains a oneof named account_filter. Only a single field of the following list may be set at a time:
 *   - all
 *   - celExpression
 */
export type Directory = {
  all?: DirectoryAccountFilterAll | null | undefined;
  /**
   * The ID of the app associated with the directory.
   */
  appId?: string | null | undefined;
  celExpression?: DirectoryAccountFilterCel | null | undefined;
  createdAt?: Date | null | undefined;
  deletedAt?: Date | null | undefined;
  /**
   * DirectoryMergeConfig configures how AppUsers from this directory are matched to C1 Users.
   */
  directoryMergeConfig?: DirectoryMergeConfig | undefined;
  updatedAt?: Date | null | undefined;
};

/** @internal */
export const Directory$inboundSchema: z.ZodType<
  Directory,
  z.ZodTypeDef,
  unknown
> = z.object({
  all: z.nullable(DirectoryAccountFilterAll$inboundSchema).optional(),
  appId: z.nullable(z.string()).optional(),
  celExpression: z.nullable(DirectoryAccountFilterCel$inboundSchema).optional(),
  createdAt: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
  deletedAt: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
  mergeConfig: DirectoryMergeConfig$inboundSchema.optional(),
  updatedAt: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
}).transform((v) => {
  return remap$(v, {
    "mergeConfig": "directoryMergeConfig",
  });
});

export function directoryFromJSON(
  jsonString: string,
): SafeParseResult<Directory, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Directory$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Directory' from JSON`,
  );
}
