/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * The EntitlementInclusionAll message.
 */
export type EntitlementInclusionAll = {};

/** @internal */
export const EntitlementInclusionAll$inboundSchema: z.ZodType<
  EntitlementInclusionAll,
  z.ZodTypeDef,
  unknown
> = z.object({});
/** @internal */
export type EntitlementInclusionAll$Outbound = {};

/** @internal */
export const EntitlementInclusionAll$outboundSchema: z.ZodType<
  EntitlementInclusionAll$Outbound,
  z.ZodTypeDef,
  EntitlementInclusionAll
> = z.object({});

export function entitlementInclusionAllToJSON(
  entitlementInclusionAll: EntitlementInclusionAll,
): string {
  return JSON.stringify(
    EntitlementInclusionAll$outboundSchema.parse(entitlementInclusionAll),
  );
}
export function entitlementInclusionAllFromJSON(
  jsonString: string,
): SafeParseResult<EntitlementInclusionAll, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EntitlementInclusionAll$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EntitlementInclusionAll' from JSON`,
  );
}
