/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Transform } from "class-transformer";

/**
 * The ErroredAction message.
 */
export class ErroredAction extends SpeakeasyBase {
    /**
     * The description field.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "description" })
    description?: string;

    /**
     * The errorCode field.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "errorCode" })
    errorCode?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "erroredAt" })
    @Transform(({ value }) => new Date(value), { toClassOnly: true })
    erroredAt?: Date;
}
