/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import {
  ExportToDatasource,
  ExportToDatasource$Outbound,
  ExportToDatasource$outboundSchema,
} from "./exporttodatasource.js";

/**
 * The Exporter message.
 *
 * @remarks
 *
 * This message contains a oneof named export_to. Only a single field of the following list may be set at a time:
 *   - datasource
 */
export type ExporterInput = {
  datasource?: ExportToDatasource | null | undefined;
  /**
   * The displayName field.
   */
  displayName?: string | null | undefined;
};

/** @internal */
export type ExporterInput$Outbound = {
  datasource?: ExportToDatasource$Outbound | null | undefined;
  displayName?: string | null | undefined;
};

/** @internal */
export const ExporterInput$outboundSchema: z.ZodType<
  ExporterInput$Outbound,
  z.ZodTypeDef,
  ExporterInput
> = z.object({
  datasource: z.nullable(ExportToDatasource$outboundSchema).optional(),
  displayName: z.nullable(z.string()).optional(),
});

export function exporterInputToJSON(exporterInput: ExporterInput): string {
  return JSON.stringify(ExporterInput$outboundSchema.parse(exporterInput));
}
