/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * ExpressionProvisioner evaluates CEL expressions to determine provisioners.
 */
export type ExpressionProvisioner = {
  /**
   * Whether the provisioner can reassign the task.
   */
  allowReassignment?: boolean | undefined;
  /**
   * The CEL expressions to evaluate.
   */
  expressions?: Array<string> | null | undefined;
  /**
   * Fallback user IDs if expression evaluation yields no users.
   */
  fallbackUserIds?: Array<string> | null | undefined;
};

/** @internal */
export const ExpressionProvisioner$inboundSchema: z.ZodType<
  ExpressionProvisioner,
  z.ZodTypeDef,
  unknown
> = z.object({
  allowReassignment: z.boolean().optional(),
  expressions: z.nullable(z.array(z.string())).optional(),
  fallbackUserIds: z.nullable(z.array(z.string())).optional(),
});
/** @internal */
export type ExpressionProvisioner$Outbound = {
  allowReassignment?: boolean | undefined;
  expressions?: Array<string> | null | undefined;
  fallbackUserIds?: Array<string> | null | undefined;
};

/** @internal */
export const ExpressionProvisioner$outboundSchema: z.ZodType<
  ExpressionProvisioner$Outbound,
  z.ZodTypeDef,
  ExpressionProvisioner
> = z.object({
  allowReassignment: z.boolean().optional(),
  expressions: z.nullable(z.array(z.string())).optional(),
  fallbackUserIds: z.nullable(z.array(z.string())).optional(),
});

export function expressionProvisionerToJSON(
  expressionProvisioner: ExpressionProvisioner,
): string {
  return JSON.stringify(
    ExpressionProvisioner$outboundSchema.parse(expressionProvisioner),
  );
}
export function expressionProvisionerFromJSON(
  jsonString: string,
): SafeParseResult<ExpressionProvisioner, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ExpressionProvisioner$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ExpressionProvisioner' from JSON`,
  );
}
