/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

export const EventTypes = {
  FindingAuditEventTypeUnspecified: "FINDING_AUDIT_EVENT_TYPE_UNSPECIFIED",
  FindingAuditEventTypeCreated: "FINDING_AUDIT_EVENT_TYPE_CREATED",
  FindingAuditEventTypeStateChanged: "FINDING_AUDIT_EVENT_TYPE_STATE_CHANGED",
  FindingAuditEventTypeSnoozed: "FINDING_AUDIT_EVENT_TYPE_SNOOZED",
  FindingAuditEventTypeSnoozeExpired: "FINDING_AUDIT_EVENT_TYPE_SNOOZE_EXPIRED",
  FindingAuditEventTypeRiskAccepted: "FINDING_AUDIT_EVENT_TYPE_RISK_ACCEPTED",
  FindingAuditEventTypeRiskAcceptanceExpired:
    "FINDING_AUDIT_EVENT_TYPE_RISK_ACCEPTANCE_EXPIRED",
  FindingAuditEventTypeSuppressed: "FINDING_AUDIT_EVENT_TYPE_SUPPRESSED",
  FindingAuditEventTypeUnsuppressed: "FINDING_AUDIT_EVENT_TYPE_UNSUPPRESSED",
  FindingAuditEventTypeResolved: "FINDING_AUDIT_EVENT_TYPE_RESOLVED",
  FindingAuditEventTypeReopened: "FINDING_AUDIT_EVENT_TYPE_REOPENED",
  FindingAuditEventTypeOwnerChanged: "FINDING_AUDIT_EVENT_TYPE_OWNER_CHANGED",
  FindingAuditEventTypeSeverityOverridden:
    "FINDING_AUDIT_EVENT_TYPE_SEVERITY_OVERRIDDEN",
  FindingAuditEventTypeComment: "FINDING_AUDIT_EVENT_TYPE_COMMENT",
  FindingAuditEventTypeTaskCreated: "FINDING_AUDIT_EVENT_TYPE_TASK_CREATED",
  FindingAuditEventTypeTaskCancelled: "FINDING_AUDIT_EVENT_TYPE_TASK_CANCELLED",
  FindingAuditEventTypeEvidenceUpdated:
    "FINDING_AUDIT_EVENT_TYPE_EVIDENCE_UPDATED",
  FindingAuditEventTypeRoutingEvaluated:
    "FINDING_AUDIT_EVENT_TYPE_ROUTING_EVALUATED",
} as const;
export type EventTypes = OpenEnum<typeof EventTypes>;

/**
 * The FindingAuditServiceSearchRequest message.
 */
export type FindingAuditServiceSearchRequest = {
  /**
   * The actorPrincipalId field.
   */
  actorPrincipalId?: string | undefined;
  /**
   * Partial match via full-text search over the denormalized actor email
   *
   * @remarks
   *  / display name column.
   */
  actorSubject?: string | undefined;
  /**
   * Empty skips the filter; non-empty must be a 27-char alphanumeric id.
   */
  appId?: string | undefined;
  /**
   * Filter by one or more event types. Empty means any.
   */
  eventTypes?: Array<EventTypes> | null | undefined;
  /**
   * Filter to a single finding. The detail-page timeline uses this.
   *
   * @remarks
   *  Empty skips the filter; non-empty must be a 27-char alphanumeric id.
   */
  findingId?: string | undefined;
  /**
   * The pageSize field.
   */
  pageSize?: number | undefined;
  /**
   * The pageToken field.
   */
  pageToken?: string | undefined;
  since?: Date | undefined;
  until?: Date | undefined;
};

/** @internal */
export const EventTypes$outboundSchema: z.ZodType<
  string,
  z.ZodTypeDef,
  EventTypes
> = openEnums.outboundSchema(EventTypes);

/** @internal */
export type FindingAuditServiceSearchRequest$Outbound = {
  actorPrincipalId?: string | undefined;
  actorSubject?: string | undefined;
  appId?: string | undefined;
  eventTypes?: Array<string> | null | undefined;
  findingId?: string | undefined;
  pageSize?: number | undefined;
  pageToken?: string | undefined;
  since?: string | undefined;
  until?: string | undefined;
};

/** @internal */
export const FindingAuditServiceSearchRequest$outboundSchema: z.ZodType<
  FindingAuditServiceSearchRequest$Outbound,
  z.ZodTypeDef,
  FindingAuditServiceSearchRequest
> = z.object({
  actorPrincipalId: z.string().optional(),
  actorSubject: z.string().optional(),
  appId: z.string().optional(),
  eventTypes: z.nullable(z.array(EventTypes$outboundSchema)).optional(),
  findingId: z.string().optional(),
  pageSize: z.number().int().optional(),
  pageToken: z.string().optional(),
  since: z.date().transform(v => v.toISOString()).optional(),
  until: z.date().transform(v => v.toISOString()).optional(),
});

export function findingAuditServiceSearchRequestToJSON(
  findingAuditServiceSearchRequest: FindingAuditServiceSearchRequest,
): string {
  return JSON.stringify(
    FindingAuditServiceSearchRequest$outboundSchema.parse(
      findingAuditServiceSearchRequest,
    ),
  );
}
