/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  FunctionInvocation,
  FunctionInvocation$inboundSchema,
  FunctionInvocation$Outbound,
  FunctionInvocation$outboundSchema,
} from "./functioninvocation.js";

/**
 * The FunctionsInvocationServiceGetResponse message.
 */
export type FunctionsInvocationServiceGetResponse = {
  /**
   * The FunctionInvocation message.
   */
  functionInvocation?: FunctionInvocation | undefined;
};

/** @internal */
export const FunctionsInvocationServiceGetResponse$inboundSchema: z.ZodType<
  FunctionsInvocationServiceGetResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  invocation: FunctionInvocation$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "invocation": "functionInvocation",
  });
});

/** @internal */
export type FunctionsInvocationServiceGetResponse$Outbound = {
  invocation?: FunctionInvocation$Outbound | undefined;
};

/** @internal */
export const FunctionsInvocationServiceGetResponse$outboundSchema: z.ZodType<
  FunctionsInvocationServiceGetResponse$Outbound,
  z.ZodTypeDef,
  FunctionsInvocationServiceGetResponse
> = z.object({
  functionInvocation: FunctionInvocation$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    functionInvocation: "invocation",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace FunctionsInvocationServiceGetResponse$ {
  /** @deprecated use `FunctionsInvocationServiceGetResponse$inboundSchema` instead. */
  export const inboundSchema =
    FunctionsInvocationServiceGetResponse$inboundSchema;
  /** @deprecated use `FunctionsInvocationServiceGetResponse$outboundSchema` instead. */
  export const outboundSchema =
    FunctionsInvocationServiceGetResponse$outboundSchema;
  /** @deprecated use `FunctionsInvocationServiceGetResponse$Outbound` instead. */
  export type Outbound = FunctionsInvocationServiceGetResponse$Outbound;
}

export function functionsInvocationServiceGetResponseToJSON(
  functionsInvocationServiceGetResponse: FunctionsInvocationServiceGetResponse,
): string {
  return JSON.stringify(
    FunctionsInvocationServiceGetResponse$outboundSchema.parse(
      functionsInvocationServiceGetResponse,
    ),
  );
}

export function functionsInvocationServiceGetResponseFromJSON(
  jsonString: string,
): SafeParseResult<FunctionsInvocationServiceGetResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      FunctionsInvocationServiceGetResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FunctionsInvocationServiceGetResponse' from JSON`,
  );
}
