/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

/**
 * The FunctionsServiceDeleteFunctionRequest message.
 */
export type FunctionsServiceDeleteFunctionRequest = {};

/** @internal */
export type FunctionsServiceDeleteFunctionRequest$Outbound = {};

/** @internal */
export const FunctionsServiceDeleteFunctionRequest$outboundSchema: z.ZodType<
  FunctionsServiceDeleteFunctionRequest$Outbound,
  z.ZodTypeDef,
  FunctionsServiceDeleteFunctionRequest
> = z.object({});

export function functionsServiceDeleteFunctionRequestToJSON(
  functionsServiceDeleteFunctionRequest: FunctionsServiceDeleteFunctionRequest,
): string {
  return JSON.stringify(
    FunctionsServiceDeleteFunctionRequest$outboundSchema.parse(
      functionsServiceDeleteFunctionRequest,
    ),
  );
}
