/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  FunctionTestResult,
  FunctionTestResult$inboundSchema,
} from "./functiontestresult.js";

/**
 * FunctionsServiceTestResponse contains test execution results.
 */
export type FunctionsServiceTestResponse = {
  /**
   * FunctionTestResult contains the result of a single test case execution.
   */
  functionTestResult?: FunctionTestResult | undefined;
  /**
   * All test results.
   */
  results?: Array<FunctionTestResult> | null | undefined;
};

/** @internal */
export const FunctionsServiceTestResponse$inboundSchema: z.ZodType<
  FunctionsServiceTestResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  result: FunctionTestResult$inboundSchema.optional(),
  results: z.nullable(z.array(FunctionTestResult$inboundSchema)).optional(),
}).transform((v) => {
  return remap$(v, {
    "result": "functionTestResult",
  });
});

export function functionsServiceTestResponseFromJSON(
  jsonString: string,
): SafeParseResult<FunctionsServiceTestResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FunctionsServiceTestResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FunctionsServiceTestResponse' from JSON`,
  );
}
