/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import {
  collectExtraKeys as collectExtraKeys$,
  safeParse,
} from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  AppEntitlementProxyView,
  AppEntitlementProxyView$inboundSchema,
} from "./appentitlementproxyview.js";

/**
 * Contains an arbitrary serialized message along with a @type that describes the type of the serialized message.
 */
export type GetAppEntitlementProxyResponseExpanded = {
  /**
   * The type of the serialized message.
   */
  atType?: string | undefined;
  additionalProperties?: { [k: string]: any } | undefined;
};

/**
 * The GetAppEntitlementProxyResponse message.
 */
export type GetAppEntitlementProxyResponse = {
  appProxyEntitlementView?: AppEntitlementProxyView | null | undefined;
  /**
   * The expanded field.
   */
  expanded?: Array<GetAppEntitlementProxyResponseExpanded> | null | undefined;
};

/** @internal */
export const GetAppEntitlementProxyResponseExpanded$inboundSchema: z.ZodType<
  GetAppEntitlementProxyResponseExpanded,
  z.ZodTypeDef,
  unknown
> = collectExtraKeys$(
  z.object({
    "@type": z.string().optional(),
  }).catchall(z.any()),
  "additionalProperties",
  true,
).transform((v) => {
  return remap$(v, {
    "@type": "atType",
  });
});

export function getAppEntitlementProxyResponseExpandedFromJSON(
  jsonString: string,
): SafeParseResult<GetAppEntitlementProxyResponseExpanded, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetAppEntitlementProxyResponseExpanded$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetAppEntitlementProxyResponseExpanded' from JSON`,
  );
}

/** @internal */
export const GetAppEntitlementProxyResponse$inboundSchema: z.ZodType<
  GetAppEntitlementProxyResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  appProxyEntitlementView: z.nullable(AppEntitlementProxyView$inboundSchema)
    .optional(),
  expanded: z.nullable(
    z.array(z.lazy(() => GetAppEntitlementProxyResponseExpanded$inboundSchema)),
  ).optional(),
});

export function getAppEntitlementProxyResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetAppEntitlementProxyResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetAppEntitlementProxyResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetAppEntitlementProxyResponse' from JSON`,
  );
}
