/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { AWSExternalID, AWSExternalID$inboundSchema } from "./awsexternalid.js";

/**
 * The GetAWSExternalIDResponse message.
 */
export type GetAWSExternalIDResponse = {
  awsExternalId?: AWSExternalID | null | undefined;
};

/** @internal */
export const GetAWSExternalIDResponse$inboundSchema: z.ZodType<
  GetAWSExternalIDResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  awsExternalId: z.nullable(AWSExternalID$inboundSchema).optional(),
});

export function getAWSExternalIDResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetAWSExternalIDResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetAWSExternalIDResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetAWSExternalIDResponse' from JSON`,
  );
}
