/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * The GetConnectorSyncDownloadURLResponse message.
 */
export type GetConnectorSyncDownloadURLResponse = {
  /**
   * Short-lived download URL for the connector sync artifact
   */
  downloadUrl?: string | undefined;
};

/** @internal */
export const GetConnectorSyncDownloadURLResponse$inboundSchema: z.ZodType<
  GetConnectorSyncDownloadURLResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  downloadUrl: z.string().optional(),
});

export function getConnectorSyncDownloadURLResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetConnectorSyncDownloadURLResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetConnectorSyncDownloadURLResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetConnectorSyncDownloadURLResponse' from JSON`,
  );
}
