/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  TFSchemaMapping,
  TFSchemaMapping$inboundSchema,
} from "./tfschemamapping.js";

/**
 * The GetSchemaResponse message.
 */
export type GetSchemaResponse = {
  schema?: TFSchemaMapping | null | undefined;
};

/** @internal */
export const GetSchemaResponse$inboundSchema: z.ZodType<
  GetSchemaResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  schema: z.nullable(TFSchemaMapping$inboundSchema).optional(),
});

export function getSchemaResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetSchemaResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetSchemaResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetSchemaResponse' from JSON`,
  );
}
