/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * The type field.
 */
export const GraphNodeType = {
  GraphNodeTypeUnspecified: "GRAPH_NODE_TYPE_UNSPECIFIED",
  GraphNodeTypeUser: "GRAPH_NODE_TYPE_USER",
  GraphNodeTypeAppUser: "GRAPH_NODE_TYPE_APP_USER",
  GraphNodeTypeApp: "GRAPH_NODE_TYPE_APP",
  GraphNodeTypeResourceType: "GRAPH_NODE_TYPE_RESOURCE_TYPE",
  GraphNodeTypeResource: "GRAPH_NODE_TYPE_RESOURCE",
  GraphNodeTypeEntitlement: "GRAPH_NODE_TYPE_ENTITLEMENT",
  GraphNodeTypeGrant: "GRAPH_NODE_TYPE_GRANT",
} as const;
/**
 * The type field.
 */
export type GraphNodeType = OpenEnum<typeof GraphNodeType>;

/**
 * A node in the access graph.
 */
export type GraphNode = {
  /**
   * The appId field.
   */
  appId?: string | undefined;
  /**
   * The displayName field.
   */
  displayName?: string | undefined;
  /**
   * The id field.
   */
  id?: string | undefined;
  /**
   * The resourceTypeId field.
   */
  resourceTypeId?: string | undefined;
  /**
   * The type field.
   */
  type?: GraphNodeType | undefined;
};

/** @internal */
export const GraphNodeType$inboundSchema: z.ZodType<
  GraphNodeType,
  z.ZodTypeDef,
  unknown
> = openEnums.inboundSchema(GraphNodeType);

/** @internal */
export const GraphNode$inboundSchema: z.ZodType<
  GraphNode,
  z.ZodTypeDef,
  unknown
> = z.object({
  appId: z.string().optional(),
  displayName: z.string().optional(),
  id: z.string().optional(),
  resourceTypeId: z.string().optional(),
  type: GraphNodeType$inboundSchema.optional(),
});

export function graphNodeFromJSON(
  jsonString: string,
): SafeParseResult<GraphNode, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GraphNode$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GraphNode' from JSON`,
  );
}
