/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * The GroupAuthzVault message.
 */
export type GroupAuthzVault = {};

/** @internal */
export const GroupAuthzVault$inboundSchema: z.ZodType<
  GroupAuthzVault,
  z.ZodTypeDef,
  unknown
> = z.object({});
/** @internal */
export type GroupAuthzVault$Outbound = {};

/** @internal */
export const GroupAuthzVault$outboundSchema: z.ZodType<
  GroupAuthzVault$Outbound,
  z.ZodTypeDef,
  GroupAuthzVault
> = z.object({});

export function groupAuthzVaultToJSON(
  groupAuthzVault: GroupAuthzVault,
): string {
  return JSON.stringify(GroupAuthzVault$outboundSchema.parse(groupAuthzVault));
}
export function groupAuthzVaultFromJSON(
  jsonString: string,
): SafeParseResult<GroupAuthzVault, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GroupAuthzVault$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GroupAuthzVault' from JSON`,
  );
}
