/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { Hook, Hook$inboundSchema } from "./hook.js";

/**
 * The HooksServiceGetResponse message.
 */
export type HooksServiceGetResponse = {
  /**
   * Hook represents a customer-configured interception point for tool calls.
   *
   * @remarks
   *
   * This message contains a oneof named hook_type. Only a single field of the following list may be set at a time:
   *   - function
   *   - builtinPattern
   */
  hook?: Hook | undefined;
};

/** @internal */
export const HooksServiceGetResponse$inboundSchema: z.ZodType<
  HooksServiceGetResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  hook: Hook$inboundSchema.optional(),
});

export function hooksServiceGetResponseFromJSON(
  jsonString: string,
): SafeParseResult<HooksServiceGetResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => HooksServiceGetResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'HooksServiceGetResponse' from JSON`,
  );
}
