/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import {
  HookRef,
  HookRef$Outbound,
  HookRef$outboundSchema,
} from "./hookref.js";

/**
 * The HooksSearchRequest message.
 */
export type HooksSearchRequest = {
  /**
   * The pageSize field.
   */
  pageSize?: number | null | undefined;
  /**
   * The pageToken field.
   */
  pageToken?: string | null | undefined;
  /**
   * The query field.
   */
  query?: string | null | undefined;
  /**
   * The refs field.
   */
  refs?: Array<HookRef> | null | undefined;
};

/** @internal */
export type HooksSearchRequest$Outbound = {
  pageSize?: number | null | undefined;
  pageToken?: string | null | undefined;
  query?: string | null | undefined;
  refs?: Array<HookRef$Outbound> | null | undefined;
};

/** @internal */
export const HooksSearchRequest$outboundSchema: z.ZodType<
  HooksSearchRequest$Outbound,
  z.ZodTypeDef,
  HooksSearchRequest
> = z.object({
  pageSize: z.nullable(z.number().int()).optional(),
  pageToken: z.nullable(z.string()).optional(),
  query: z.nullable(z.string()).optional(),
  refs: z.nullable(z.array(HookRef$outboundSchema)).optional(),
});

export function hooksSearchRequestToJSON(
  hooksSearchRequest: HooksSearchRequest,
): string {
  return JSON.stringify(
    HooksSearchRequest$outboundSchema.parse(hooksSearchRequest),
  );
}
