/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  LocalUserInvitation,
  LocalUserInvitation$inboundSchema,
} from "./localuserinvitation.js";

/**
 * The LocalUserInvitationServiceCreateResponse message.
 */
export type LocalUserInvitationServiceCreateResponse = {
  /**
   * LocalUserInvitation is the public representation of a per-directory user invitation.
   */
  localUserInvitation?: LocalUserInvitation | undefined;
};

/** @internal */
export const LocalUserInvitationServiceCreateResponse$inboundSchema: z.ZodType<
  LocalUserInvitationServiceCreateResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  invitation: LocalUserInvitation$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "invitation": "localUserInvitation",
  });
});

export function localUserInvitationServiceCreateResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  LocalUserInvitationServiceCreateResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      LocalUserInvitationServiceCreateResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'LocalUserInvitationServiceCreateResponse' from JSON`,
  );
}
