/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

/**
 * The manager approval object provides configuration options for approval when the target of the approval is the manager of the user in the task.
 */
export type ManagerApprovalInput = {
  /**
   * Configuration to allow self approval if the target user is their own manager. This may occur if a service account has an identity user and manager specified as the same person.
   */
  allowSelfApproval?: boolean | null | undefined;
  /**
   * Configuration to allow a fallback if no manager is found.
   */
  fallback?: boolean | null | undefined;
  /**
   * Configuration to specific which users to fallback to if fallback is enabled and no manager is found.
   */
  fallbackUserIds?: Array<string> | null | undefined;
  /**
   * Configuration to require distinct approvers across approval steps of a rule.
   */
  requireDistinctApprovers?: boolean | undefined;
};

/** @internal */
export type ManagerApprovalInput$Outbound = {
  allowSelfApproval?: boolean | null | undefined;
  fallback?: boolean | null | undefined;
  fallbackUserIds?: Array<string> | null | undefined;
  requireDistinctApprovers?: boolean | undefined;
};

/** @internal */
export const ManagerApprovalInput$outboundSchema: z.ZodType<
  ManagerApprovalInput$Outbound,
  z.ZodTypeDef,
  ManagerApprovalInput
> = z.object({
  allowSelfApproval: z.nullable(z.boolean()).optional(),
  fallback: z.nullable(z.boolean()).optional(),
  fallbackUserIds: z.nullable(z.array(z.string())).optional(),
  requireDistinctApprovers: z.boolean().optional(),
});

export function managerApprovalInputToJSON(
  managerApprovalInput: ManagerApprovalInput,
): string {
  return JSON.stringify(
    ManagerApprovalInput$outboundSchema.parse(managerApprovalInput),
  );
}
