/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { safeParse } from "../../../lib/schemas.js";
/** @internal */
export const ManualAutomationTrigger$inboundSchema = z.object({});
/** @internal */
export const ManualAutomationTrigger$outboundSchema = z.object({});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export var ManualAutomationTrigger$;
(function (ManualAutomationTrigger$) {
    /** @deprecated use `ManualAutomationTrigger$inboundSchema` instead. */
    ManualAutomationTrigger$.inboundSchema = ManualAutomationTrigger$inboundSchema;
    /** @deprecated use `ManualAutomationTrigger$outboundSchema` instead. */
    ManualAutomationTrigger$.outboundSchema = ManualAutomationTrigger$outboundSchema;
})(ManualAutomationTrigger$ || (ManualAutomationTrigger$ = {}));
export function manualAutomationTriggerToJSON(manualAutomationTrigger) {
    return JSON.stringify(ManualAutomationTrigger$outboundSchema.parse(manualAutomationTrigger));
}
export function manualAutomationTriggerFromJSON(jsonString) {
    return safeParse(jsonString, (x) => ManualAutomationTrigger$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'ManualAutomationTrigger' from JSON`);
}
