/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

/**
 * MCPAccessProfileServiceDeleteRequest deletes an MCP access profile (soft delete).
 */
export type MCPAccessProfileServiceDeleteRequest = {};

/** @internal */
export type MCPAccessProfileServiceDeleteRequest$Outbound = {};

/** @internal */
export const MCPAccessProfileServiceDeleteRequest$outboundSchema: z.ZodType<
  MCPAccessProfileServiceDeleteRequest$Outbound,
  z.ZodTypeDef,
  MCPAccessProfileServiceDeleteRequest
> = z.object({});

export function mcpAccessProfileServiceDeleteRequestToJSON(
  mcpAccessProfileServiceDeleteRequest: MCPAccessProfileServiceDeleteRequest,
): string {
  return JSON.stringify(
    MCPAccessProfileServiceDeleteRequest$outboundSchema.parse(
      mcpAccessProfileServiceDeleteRequest,
    ),
  );
}
