/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * MCPAccessProfileToolBinding represents a binding between an access profile and a tool.
 */
export type MCPAccessProfileToolBinding = {
  /**
   * Access profile identifier.
   */
  accessProfileId?: string | undefined;
  /**
   * App identifier.
   */
  appId?: string | undefined;
  /**
   * Connector identifier.
   */
  connectorId?: string | undefined;
  createdAt?: Date | undefined;
  deletedAt?: Date | undefined;
  /**
   * MCP tool identifier.
   */
  mcpToolId?: string | undefined;
  updatedAt?: Date | undefined;
};

/** @internal */
export const MCPAccessProfileToolBinding$inboundSchema: z.ZodType<
  MCPAccessProfileToolBinding,
  z.ZodTypeDef,
  unknown
> = z.object({
  accessProfileId: z.string().optional(),
  appId: z.string().optional(),
  connectorId: z.string().optional(),
  createdAt: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  deletedAt: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  mcpToolId: z.string().optional(),
  updatedAt: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
});

export function mcpAccessProfileToolBindingFromJSON(
  jsonString: string,
): SafeParseResult<MCPAccessProfileToolBinding, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MCPAccessProfileToolBinding$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MCPAccessProfileToolBinding' from JSON`,
  );
}
