/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  RequestableConnector,
  RequestableConnector$inboundSchema,
} from "./requestableconnector.js";

/**
 * MCPAccessProfileServiceListRequestableConnectorsResponse returns connector references
 *
 * @remarks
 *  that have requestable MCP access profiles.
 */
export type MCPAccessProfileServiceListRequestableConnectorsResponse = {
  /**
   * List of connectors with requestable MCP access profiles.
   */
  connectors?: Array<RequestableConnector> | null | undefined;
};

/** @internal */
export const MCPAccessProfileServiceListRequestableConnectorsResponse$inboundSchema:
  z.ZodType<
    MCPAccessProfileServiceListRequestableConnectorsResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    connectors: z.nullable(z.array(RequestableConnector$inboundSchema))
      .optional(),
  });

export function mcpAccessProfileServiceListRequestableConnectorsResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  MCPAccessProfileServiceListRequestableConnectorsResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      MCPAccessProfileServiceListRequestableConnectorsResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'MCPAccessProfileServiceListRequestableConnectorsResponse' from JSON`,
  );
}
