/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const AllowedClientTypes = {
  McpClientTypeUnspecified: "MCP_CLIENT_TYPE_UNSPECIFIED",
  McpClientTypePersonal: "MCP_CLIENT_TYPE_PERSONAL",
  McpClientTypeShared: "MCP_CLIENT_TYPE_SHARED",
  McpClientTypeService: "MCP_CLIENT_TYPE_SERVICE",
  McpClientTypeEphemeral: "MCP_CLIENT_TYPE_EPHEMERAL",
} as const;
export type AllowedClientTypes = OpenEnum<typeof AllowedClientTypes>;

/**
 * Tool risk classification for policy decisions.
 */
export const Classification = {
  ToolClassificationUnspecified: "TOOL_CLASSIFICATION_UNSPECIFIED",
  ToolClassificationRead: "TOOL_CLASSIFICATION_READ",
  ToolClassificationWrite: "TOOL_CLASSIFICATION_WRITE",
  ToolClassificationDestructive: "TOOL_CLASSIFICATION_DESTRUCTIVE",
  ToolClassificationSensitive: "TOOL_CLASSIFICATION_SENSITIVE",
  ToolClassificationDangerous: "TOOL_CLASSIFICATION_DANGEROUS",
} as const;
/**
 * Tool risk classification for policy decisions.
 */
export type Classification = OpenEnum<typeof Classification>;

/**
 * Default tool classification from MCP config (system-managed during discovery).
 */
export const DefaultClassification = {
  ToolClassificationUnspecified: "TOOL_CLASSIFICATION_UNSPECIFIED",
  ToolClassificationRead: "TOOL_CLASSIFICATION_READ",
  ToolClassificationWrite: "TOOL_CLASSIFICATION_WRITE",
  ToolClassificationDestructive: "TOOL_CLASSIFICATION_DESTRUCTIVE",
  ToolClassificationSensitive: "TOOL_CLASSIFICATION_SENSITIVE",
  ToolClassificationDangerous: "TOOL_CLASSIFICATION_DANGEROUS",
} as const;
/**
 * Default tool classification from MCP config (system-managed during discovery).
 */
export type DefaultClassification = OpenEnum<typeof DefaultClassification>;

/**
 * System-managed default visibility from MCP config (set during discovery).
 */
export const DefaultVisibility = {
  ToolVisibilityUnspecified: "TOOL_VISIBILITY_UNSPECIFIED",
  ToolVisibilityFeatured: "TOOL_VISIBILITY_FEATURED",
  ToolVisibilityAvailable: "TOOL_VISIBILITY_AVAILABLE",
  ToolVisibilityBypassed: "TOOL_VISIBILITY_BYPASSED",
} as const;
/**
 * System-managed default visibility from MCP config (set during discovery).
 */
export type DefaultVisibility = OpenEnum<typeof DefaultVisibility>;

/**
 * Tool approval/lifecycle state.
 */
export const MCPToolState = {
  McpToolStateUnspecified: "MCP_TOOL_STATE_UNSPECIFIED",
  McpToolStatePendingReview: "MCP_TOOL_STATE_PENDING_REVIEW",
  McpToolStateApproved: "MCP_TOOL_STATE_APPROVED",
  McpToolStateDisabled: "MCP_TOOL_STATE_DISABLED",
  McpToolStateRemoved: "MCP_TOOL_STATE_REMOVED",
} as const;
/**
 * Tool approval/lifecycle state.
 */
export type MCPToolState = OpenEnum<typeof MCPToolState>;

/**
 * Admin-settable visibility override (how this tool is surfaced to users).
 */
export const Visibility = {
  ToolVisibilityUnspecified: "TOOL_VISIBILITY_UNSPECIFIED",
  ToolVisibilityFeatured: "TOOL_VISIBILITY_FEATURED",
  ToolVisibilityAvailable: "TOOL_VISIBILITY_AVAILABLE",
  ToolVisibilityBypassed: "TOOL_VISIBILITY_BYPASSED",
} as const;
/**
 * Admin-settable visibility override (how this tool is surfaced to users).
 */
export type Visibility = OpenEnum<typeof Visibility>;

/**
 * MCPTool represents metadata about individual tools discovered from an MCP server.
 */
export type MCPTool = {
  /**
   * Which client types may use this tool.
   *
   * @remarks
   *  Empty = all allowed types from tenant config.
   */
  allowedClientTypes?: Array<AllowedClientTypes> | null | undefined;
  /**
   * Bound AppEntitlement created during sync.
   */
  appEntitlementId?: string | null | undefined;
  /**
   * App identifier (app that owns the connector).
   */
  appId?: string | null | undefined;
  /**
   * Tool risk classification for policy decisions.
   */
  classification?: Classification | null | undefined;
  /**
   * Connector identifier.
   */
  connectorId?: string | null | undefined;
  createdAt?: Date | null | undefined;
  /**
   * Default tool classification from MCP config (system-managed during discovery).
   */
  defaultClassification?: DefaultClassification | null | undefined;
  /**
   * Default display name from MCP tool spec (title field).
   */
  defaultDisplayName?: string | null | undefined;
  /**
   * System-managed default visibility from MCP config (set during discovery).
   */
  defaultVisibility?: DefaultVisibility | null | undefined;
  deletedAt?: Date | null | undefined;
  /**
   * Admin-editable description.
   */
  description?: string | null | undefined;
  /**
   * Hash of tool definition for change detection.
   */
  discoveryHash?: string | null | undefined;
  /**
   * Admin-editable display name (overrides default_display_name when set).
   */
  displayName?: string | null | undefined;
  /**
   * Unique identifier for this MCP tool record.
   */
  id?: string | null | undefined;
  /**
   * JSON-encoded input schema from MCP discovery.
   */
  inputSchemaJson?: string | null | undefined;
  lastCalledAt?: Date | null | undefined;
  /**
   * Tool approval/lifecycle state.
   */
  state?: MCPToolState | null | undefined;
  /**
   * Native MCP tool name (unique within an MCP server).
   */
  toolName?: string | null | undefined;
  updatedAt?: Date | null | undefined;
  /**
   * Admin-settable visibility override (how this tool is surfaced to users).
   */
  visibility?: Visibility | null | undefined;
};

/**
 * MCPTool represents metadata about individual tools discovered from an MCP server.
 */
export type MCPToolInput = {
  /**
   * Which client types may use this tool.
   *
   * @remarks
   *  Empty = all allowed types from tenant config.
   */
  allowedClientTypes?: Array<AllowedClientTypes> | null | undefined;
  /**
   * Bound AppEntitlement created during sync.
   */
  appEntitlementId?: string | null | undefined;
  /**
   * App identifier (app that owns the connector).
   */
  appId?: string | null | undefined;
  /**
   * Tool risk classification for policy decisions.
   */
  classification?: Classification | null | undefined;
  /**
   * Connector identifier.
   */
  connectorId?: string | null | undefined;
  createdAt?: Date | null | undefined;
  /**
   * Default tool classification from MCP config (system-managed during discovery).
   */
  defaultClassification?: DefaultClassification | null | undefined;
  /**
   * Default display name from MCP tool spec (title field).
   */
  defaultDisplayName?: string | null | undefined;
  /**
   * System-managed default visibility from MCP config (set during discovery).
   */
  defaultVisibility?: DefaultVisibility | null | undefined;
  deletedAt?: Date | null | undefined;
  /**
   * Admin-editable description.
   */
  description?: string | null | undefined;
  /**
   * Hash of tool definition for change detection.
   */
  discoveryHash?: string | null | undefined;
  /**
   * Admin-editable display name (overrides default_display_name when set).
   */
  displayName?: string | null | undefined;
  /**
   * Unique identifier for this MCP tool record.
   */
  id?: string | null | undefined;
  /**
   * JSON-encoded input schema from MCP discovery.
   */
  inputSchemaJson?: string | null | undefined;
  /**
   * Tool approval/lifecycle state.
   */
  state?: MCPToolState | null | undefined;
  /**
   * Native MCP tool name (unique within an MCP server).
   */
  toolName?: string | null | undefined;
  updatedAt?: Date | null | undefined;
  /**
   * Admin-settable visibility override (how this tool is surfaced to users).
   */
  visibility?: Visibility | null | undefined;
};

/** @internal */
export const AllowedClientTypes$inboundSchema: z.ZodType<
  AllowedClientTypes,
  z.ZodTypeDef,
  unknown
> = openEnums.inboundSchema(AllowedClientTypes);
/** @internal */
export const AllowedClientTypes$outboundSchema: z.ZodType<
  string,
  z.ZodTypeDef,
  AllowedClientTypes
> = openEnums.outboundSchema(AllowedClientTypes);

/** @internal */
export const Classification$inboundSchema: z.ZodType<
  Classification,
  z.ZodTypeDef,
  unknown
> = openEnums.inboundSchema(Classification);
/** @internal */
export const Classification$outboundSchema: z.ZodType<
  string,
  z.ZodTypeDef,
  Classification
> = openEnums.outboundSchema(Classification);

/** @internal */
export const DefaultClassification$inboundSchema: z.ZodType<
  DefaultClassification,
  z.ZodTypeDef,
  unknown
> = openEnums.inboundSchema(DefaultClassification);
/** @internal */
export const DefaultClassification$outboundSchema: z.ZodType<
  string,
  z.ZodTypeDef,
  DefaultClassification
> = openEnums.outboundSchema(DefaultClassification);

/** @internal */
export const DefaultVisibility$inboundSchema: z.ZodType<
  DefaultVisibility,
  z.ZodTypeDef,
  unknown
> = openEnums.inboundSchema(DefaultVisibility);
/** @internal */
export const DefaultVisibility$outboundSchema: z.ZodType<
  string,
  z.ZodTypeDef,
  DefaultVisibility
> = openEnums.outboundSchema(DefaultVisibility);

/** @internal */
export const MCPToolState$inboundSchema: z.ZodType<
  MCPToolState,
  z.ZodTypeDef,
  unknown
> = openEnums.inboundSchema(MCPToolState);
/** @internal */
export const MCPToolState$outboundSchema: z.ZodType<
  string,
  z.ZodTypeDef,
  MCPToolState
> = openEnums.outboundSchema(MCPToolState);

/** @internal */
export const Visibility$inboundSchema: z.ZodType<
  Visibility,
  z.ZodTypeDef,
  unknown
> = openEnums.inboundSchema(Visibility);
/** @internal */
export const Visibility$outboundSchema: z.ZodType<
  string,
  z.ZodTypeDef,
  Visibility
> = openEnums.outboundSchema(Visibility);

/** @internal */
export const MCPTool$inboundSchema: z.ZodType<MCPTool, z.ZodTypeDef, unknown> =
  z.object({
    allowedClientTypes: z.nullable(z.array(AllowedClientTypes$inboundSchema))
      .optional(),
    appEntitlementId: z.nullable(z.string()).optional(),
    appId: z.nullable(z.string()).optional(),
    classification: z.nullable(Classification$inboundSchema).optional(),
    connectorId: z.nullable(z.string()).optional(),
    createdAt: z.nullable(
      z.string().datetime({ offset: true }).transform(v => new Date(v)),
    ).optional(),
    defaultClassification: z.nullable(DefaultClassification$inboundSchema)
      .optional(),
    defaultDisplayName: z.nullable(z.string()).optional(),
    defaultVisibility: z.nullable(DefaultVisibility$inboundSchema).optional(),
    deletedAt: z.nullable(
      z.string().datetime({ offset: true }).transform(v => new Date(v)),
    ).optional(),
    description: z.nullable(z.string()).optional(),
    discoveryHash: z.nullable(z.string()).optional(),
    displayName: z.nullable(z.string()).optional(),
    id: z.nullable(z.string()).optional(),
    inputSchemaJson: z.nullable(z.string()).optional(),
    lastCalledAt: z.nullable(
      z.string().datetime({ offset: true }).transform(v => new Date(v)),
    ).optional(),
    state: z.nullable(MCPToolState$inboundSchema).optional(),
    toolName: z.nullable(z.string()).optional(),
    updatedAt: z.nullable(
      z.string().datetime({ offset: true }).transform(v => new Date(v)),
    ).optional(),
    visibility: z.nullable(Visibility$inboundSchema).optional(),
  });

export function mcpToolFromJSON(
  jsonString: string,
): SafeParseResult<MCPTool, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MCPTool$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MCPTool' from JSON`,
  );
}

/** @internal */
export type MCPToolInput$Outbound = {
  allowedClientTypes?: Array<string> | null | undefined;
  appEntitlementId?: string | null | undefined;
  appId?: string | null | undefined;
  classification?: string | null | undefined;
  connectorId?: string | null | undefined;
  createdAt?: string | null | undefined;
  defaultClassification?: string | null | undefined;
  defaultDisplayName?: string | null | undefined;
  defaultVisibility?: string | null | undefined;
  deletedAt?: string | null | undefined;
  description?: string | null | undefined;
  discoveryHash?: string | null | undefined;
  displayName?: string | null | undefined;
  id?: string | null | undefined;
  inputSchemaJson?: string | null | undefined;
  state?: string | null | undefined;
  toolName?: string | null | undefined;
  updatedAt?: string | null | undefined;
  visibility?: string | null | undefined;
};

/** @internal */
export const MCPToolInput$outboundSchema: z.ZodType<
  MCPToolInput$Outbound,
  z.ZodTypeDef,
  MCPToolInput
> = z.object({
  allowedClientTypes: z.nullable(z.array(AllowedClientTypes$outboundSchema))
    .optional(),
  appEntitlementId: z.nullable(z.string()).optional(),
  appId: z.nullable(z.string()).optional(),
  classification: z.nullable(Classification$outboundSchema).optional(),
  connectorId: z.nullable(z.string()).optional(),
  createdAt: z.nullable(z.date().transform(v => v.toISOString())).optional(),
  defaultClassification: z.nullable(DefaultClassification$outboundSchema)
    .optional(),
  defaultDisplayName: z.nullable(z.string()).optional(),
  defaultVisibility: z.nullable(DefaultVisibility$outboundSchema).optional(),
  deletedAt: z.nullable(z.date().transform(v => v.toISOString())).optional(),
  description: z.nullable(z.string()).optional(),
  discoveryHash: z.nullable(z.string()).optional(),
  displayName: z.nullable(z.string()).optional(),
  id: z.nullable(z.string()).optional(),
  inputSchemaJson: z.nullable(z.string()).optional(),
  state: z.nullable(MCPToolState$outboundSchema).optional(),
  toolName: z.nullable(z.string()).optional(),
  updatedAt: z.nullable(z.date().transform(v => v.toISOString())).optional(),
  visibility: z.nullable(Visibility$outboundSchema).optional(),
});

export function mcpToolInputToJSON(mcpToolInput: MCPToolInput): string {
  return JSON.stringify(MCPToolInput$outboundSchema.parse(mcpToolInput));
}
