/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * The frequency field.
 */
export const Frequency = {
  FrequencyUnspecified: "FREQUENCY_UNSPECIFIED",
  FrequencyNone: "FREQUENCY_NONE",
  FrequencyDaily: "FREQUENCY_DAILY",
  FrequencyWeekly: "FREQUENCY_WEEKLY",
  FrequencyMonthly: "FREQUENCY_MONTHLY",
  FrequencyYearly: "FREQUENCY_YEARLY",
} as const;
/**
 * The frequency field.
 */
export type Frequency = OpenEnum<typeof Frequency>;

/**
 * The RecurrenceRule message.
 *
 * @remarks
 *
 * This message contains a oneof named end_condition. Only a single field of the following list may be set at a time:
 *   - endDate
 *   - occurrences
 */
export type RecurrenceRule = {
  endDate?: Date | undefined;
  /**
   * The frequency field.
   */
  frequency?: Frequency | undefined;
  /**
   * The interval field.
   */
  interval?: number | undefined;
  /**
   * The occurrences field.
   *
   * @remarks
   * This field is part of the `end_condition` oneof.
   * See the documentation for `c1.api.accessreview.v1.RecurrenceRule` for more details.
   */
  occurrences?: number | null | undefined;
  startDate?: Date | undefined;
};

/** @internal */
export const Frequency$inboundSchema: z.ZodType<
  Frequency,
  z.ZodTypeDef,
  unknown
> = openEnums.inboundSchema(Frequency);
/** @internal */
export const Frequency$outboundSchema: z.ZodType<
  string,
  z.ZodTypeDef,
  Frequency
> = openEnums.outboundSchema(Frequency);

/** @internal */
export const RecurrenceRule$inboundSchema: z.ZodType<
  RecurrenceRule,
  z.ZodTypeDef,
  unknown
> = z.object({
  endDate: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  frequency: Frequency$inboundSchema.optional(),
  interval: z.number().int().optional(),
  occurrences: z.nullable(z.number().int()).optional(),
  startDate: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
});
/** @internal */
export type RecurrenceRule$Outbound = {
  endDate?: string | undefined;
  frequency?: string | undefined;
  interval?: number | undefined;
  occurrences?: number | null | undefined;
  startDate?: string | undefined;
};

/** @internal */
export const RecurrenceRule$outboundSchema: z.ZodType<
  RecurrenceRule$Outbound,
  z.ZodTypeDef,
  RecurrenceRule
> = z.object({
  endDate: z.date().transform(v => v.toISOString()).optional(),
  frequency: Frequency$outboundSchema.optional(),
  interval: z.number().int().optional(),
  occurrences: z.nullable(z.number().int()).optional(),
  startDate: z.date().transform(v => v.toISOString()).optional(),
});

export function recurrenceRuleToJSON(recurrenceRule: RecurrenceRule): string {
  return JSON.stringify(RecurrenceRule$outboundSchema.parse(recurrenceRule));
}
export function recurrenceRuleFromJSON(
  jsonString: string,
): SafeParseResult<RecurrenceRule, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RecurrenceRule$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RecurrenceRule' from JSON`,
  );
}
