/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

/**
 * The RemoveGrantDurationRequest message.
 */
export type RemoveGrantDurationRequest = {};

/** @internal */
export type RemoveGrantDurationRequest$Outbound = {};

/** @internal */
export const RemoveGrantDurationRequest$outboundSchema: z.ZodType<
  RemoveGrantDurationRequest$Outbound,
  z.ZodTypeDef,
  RemoveGrantDurationRequest
> = z.object({});

export function removeGrantDurationRequestToJSON(
  removeGrantDurationRequest: RemoveGrantDurationRequest,
): string {
  return JSON.stringify(
    RemoveGrantDurationRequest$outboundSchema.parse(removeGrantDurationRequest),
  );
}
