/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import {
  AppEntitlementRef,
  AppEntitlementRef$Outbound,
  AppEntitlementRef$outboundSchema,
} from "./appentitlementref.js";

/**
 * The RequestCatalogManagementServiceUpdateAppEntitlementsRequest object is used to update app entitlements to a request catalog id.
 */
export type RequestCatalogManagementServiceUpdateAppEntitlementsRequest = {
  /**
   * The entitlement to get from the request catalog.
   */
  appEntitlements: Array<AppEntitlementRef> | null;
};

/** @internal */
export type RequestCatalogManagementServiceUpdateAppEntitlementsRequest$Outbound =
  {
    appEntitlements: Array<AppEntitlementRef$Outbound> | null;
  };

/** @internal */
export const RequestCatalogManagementServiceUpdateAppEntitlementsRequest$outboundSchema:
  z.ZodType<
    RequestCatalogManagementServiceUpdateAppEntitlementsRequest$Outbound,
    z.ZodTypeDef,
    RequestCatalogManagementServiceUpdateAppEntitlementsRequest
  > = z.object({
    appEntitlements: z.nullable(z.array(AppEntitlementRef$outboundSchema)),
  });

export function requestCatalogManagementServiceUpdateAppEntitlementsRequestToJSON(
  requestCatalogManagementServiceUpdateAppEntitlementsRequest:
    RequestCatalogManagementServiceUpdateAppEntitlementsRequest,
): string {
  return JSON.stringify(
    RequestCatalogManagementServiceUpdateAppEntitlementsRequest$outboundSchema
      .parse(requestCatalogManagementServiceUpdateAppEntitlementsRequest),
  );
}
