/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { safeParse } from "../../../lib/schemas.js";
import { catchUnrecognizedEnum, } from "../../types/enums.js";
import { RequestCatalogExpandMask$inboundSchema, RequestCatalogExpandMask$outboundSchema, } from "./requestcatalogexpandmask.js";
/**
 * Defines how to handle the request policies of the entitlements in the catalog during enrollment.
 */
export const RequestCatalogManagementServiceCreateRequestEnrollmentBehavior = {
    RequestCatalogEnrollmentBehaviorUnspecified: "REQUEST_CATALOG_ENROLLMENT_BEHAVIOR_UNSPECIFIED",
    RequestCatalogEnrollmentBehaviorBypassEntitlementRequestPolicy: "REQUEST_CATALOG_ENROLLMENT_BEHAVIOR_BYPASS_ENTITLEMENT_REQUEST_POLICY",
    RequestCatalogEnrollmentBehaviorEnforceEntitlementRequestPolicy: "REQUEST_CATALOG_ENROLLMENT_BEHAVIOR_ENFORCE_ENTITLEMENT_REQUEST_POLICY",
};
/**
 * Defines how to handle the revocation of the entitlements in the catalog during unenrollment.
 */
export const RequestCatalogManagementServiceCreateRequestUnenrollmentBehavior = {
    RequestCatalogUnenrollmentBehaviorUnspecified: "REQUEST_CATALOG_UNENROLLMENT_BEHAVIOR_UNSPECIFIED",
    RequestCatalogUnenrollmentBehaviorLeaveAccessAsIs: "REQUEST_CATALOG_UNENROLLMENT_BEHAVIOR_LEAVE_ACCESS_AS_IS",
    RequestCatalogUnenrollmentBehaviorRevokeAll: "REQUEST_CATALOG_UNENROLLMENT_BEHAVIOR_REVOKE_ALL",
    RequestCatalogUnenrollmentBehaviorRevokeUnjustified: "REQUEST_CATALOG_UNENROLLMENT_BEHAVIOR_REVOKE_UNJUSTIFIED",
};
/**
 * Defines how to handle the revoke policies of the entitlements in the catalog during unenrollment.
 */
export const RequestCatalogManagementServiceCreateRequestUnenrollmentEntitlementBehavior = {
    RequestCatalogUnenrollmentEntitlementBehaviorUnspecified: "REQUEST_CATALOG_UNENROLLMENT_ENTITLEMENT_BEHAVIOR_UNSPECIFIED",
    RequestCatalogUnenrollmentEntitlementBehaviorBypass: "REQUEST_CATALOG_UNENROLLMENT_ENTITLEMENT_BEHAVIOR_BYPASS",
    RequestCatalogUnenrollmentEntitlementBehaviorEnforce: "REQUEST_CATALOG_UNENROLLMENT_ENTITLEMENT_BEHAVIOR_ENFORCE",
};
/** @internal */
export const RequestCatalogManagementServiceCreateRequestEnrollmentBehavior$inboundSchema = z
    .union([
    z.nativeEnum(RequestCatalogManagementServiceCreateRequestEnrollmentBehavior),
    z.string().transform(catchUnrecognizedEnum),
]);
/** @internal */
export const RequestCatalogManagementServiceCreateRequestEnrollmentBehavior$outboundSchema = z.union([
    z.nativeEnum(RequestCatalogManagementServiceCreateRequestEnrollmentBehavior),
    z.string().and(z.custom()),
]);
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export var RequestCatalogManagementServiceCreateRequestEnrollmentBehavior$;
(function (RequestCatalogManagementServiceCreateRequestEnrollmentBehavior$) {
    /** @deprecated use `RequestCatalogManagementServiceCreateRequestEnrollmentBehavior$inboundSchema` instead. */
    RequestCatalogManagementServiceCreateRequestEnrollmentBehavior$.inboundSchema = RequestCatalogManagementServiceCreateRequestEnrollmentBehavior$inboundSchema;
    /** @deprecated use `RequestCatalogManagementServiceCreateRequestEnrollmentBehavior$outboundSchema` instead. */
    RequestCatalogManagementServiceCreateRequestEnrollmentBehavior$.outboundSchema = RequestCatalogManagementServiceCreateRequestEnrollmentBehavior$outboundSchema;
})(RequestCatalogManagementServiceCreateRequestEnrollmentBehavior$ || (RequestCatalogManagementServiceCreateRequestEnrollmentBehavior$ = {}));
/** @internal */
export const RequestCatalogManagementServiceCreateRequestUnenrollmentBehavior$inboundSchema = z
    .union([
    z.nativeEnum(RequestCatalogManagementServiceCreateRequestUnenrollmentBehavior),
    z.string().transform(catchUnrecognizedEnum),
]);
/** @internal */
export const RequestCatalogManagementServiceCreateRequestUnenrollmentBehavior$outboundSchema = z.union([
    z.nativeEnum(RequestCatalogManagementServiceCreateRequestUnenrollmentBehavior),
    z.string().and(z.custom()),
]);
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export var RequestCatalogManagementServiceCreateRequestUnenrollmentBehavior$;
(function (RequestCatalogManagementServiceCreateRequestUnenrollmentBehavior$) {
    /** @deprecated use `RequestCatalogManagementServiceCreateRequestUnenrollmentBehavior$inboundSchema` instead. */
    RequestCatalogManagementServiceCreateRequestUnenrollmentBehavior$.inboundSchema = RequestCatalogManagementServiceCreateRequestUnenrollmentBehavior$inboundSchema;
    /** @deprecated use `RequestCatalogManagementServiceCreateRequestUnenrollmentBehavior$outboundSchema` instead. */
    RequestCatalogManagementServiceCreateRequestUnenrollmentBehavior$.outboundSchema = RequestCatalogManagementServiceCreateRequestUnenrollmentBehavior$outboundSchema;
})(RequestCatalogManagementServiceCreateRequestUnenrollmentBehavior$ || (RequestCatalogManagementServiceCreateRequestUnenrollmentBehavior$ = {}));
/** @internal */
export const RequestCatalogManagementServiceCreateRequestUnenrollmentEntitlementBehavior$inboundSchema = z
    .union([
    z.nativeEnum(RequestCatalogManagementServiceCreateRequestUnenrollmentEntitlementBehavior),
    z.string().transform(catchUnrecognizedEnum),
]);
/** @internal */
export const RequestCatalogManagementServiceCreateRequestUnenrollmentEntitlementBehavior$outboundSchema = z.union([
    z.nativeEnum(RequestCatalogManagementServiceCreateRequestUnenrollmentEntitlementBehavior),
    z.string().and(z.custom()),
]);
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export var RequestCatalogManagementServiceCreateRequestUnenrollmentEntitlementBehavior$;
(function (RequestCatalogManagementServiceCreateRequestUnenrollmentEntitlementBehavior$) {
    /** @deprecated use `RequestCatalogManagementServiceCreateRequestUnenrollmentEntitlementBehavior$inboundSchema` instead. */
    RequestCatalogManagementServiceCreateRequestUnenrollmentEntitlementBehavior$.inboundSchema = RequestCatalogManagementServiceCreateRequestUnenrollmentEntitlementBehavior$inboundSchema;
    /** @deprecated use `RequestCatalogManagementServiceCreateRequestUnenrollmentEntitlementBehavior$outboundSchema` instead. */
    RequestCatalogManagementServiceCreateRequestUnenrollmentEntitlementBehavior$.outboundSchema = RequestCatalogManagementServiceCreateRequestUnenrollmentEntitlementBehavior$outboundSchema;
})(RequestCatalogManagementServiceCreateRequestUnenrollmentEntitlementBehavior$ || (RequestCatalogManagementServiceCreateRequestUnenrollmentEntitlementBehavior$ = {}));
/** @internal */
export const RequestCatalogManagementServiceCreateRequest$inboundSchema = z.object({
    description: z.nullable(z.string()).optional(),
    displayName: z.string(),
    enrollmentBehavior: z.nullable(RequestCatalogManagementServiceCreateRequestEnrollmentBehavior$inboundSchema).optional(),
    expandMask: z.nullable(RequestCatalogExpandMask$inboundSchema).optional(),
    published: z.nullable(z.boolean()).optional(),
    requestBundle: z.nullable(z.boolean()).optional(),
    unenrollmentBehavior: z.nullable(RequestCatalogManagementServiceCreateRequestUnenrollmentBehavior$inboundSchema).optional(),
    unenrollmentEntitlementBehavior: z.nullable(RequestCatalogManagementServiceCreateRequestUnenrollmentEntitlementBehavior$inboundSchema).optional(),
    visibleToEveryone: z.nullable(z.boolean()).optional(),
});
/** @internal */
export const RequestCatalogManagementServiceCreateRequest$outboundSchema = z.object({
    description: z.nullable(z.string()).optional(),
    displayName: z.string(),
    enrollmentBehavior: z.nullable(RequestCatalogManagementServiceCreateRequestEnrollmentBehavior$outboundSchema).optional(),
    expandMask: z.nullable(RequestCatalogExpandMask$outboundSchema).optional(),
    published: z.nullable(z.boolean()).optional(),
    requestBundle: z.nullable(z.boolean()).optional(),
    unenrollmentBehavior: z.nullable(RequestCatalogManagementServiceCreateRequestUnenrollmentBehavior$outboundSchema).optional(),
    unenrollmentEntitlementBehavior: z.nullable(RequestCatalogManagementServiceCreateRequestUnenrollmentEntitlementBehavior$outboundSchema).optional(),
    visibleToEveryone: z.nullable(z.boolean()).optional(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export var RequestCatalogManagementServiceCreateRequest$;
(function (RequestCatalogManagementServiceCreateRequest$) {
    /** @deprecated use `RequestCatalogManagementServiceCreateRequest$inboundSchema` instead. */
    RequestCatalogManagementServiceCreateRequest$.inboundSchema = RequestCatalogManagementServiceCreateRequest$inboundSchema;
    /** @deprecated use `RequestCatalogManagementServiceCreateRequest$outboundSchema` instead. */
    RequestCatalogManagementServiceCreateRequest$.outboundSchema = RequestCatalogManagementServiceCreateRequest$outboundSchema;
})(RequestCatalogManagementServiceCreateRequest$ || (RequestCatalogManagementServiceCreateRequest$ = {}));
export function requestCatalogManagementServiceCreateRequestToJSON(requestCatalogManagementServiceCreateRequest) {
    return JSON.stringify(RequestCatalogManagementServiceCreateRequest$outboundSchema.parse(requestCatalogManagementServiceCreateRequest));
}
export function requestCatalogManagementServiceCreateRequestFromJSON(jsonString) {
    return safeParse(jsonString, (x) => RequestCatalogManagementServiceCreateRequest$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'RequestCatalogManagementServiceCreateRequest' from JSON`);
}
