/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  RequestableEntry,
  RequestableEntry$inboundSchema,
} from "./requestableentry.js";

/**
 * Response containing the requested entry
 */
export type RequestCatalogManagementServiceGetRequestableEntryResponse = {
  /**
   * A requestable entry in a catalog
   */
  requestableEntry?: RequestableEntry | undefined;
};

/** @internal */
export const RequestCatalogManagementServiceGetRequestableEntryResponse$inboundSchema:
  z.ZodType<
    RequestCatalogManagementServiceGetRequestableEntryResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    requestableEntry: RequestableEntry$inboundSchema.optional(),
  });

export function requestCatalogManagementServiceGetRequestableEntryResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  RequestCatalogManagementServiceGetRequestableEntryResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      RequestCatalogManagementServiceGetRequestableEntryResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'RequestCatalogManagementServiceGetRequestableEntryResponse' from JSON`,
  );
}
