/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * The ReviewsPreference message.
 */
export type ReviewsPreference = {
  /**
   * The enabled field.
   */
  enabled?: boolean | undefined;
};

/** @internal */
export const ReviewsPreference$inboundSchema: z.ZodType<
  ReviewsPreference,
  z.ZodTypeDef,
  unknown
> = z.object({
  enabled: z.boolean().optional(),
});
/** @internal */
export type ReviewsPreference$Outbound = {
  enabled?: boolean | undefined;
};

/** @internal */
export const ReviewsPreference$outboundSchema: z.ZodType<
  ReviewsPreference$Outbound,
  z.ZodTypeDef,
  ReviewsPreference
> = z.object({
  enabled: z.boolean().optional(),
});

export function reviewsPreferenceToJSON(
  reviewsPreference: ReviewsPreference,
): string {
  return JSON.stringify(
    ReviewsPreference$outboundSchema.parse(reviewsPreference),
  );
}
export function reviewsPreferenceFromJSON(
  jsonString: string,
): SafeParseResult<ReviewsPreference, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ReviewsPreference$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ReviewsPreference' from JSON`,
  );
}
