/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Current execution status of this run (e.g., running, completed, failed).
 */
export const RoleMiningManagementRunStatus = {
  RunStatusUnspecified: "RUN_STATUS_UNSPECIFIED",
  RunStatusRunning: "RUN_STATUS_RUNNING",
  RunStatusCompleted: "RUN_STATUS_COMPLETED",
  RunStatusFailed: "RUN_STATUS_FAILED",
} as const;
/**
 * Current execution status of this run (e.g., running, completed, failed).
 */
export type RoleMiningManagementRunStatus = OpenEnum<
  typeof RoleMiningManagementRunStatus
>;

/**
 * How this run was initiated (e.g., manual, scheduled).
 */
export const TriggerType = {
  TriggerTypeUnspecified: "TRIGGER_TYPE_UNSPECIFIED",
  TriggerTypeManual: "TRIGGER_TYPE_MANUAL",
  TriggerTypeUpliftCompletion: "TRIGGER_TYPE_UPLIFT_COMPLETION",
  TriggerTypeScheduled: "TRIGGER_TYPE_SCHEDULED",
  TriggerTypeDirectoryMerge: "TRIGGER_TYPE_DIRECTORY_MERGE",
} as const;
/**
 * How this run was initiated (e.g., manual, scheduled).
 */
export type TriggerType = OpenEnum<typeof TriggerType>;

/**
 * The RoleMiningManagementRun message.
 */
export type RoleMiningManagementRun = {
  /**
   * Number of user cohorts evaluated during the analysis.
   */
  cohortsAnalyzed?: number | null | undefined;
  completedAt?: Date | null | undefined;
  createdAt?: Date | null | undefined;
  /**
   * Error message if the run failed, empty on success.
   */
  errorMessage?: string | null | undefined;
  /**
   * Unique identifier for this analysis run.
   */
  id?: string | null | undefined;
  /**
   * Current execution status of this run (e.g., running, completed, failed).
   */
  status?: RoleMiningManagementRunStatus | null | undefined;
  /**
   * Number of role suggestions produced by this run.
   */
  suggestionsGenerated?: number | null | undefined;
  /**
   * Total number of users evaluated during the analysis.
   */
  totalUsers?: number | null | undefined;
  /**
   * Additional detail about the trigger, such as the user or schedule that initiated the run.
   */
  triggerDetail?: string | null | undefined;
  /**
   * How this run was initiated (e.g., manual, scheduled).
   */
  triggerType?: TriggerType | null | undefined;
  updatedAt?: Date | null | undefined;
};

/** @internal */
export const RoleMiningManagementRunStatus$inboundSchema: z.ZodType<
  RoleMiningManagementRunStatus,
  z.ZodTypeDef,
  unknown
> = openEnums.inboundSchema(RoleMiningManagementRunStatus);

/** @internal */
export const TriggerType$inboundSchema: z.ZodType<
  TriggerType,
  z.ZodTypeDef,
  unknown
> = openEnums.inboundSchema(TriggerType);

/** @internal */
export const RoleMiningManagementRun$inboundSchema: z.ZodType<
  RoleMiningManagementRun,
  z.ZodTypeDef,
  unknown
> = z.object({
  cohortsAnalyzed: z.nullable(z.number().int()).optional(),
  completedAt: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
  createdAt: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
  errorMessage: z.nullable(z.string()).optional(),
  id: z.nullable(z.string()).optional(),
  status: z.nullable(RoleMiningManagementRunStatus$inboundSchema).optional(),
  suggestionsGenerated: z.nullable(z.number().int()).optional(),
  totalUsers: z.nullable(z.number().int()).optional(),
  triggerDetail: z.nullable(z.string()).optional(),
  triggerType: z.nullable(TriggerType$inboundSchema).optional(),
  updatedAt: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
});

export function roleMiningManagementRunFromJSON(
  jsonString: string,
): SafeParseResult<RoleMiningManagementRun, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RoleMiningManagementRun$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RoleMiningManagementRun' from JSON`,
  );
}
