/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * The SaveToVault message.
 */
export type SaveToVault = {
  /**
   * The vaultIds field.
   */
  vaultIds?: Array<string> | null | undefined;
};

/** @internal */
export const SaveToVault$inboundSchema: z.ZodType<
  SaveToVault,
  z.ZodTypeDef,
  unknown
> = z.object({
  vaultIds: z.nullable(z.array(z.string())).optional(),
});
/** @internal */
export type SaveToVault$Outbound = {
  vaultIds?: Array<string> | null | undefined;
};

/** @internal */
export const SaveToVault$outboundSchema: z.ZodType<
  SaveToVault$Outbound,
  z.ZodTypeDef,
  SaveToVault
> = z.object({
  vaultIds: z.nullable(z.array(z.string())).optional(),
});

export function saveToVaultToJSON(saveToVault: SaveToVault): string {
  return JSON.stringify(SaveToVault$outboundSchema.parse(saveToVault));
}
export function saveToVaultFromJSON(
  jsonString: string,
): SafeParseResult<SaveToVault, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SaveToVault$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SaveToVault' from JSON`,
  );
}
