/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

/**
 * Scope-role variant of TaskTypeAction.target_object. The UI uses the
 *
 * @remarks
 *  embedded identifiers to build links and title strings without a separate
 *  Action fetch.
 */
export type ScopeRoleInput = {};

/** @internal */
export type ScopeRoleInput$Outbound = {};

/** @internal */
export const ScopeRoleInput$outboundSchema: z.ZodType<
  ScopeRoleInput$Outbound,
  z.ZodTypeDef,
  ScopeRoleInput
> = z.object({});

export function scopeRoleInputToJSON(scopeRoleInput: ScopeRoleInput): string {
  return JSON.stringify(ScopeRoleInput$outboundSchema.parse(scopeRoleInput));
}
