/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  AttributeValue,
  AttributeValue$inboundSchema,
} from "./attributevalue.js";

/**
 * SearchAttributeValuesResponse is the response for searching AttributeValues.
 */
export type SearchAttributeValuesResponse = {
  /**
   * The list of returned AttributeValues.
   */
  list?: Array<AttributeValue> | null | undefined;
  /**
   * The nextPageToken is shown for the next page if the number of results is larger than the max page size.
   *
   * @remarks
   *  The server returns one page of results and the nextPageToken until all results are retreived.
   *  To retrieve the next page, use the same request and append a pageToken field with the value of nextPageToken shown on the previous page.
   */
  nextPageToken?: string | null | undefined;
};

/** @internal */
export const SearchAttributeValuesResponse$inboundSchema: z.ZodType<
  SearchAttributeValuesResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  list: z.nullable(z.array(AttributeValue$inboundSchema)).optional(),
  nextPageToken: z.nullable(z.string()).optional(),
});

export function searchAttributeValuesResponseFromJSON(
  jsonString: string,
): SafeParseResult<SearchAttributeValuesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SearchAttributeValuesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchAttributeValuesResponse' from JSON`,
  );
}
