/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * The SelectedUsersScope message.
 */
export type SelectedUsersScope = {
  /**
   * The userIds field.
   */
  userIds?: Array<string> | null | undefined;
};

/** @internal */
export const SelectedUsersScope$inboundSchema: z.ZodType<
  SelectedUsersScope,
  z.ZodTypeDef,
  unknown
> = z.object({
  userIds: z.nullable(z.array(z.string())).optional(),
});

/** @internal */
export type SelectedUsersScope$Outbound = {
  userIds?: Array<string> | null | undefined;
};

/** @internal */
export const SelectedUsersScope$outboundSchema: z.ZodType<
  SelectedUsersScope$Outbound,
  z.ZodTypeDef,
  SelectedUsersScope
> = z.object({
  userIds: z.nullable(z.array(z.string())).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SelectedUsersScope$ {
  /** @deprecated use `SelectedUsersScope$inboundSchema` instead. */
  export const inboundSchema = SelectedUsersScope$inboundSchema;
  /** @deprecated use `SelectedUsersScope$outboundSchema` instead. */
  export const outboundSchema = SelectedUsersScope$outboundSchema;
  /** @deprecated use `SelectedUsersScope$Outbound` instead. */
  export type Outbound = SelectedUsersScope$Outbound;
}

export function selectedUsersScopeToJSON(
  selectedUsersScope: SelectedUsersScope,
): string {
  return JSON.stringify(
    SelectedUsersScope$outboundSchema.parse(selectedUsersScope),
  );
}

export function selectedUsersScopeFromJSON(
  jsonString: string,
): SafeParseResult<SelectedUsersScope, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SelectedUsersScope$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SelectedUsersScope' from JSON`,
  );
}
