/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

/**
 * The ServicePrincipalServiceCreateRequest message.
 */
export type ServicePrincipalServiceCreateRequest = {
  /**
   * The display name for the new service principal.
   */
  displayName?: string | null | undefined;
};

/** @internal */
export type ServicePrincipalServiceCreateRequest$Outbound = {
  displayName?: string | null | undefined;
};

/** @internal */
export const ServicePrincipalServiceCreateRequest$outboundSchema: z.ZodType<
  ServicePrincipalServiceCreateRequest$Outbound,
  z.ZodTypeDef,
  ServicePrincipalServiceCreateRequest
> = z.object({
  displayName: z.nullable(z.string()).optional(),
});

export function servicePrincipalServiceCreateRequestToJSON(
  servicePrincipalServiceCreateRequest: ServicePrincipalServiceCreateRequest,
): string {
  return JSON.stringify(
    ServicePrincipalServiceCreateRequest$outboundSchema.parse(
      servicePrincipalServiceCreateRequest,
    ),
  );
}
