/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * What the account is currently classified as in ConductorOne.
 */
export const CurrentAccountType = {
  AppUserTypeUnspecified: "APP_USER_TYPE_UNSPECIFIED",
  AppUserTypeUser: "APP_USER_TYPE_USER",
  AppUserTypeServiceAccount: "APP_USER_TYPE_SERVICE_ACCOUNT",
  AppUserTypeSystemAccount: "APP_USER_TYPE_SYSTEM_ACCOUNT",
} as const;
/**
 * What the account is currently classified as in ConductorOne.
 */
export type CurrentAccountType = OpenEnum<typeof CurrentAccountType>;

/**
 * What the detector thinks the account actually is.
 */
export const DetectedAccountType = {
  AppUserTypeUnspecified: "APP_USER_TYPE_UNSPECIFIED",
  AppUserTypeUser: "APP_USER_TYPE_USER",
  AppUserTypeServiceAccount: "APP_USER_TYPE_SERVICE_ACCOUNT",
  AppUserTypeSystemAccount: "APP_USER_TYPE_SYSTEM_ACCOUNT",
} as const;
/**
 * What the detector thinks the account actually is.
 */
export type DetectedAccountType = OpenEnum<typeof DetectedAccountType>;

/**
 * ServiceAccountMisclassificationType: account classified as human but
 *
 * @remarks
 *  detected as service account, or vice versa.
 *  Target: AppUserTarget (the misclassified account).
 */
export type ServiceAccountMisclassificationType = {
  /**
   * What the account is currently classified as in ConductorOne.
   */
  currentAccountType?: CurrentAccountType | undefined;
  /**
   * What the detector thinks the account actually is.
   */
  detectedAccountType?: DetectedAccountType | undefined;
};

/** @internal */
export const CurrentAccountType$inboundSchema: z.ZodType<
  CurrentAccountType,
  z.ZodTypeDef,
  unknown
> = openEnums.inboundSchema(CurrentAccountType);

/** @internal */
export const DetectedAccountType$inboundSchema: z.ZodType<
  DetectedAccountType,
  z.ZodTypeDef,
  unknown
> = openEnums.inboundSchema(DetectedAccountType);

/** @internal */
export const ServiceAccountMisclassificationType$inboundSchema: z.ZodType<
  ServiceAccountMisclassificationType,
  z.ZodTypeDef,
  unknown
> = z.object({
  currentAccountType: CurrentAccountType$inboundSchema.optional(),
  detectedAccountType: DetectedAccountType$inboundSchema.optional(),
});

export function serviceAccountMisclassificationTypeFromJSON(
  jsonString: string,
): SafeParseResult<ServiceAccountMisclassificationType, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ServiceAccountMisclassificationType$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ServiceAccountMisclassificationType' from JSON`,
  );
}
