/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * The empty response message for setting the app entitlement owners.
 */
export type SetAppEntitlementOwnersResponse = {};

/** @internal */
export const SetAppEntitlementOwnersResponse$inboundSchema: z.ZodType<
  SetAppEntitlementOwnersResponse,
  z.ZodTypeDef,
  unknown
> = z.object({});

export function setAppEntitlementOwnersResponseFromJSON(
  jsonString: string,
): SafeParseResult<SetAppEntitlementOwnersResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SetAppEntitlementOwnersResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SetAppEntitlementOwnersResponse' from JSON`,
  );
}
