/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

/**
 * The accountDisabledAction field.
 */
export const SSFReceiverStreamServiceCreateRequestAccountDisabledAction = {
  SsfRevocationActionUnspecified: "SSF_REVOCATION_ACTION_UNSPECIFIED",
  SsfRevocationActionRevokeAll: "SSF_REVOCATION_ACTION_REVOKE_ALL",
  SsfRevocationActionLogOnly: "SSF_REVOCATION_ACTION_LOG_ONLY",
} as const;
/**
 * The accountDisabledAction field.
 */
export type SSFReceiverStreamServiceCreateRequestAccountDisabledAction =
  OpenEnum<typeof SSFReceiverStreamServiceCreateRequestAccountDisabledAction>;

/**
 * The credentialChangeAction field.
 */
export const SSFReceiverStreamServiceCreateRequestCredentialChangeAction = {
  SsfRevocationActionUnspecified: "SSF_REVOCATION_ACTION_UNSPECIFIED",
  SsfRevocationActionRevokeAll: "SSF_REVOCATION_ACTION_REVOKE_ALL",
  SsfRevocationActionLogOnly: "SSF_REVOCATION_ACTION_LOG_ONLY",
} as const;
/**
 * The credentialChangeAction field.
 */
export type SSFReceiverStreamServiceCreateRequestCredentialChangeAction =
  OpenEnum<typeof SSFReceiverStreamServiceCreateRequestCredentialChangeAction>;

/**
 * The credentialCompromiseAction field.
 */
export const SSFReceiverStreamServiceCreateRequestCredentialCompromiseAction = {
  SsfRevocationActionUnspecified: "SSF_REVOCATION_ACTION_UNSPECIFIED",
  SsfRevocationActionRevokeAll: "SSF_REVOCATION_ACTION_REVOKE_ALL",
  SsfRevocationActionLogOnly: "SSF_REVOCATION_ACTION_LOG_ONLY",
} as const;
/**
 * The credentialCompromiseAction field.
 */
export type SSFReceiverStreamServiceCreateRequestCredentialCompromiseAction =
  OpenEnum<
    typeof SSFReceiverStreamServiceCreateRequestCredentialCompromiseAction
  >;

/**
 * The deliveryMethod field.
 */
export const SSFReceiverStreamServiceCreateRequestDeliveryMethod = {
  SsfDeliveryMethodUnspecified: "SSF_DELIVERY_METHOD_UNSPECIFIED",
  SsfDeliveryMethodPush: "SSF_DELIVERY_METHOD_PUSH",
  SsfDeliveryMethodPoll: "SSF_DELIVERY_METHOD_POLL",
} as const;
/**
 * The deliveryMethod field.
 */
export type SSFReceiverStreamServiceCreateRequestDeliveryMethod = OpenEnum<
  typeof SSFReceiverStreamServiceCreateRequestDeliveryMethod
>;

/**
 * Per-event-type action configuration.
 */
export const SSFReceiverStreamServiceCreateRequestSessionRevokedAction = {
  SsfRevocationActionUnspecified: "SSF_REVOCATION_ACTION_UNSPECIFIED",
  SsfRevocationActionRevokeAll: "SSF_REVOCATION_ACTION_REVOKE_ALL",
  SsfRevocationActionLogOnly: "SSF_REVOCATION_ACTION_LOG_ONLY",
} as const;
/**
 * Per-event-type action configuration.
 */
export type SSFReceiverStreamServiceCreateRequestSessionRevokedAction =
  OpenEnum<typeof SSFReceiverStreamServiceCreateRequestSessionRevokedAction>;

/**
 * The SSFReceiverStreamServiceCreateRequest message.
 */
export type SSFReceiverStreamServiceCreateRequest = {
  /**
   * The accountDisabledAction field.
   */
  accountDisabledAction?:
    | SSFReceiverStreamServiceCreateRequestAccountDisabledAction
    | undefined;
  /**
   * The credentialChangeAction field.
   */
  credentialChangeAction?:
    | SSFReceiverStreamServiceCreateRequestCredentialChangeAction
    | undefined;
  /**
   * The credentialCompromiseAction field.
   */
  credentialCompromiseAction?:
    | SSFReceiverStreamServiceCreateRequestCredentialCompromiseAction
    | undefined;
  /**
   * The deliveryMethod field.
   */
  deliveryMethod?:
    | SSFReceiverStreamServiceCreateRequestDeliveryMethod
    | undefined;
  /**
   * The description field.
   */
  description?: string | undefined;
  /**
   * The displayName field.
   */
  displayName: string;
  /**
   * The enabled field.
   */
  enabled?: boolean | undefined;
  /**
   * The expectedAudience field.
   */
  expectedAudience?: string | undefined;
  /**
   * The issuerUrl field.
   */
  issuerUrl: string;
  /**
   * The jwksUrl field.
   */
  jwksUrl?: string | undefined;
  /**
   * The pollEndpointUrl field.
   */
  pollEndpointUrl?: string | undefined;
  pollInterval?: string | undefined;
  /**
   * Per-event-type action configuration.
   */
  sessionRevokedAction?:
    | SSFReceiverStreamServiceCreateRequestSessionRevokedAction
    | undefined;
};

/** @internal */
export const SSFReceiverStreamServiceCreateRequestAccountDisabledAction$outboundSchema:
  z.ZodType<
    string,
    z.ZodTypeDef,
    SSFReceiverStreamServiceCreateRequestAccountDisabledAction
  > = openEnums.outboundSchema(
    SSFReceiverStreamServiceCreateRequestAccountDisabledAction,
  );

/** @internal */
export const SSFReceiverStreamServiceCreateRequestCredentialChangeAction$outboundSchema:
  z.ZodType<
    string,
    z.ZodTypeDef,
    SSFReceiverStreamServiceCreateRequestCredentialChangeAction
  > = openEnums.outboundSchema(
    SSFReceiverStreamServiceCreateRequestCredentialChangeAction,
  );

/** @internal */
export const SSFReceiverStreamServiceCreateRequestCredentialCompromiseAction$outboundSchema:
  z.ZodType<
    string,
    z.ZodTypeDef,
    SSFReceiverStreamServiceCreateRequestCredentialCompromiseAction
  > = openEnums.outboundSchema(
    SSFReceiverStreamServiceCreateRequestCredentialCompromiseAction,
  );

/** @internal */
export const SSFReceiverStreamServiceCreateRequestDeliveryMethod$outboundSchema:
  z.ZodType<
    string,
    z.ZodTypeDef,
    SSFReceiverStreamServiceCreateRequestDeliveryMethod
  > = openEnums.outboundSchema(
    SSFReceiverStreamServiceCreateRequestDeliveryMethod,
  );

/** @internal */
export const SSFReceiverStreamServiceCreateRequestSessionRevokedAction$outboundSchema:
  z.ZodType<
    string,
    z.ZodTypeDef,
    SSFReceiverStreamServiceCreateRequestSessionRevokedAction
  > = openEnums.outboundSchema(
    SSFReceiverStreamServiceCreateRequestSessionRevokedAction,
  );

/** @internal */
export type SSFReceiverStreamServiceCreateRequest$Outbound = {
  accountDisabledAction?: string | undefined;
  credentialChangeAction?: string | undefined;
  credentialCompromiseAction?: string | undefined;
  deliveryMethod?: string | undefined;
  description?: string | undefined;
  displayName: string;
  enabled?: boolean | undefined;
  expectedAudience?: string | undefined;
  issuerUrl: string;
  jwksUrl?: string | undefined;
  pollEndpointUrl?: string | undefined;
  pollInterval?: string | undefined;
  sessionRevokedAction?: string | undefined;
};

/** @internal */
export const SSFReceiverStreamServiceCreateRequest$outboundSchema: z.ZodType<
  SSFReceiverStreamServiceCreateRequest$Outbound,
  z.ZodTypeDef,
  SSFReceiverStreamServiceCreateRequest
> = z.object({
  accountDisabledAction:
    SSFReceiverStreamServiceCreateRequestAccountDisabledAction$outboundSchema
      .optional(),
  credentialChangeAction:
    SSFReceiverStreamServiceCreateRequestCredentialChangeAction$outboundSchema
      .optional(),
  credentialCompromiseAction:
    SSFReceiverStreamServiceCreateRequestCredentialCompromiseAction$outboundSchema
      .optional(),
  deliveryMethod:
    SSFReceiverStreamServiceCreateRequestDeliveryMethod$outboundSchema
      .optional(),
  description: z.string().optional(),
  displayName: z.string(),
  enabled: z.boolean().optional(),
  expectedAudience: z.string().optional(),
  issuerUrl: z.string(),
  jwksUrl: z.string().optional(),
  pollEndpointUrl: z.string().optional(),
  pollInterval: z.string().optional(),
  sessionRevokedAction:
    SSFReceiverStreamServiceCreateRequestSessionRevokedAction$outboundSchema
      .optional(),
});

export function ssfReceiverStreamServiceCreateRequestToJSON(
  ssfReceiverStreamServiceCreateRequest: SSFReceiverStreamServiceCreateRequest,
): string {
  return JSON.stringify(
    SSFReceiverStreamServiceCreateRequest$outboundSchema.parse(
      ssfReceiverStreamServiceCreateRequest,
    ),
  );
}
