/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * The SSFReceiverStreamServiceDeleteResponse message.
 */
export type SSFReceiverStreamServiceDeleteResponse = {};

/** @internal */
export const SSFReceiverStreamServiceDeleteResponse$inboundSchema: z.ZodType<
  SSFReceiverStreamServiceDeleteResponse,
  z.ZodTypeDef,
  unknown
> = z.object({});

export function ssfReceiverStreamServiceDeleteResponseFromJSON(
  jsonString: string,
): SafeParseResult<SSFReceiverStreamServiceDeleteResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      SSFReceiverStreamServiceDeleteResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SSFReceiverStreamServiceDeleteResponse' from JSON`,
  );
}
