/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  ChipsField,
  ChipsField$inboundSchema,
  ChipsField$Outbound,
  ChipsField$outboundSchema,
} from "./chipsfield.js";
import {
  RepeatedRules,
  RepeatedRules$inboundSchema,
  RepeatedRules$Outbound,
  RepeatedRules$outboundSchema,
} from "./repeatedrules.js";

/**
 * The StringSliceField message.
 *
 * @remarks
 *
 * This message contains a oneof named view. Only a single field of the following list may be set at a time:
 *   - chipsField
 *
 * This message contains a oneof named _rules. Only a single field of the following list may be set at a time:
 *   - rules
 */
export type StringSliceField = {
  chipsField?: ChipsField | null | undefined;
  /**
   * The defaultValues field.
   */
  defaultValues?: Array<string> | null | undefined;
  /**
   * The placeholder field.
   */
  placeholder?: string | null | undefined;
  rules?: RepeatedRules | null | undefined;
};

/** @internal */
export const StringSliceField$inboundSchema: z.ZodType<
  StringSliceField,
  z.ZodTypeDef,
  unknown
> = z.object({
  chipsField: z.nullable(ChipsField$inboundSchema).optional(),
  defaultValues: z.nullable(z.array(z.string())).optional(),
  placeholder: z.nullable(z.string()).optional(),
  rules: z.nullable(RepeatedRules$inboundSchema).optional(),
});
/** @internal */
export type StringSliceField$Outbound = {
  chipsField?: ChipsField$Outbound | null | undefined;
  defaultValues?: Array<string> | null | undefined;
  placeholder?: string | null | undefined;
  rules?: RepeatedRules$Outbound | null | undefined;
};

/** @internal */
export const StringSliceField$outboundSchema: z.ZodType<
  StringSliceField$Outbound,
  z.ZodTypeDef,
  StringSliceField
> = z.object({
  chipsField: z.nullable(ChipsField$outboundSchema).optional(),
  defaultValues: z.nullable(z.array(z.string())).optional(),
  placeholder: z.nullable(z.string()).optional(),
  rules: z.nullable(RepeatedRules$outboundSchema).optional(),
});

export function stringSliceFieldToJSON(
  stringSliceField: StringSliceField,
): string {
  return JSON.stringify(
    StringSliceField$outboundSchema.parse(stringSliceField),
  );
}
export function stringSliceFieldFromJSON(
  jsonString: string,
): SafeParseResult<StringSliceField, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => StringSliceField$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'StringSliceField' from JSON`,
  );
}
