/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  TaskExpandMask,
  TaskExpandMask$inboundSchema,
  TaskExpandMask$Outbound,
  TaskExpandMask$outboundSchema,
} from "./taskexpandmask.js";

/**
 * The TaskActionsServiceUpdateGrantDurationRequest message.
 */
export type TaskActionsServiceUpdateGrantDurationRequest = {
  duration: string;
  expandMask?: TaskExpandMask | null | undefined;
};

/** @internal */
export const TaskActionsServiceUpdateGrantDurationRequest$inboundSchema:
  z.ZodType<
    TaskActionsServiceUpdateGrantDurationRequest,
    z.ZodTypeDef,
    unknown
  > = z.object({
    duration: z.string(),
    expandMask: z.nullable(TaskExpandMask$inboundSchema).optional(),
  });

/** @internal */
export type TaskActionsServiceUpdateGrantDurationRequest$Outbound = {
  duration: string;
  expandMask?: TaskExpandMask$Outbound | null | undefined;
};

/** @internal */
export const TaskActionsServiceUpdateGrantDurationRequest$outboundSchema:
  z.ZodType<
    TaskActionsServiceUpdateGrantDurationRequest$Outbound,
    z.ZodTypeDef,
    TaskActionsServiceUpdateGrantDurationRequest
  > = z.object({
    duration: z.string(),
    expandMask: z.nullable(TaskExpandMask$outboundSchema).optional(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TaskActionsServiceUpdateGrantDurationRequest$ {
  /** @deprecated use `TaskActionsServiceUpdateGrantDurationRequest$inboundSchema` instead. */
  export const inboundSchema =
    TaskActionsServiceUpdateGrantDurationRequest$inboundSchema;
  /** @deprecated use `TaskActionsServiceUpdateGrantDurationRequest$outboundSchema` instead. */
  export const outboundSchema =
    TaskActionsServiceUpdateGrantDurationRequest$outboundSchema;
  /** @deprecated use `TaskActionsServiceUpdateGrantDurationRequest$Outbound` instead. */
  export type Outbound = TaskActionsServiceUpdateGrantDurationRequest$Outbound;
}

export function taskActionsServiceUpdateGrantDurationRequestToJSON(
  taskActionsServiceUpdateGrantDurationRequest:
    TaskActionsServiceUpdateGrantDurationRequest,
): string {
  return JSON.stringify(
    TaskActionsServiceUpdateGrantDurationRequest$outboundSchema.parse(
      taskActionsServiceUpdateGrantDurationRequest,
    ),
  );
}

export function taskActionsServiceUpdateGrantDurationRequestFromJSON(
  jsonString: string,
): SafeParseResult<
  TaskActionsServiceUpdateGrantDurationRequest,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      TaskActionsServiceUpdateGrantDurationRequest$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'TaskActionsServiceUpdateGrantDurationRequest' from JSON`,
  );
}
