/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * The TaskAuditFormInstanceChange message.
 */
export type TaskAuditFormInstanceChange = {
  /**
   * The isValid field.
   */
  isValid?: boolean | null | undefined;
};

/** @internal */
export const TaskAuditFormInstanceChange$inboundSchema: z.ZodType<
  TaskAuditFormInstanceChange,
  z.ZodTypeDef,
  unknown
> = z.object({
  isValid: z.nullable(z.boolean()).optional(),
});

export function taskAuditFormInstanceChangeFromJSON(
  jsonString: string,
): SafeParseResult<TaskAuditFormInstanceChange, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TaskAuditFormInstanceChange$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TaskAuditFormInstanceChange' from JSON`,
  );
}
