/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * The TaskAuditWaitForAnalysisStepWaiting message.
 */
export type TaskAuditWaitForAnalysisStepWaiting = {
  /**
   * The stepId field.
   */
  stepId?: string | null | undefined;
};

/** @internal */
export const TaskAuditWaitForAnalysisStepWaiting$inboundSchema: z.ZodType<
  TaskAuditWaitForAnalysisStepWaiting,
  z.ZodTypeDef,
  unknown
> = z.object({
  stepId: z.nullable(z.string()).optional(),
});

export function taskAuditWaitForAnalysisStepWaitingFromJSON(
  jsonString: string,
): SafeParseResult<TaskAuditWaitForAnalysisStepWaiting, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      TaskAuditWaitForAnalysisStepWaiting$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TaskAuditWaitForAnalysisStepWaiting' from JSON`,
  );
}
