/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * The TaskAuditWaitForAnalysisStepTimedOut message.
 */
export type TaskAuditWaitForAnalysisStepTimedOut = {
  /**
   * The stepId field.
   */
  stepId?: string | null | undefined;
  timedOutAt?: Date | null | undefined;
};

/** @internal */
export const TaskAuditWaitForAnalysisStepTimedOut$inboundSchema: z.ZodType<
  TaskAuditWaitForAnalysisStepTimedOut,
  z.ZodTypeDef,
  unknown
> = z.object({
  stepId: z.nullable(z.string()).optional(),
  timedOutAt: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
});

/** @internal */
export type TaskAuditWaitForAnalysisStepTimedOut$Outbound = {
  stepId?: string | null | undefined;
  timedOutAt?: string | null | undefined;
};

/** @internal */
export const TaskAuditWaitForAnalysisStepTimedOut$outboundSchema: z.ZodType<
  TaskAuditWaitForAnalysisStepTimedOut$Outbound,
  z.ZodTypeDef,
  TaskAuditWaitForAnalysisStepTimedOut
> = z.object({
  stepId: z.nullable(z.string()).optional(),
  timedOutAt: z.nullable(z.date().transform(v => v.toISOString())).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TaskAuditWaitForAnalysisStepTimedOut$ {
  /** @deprecated use `TaskAuditWaitForAnalysisStepTimedOut$inboundSchema` instead. */
  export const inboundSchema =
    TaskAuditWaitForAnalysisStepTimedOut$inboundSchema;
  /** @deprecated use `TaskAuditWaitForAnalysisStepTimedOut$outboundSchema` instead. */
  export const outboundSchema =
    TaskAuditWaitForAnalysisStepTimedOut$outboundSchema;
  /** @deprecated use `TaskAuditWaitForAnalysisStepTimedOut$Outbound` instead. */
  export type Outbound = TaskAuditWaitForAnalysisStepTimedOut$Outbound;
}

export function taskAuditWaitForAnalysisStepTimedOutToJSON(
  taskAuditWaitForAnalysisStepTimedOut: TaskAuditWaitForAnalysisStepTimedOut,
): string {
  return JSON.stringify(
    TaskAuditWaitForAnalysisStepTimedOut$outboundSchema.parse(
      taskAuditWaitForAnalysisStepTimedOut,
    ),
  );
}

export function taskAuditWaitForAnalysisStepTimedOutFromJSON(
  jsonString: string,
): SafeParseResult<TaskAuditWaitForAnalysisStepTimedOut, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      TaskAuditWaitForAnalysisStepTimedOut$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TaskAuditWaitForAnalysisStepTimedOut' from JSON`,
  );
}
