/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import {
  collectExtraKeys as collectExtraKeys$,
  safeParse,
} from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { TaskView, TaskView$inboundSchema } from "./taskview.js";

/**
 * Contains an arbitrary serialized message along with a @type that describes the type of the serialized message.
 */
export type TaskActionsServiceRestartResponseExpanded = {
  /**
   * The type of the serialized message.
   */
  atType?: string | undefined;
  additionalProperties?: { [k: string]: any } | undefined;
};

/**
 * The TaskActionsServiceRestartResponse message.
 */
export type TaskActionsServiceRestartResponse = {
  /**
   * The expanded field.
   */
  expanded?:
    | Array<TaskActionsServiceRestartResponseExpanded>
    | null
    | undefined;
  taskView?: TaskView | null | undefined;
  /**
   * The ticketActionId field.
   */
  ticketActionId?: string | null | undefined;
};

/** @internal */
export const TaskActionsServiceRestartResponseExpanded$inboundSchema: z.ZodType<
  TaskActionsServiceRestartResponseExpanded,
  z.ZodTypeDef,
  unknown
> = collectExtraKeys$(
  z.object({
    "@type": z.string().optional(),
  }).catchall(z.any()),
  "additionalProperties",
  true,
).transform((v) => {
  return remap$(v, {
    "@type": "atType",
  });
});

export function taskActionsServiceRestartResponseExpandedFromJSON(
  jsonString: string,
): SafeParseResult<
  TaskActionsServiceRestartResponseExpanded,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      TaskActionsServiceRestartResponseExpanded$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'TaskActionsServiceRestartResponseExpanded' from JSON`,
  );
}

/** @internal */
export const TaskActionsServiceRestartResponse$inboundSchema: z.ZodType<
  TaskActionsServiceRestartResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  expanded: z.nullable(
    z.array(
      z.lazy(() => TaskActionsServiceRestartResponseExpanded$inboundSchema),
    ),
  ).optional(),
  taskView: z.nullable(TaskView$inboundSchema).optional(),
  ticketActionId: z.nullable(z.string()).optional(),
});

export function taskActionsServiceRestartResponseFromJSON(
  jsonString: string,
): SafeParseResult<TaskActionsServiceRestartResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TaskActionsServiceRestartResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TaskActionsServiceRestartResponse' from JSON`,
  );
}
