/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { safeParse } from "../../../lib/schemas.js";
/** @internal */
export const TaskAuditWaitForAnalysisStepSuccess$inboundSchema = z.object({
    stepId: z.nullable(z.string()).optional(),
    succeededAt: z.nullable(z.string().datetime({ offset: true }).transform(v => new Date(v))).optional(),
});
/** @internal */
export const TaskAuditWaitForAnalysisStepSuccess$outboundSchema = z.object({
    stepId: z.nullable(z.string()).optional(),
    succeededAt: z.nullable(z.date().transform(v => v.toISOString())).optional(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export var TaskAuditWaitForAnalysisStepSuccess$;
(function (TaskAuditWaitForAnalysisStepSuccess$) {
    /** @deprecated use `TaskAuditWaitForAnalysisStepSuccess$inboundSchema` instead. */
    TaskAuditWaitForAnalysisStepSuccess$.inboundSchema = TaskAuditWaitForAnalysisStepSuccess$inboundSchema;
    /** @deprecated use `TaskAuditWaitForAnalysisStepSuccess$outboundSchema` instead. */
    TaskAuditWaitForAnalysisStepSuccess$.outboundSchema = TaskAuditWaitForAnalysisStepSuccess$outboundSchema;
})(TaskAuditWaitForAnalysisStepSuccess$ || (TaskAuditWaitForAnalysisStepSuccess$ = {}));
export function taskAuditWaitForAnalysisStepSuccessToJSON(taskAuditWaitForAnalysisStepSuccess) {
    return JSON.stringify(TaskAuditWaitForAnalysisStepSuccess$outboundSchema.parse(taskAuditWaitForAnalysisStepSuccess));
}
export function taskAuditWaitForAnalysisStepSuccessFromJSON(jsonString) {
    return safeParse(jsonString, (x) => TaskAuditWaitForAnalysisStepSuccess$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'TaskAuditWaitForAnalysisStepSuccess' from JSON`);
}
