/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { safeParse } from "../../../lib/schemas.js";
/** @internal */
export const TaskAuditWebhookApprovalBadResponse$inboundSchema = z.object({
    error: z.nullable(z.string()).optional(),
    webhookId: z.nullable(z.string()).optional(),
    webhookInstanceId: z.nullable(z.string()).optional(),
    webhookName: z.nullable(z.string()).optional(),
    webhookUrl: z.nullable(z.string()).optional(),
});
/** @internal */
export const TaskAuditWebhookApprovalBadResponse$outboundSchema = z.object({
    error: z.nullable(z.string()).optional(),
    webhookId: z.nullable(z.string()).optional(),
    webhookInstanceId: z.nullable(z.string()).optional(),
    webhookName: z.nullable(z.string()).optional(),
    webhookUrl: z.nullable(z.string()).optional(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export var TaskAuditWebhookApprovalBadResponse$;
(function (TaskAuditWebhookApprovalBadResponse$) {
    /** @deprecated use `TaskAuditWebhookApprovalBadResponse$inboundSchema` instead. */
    TaskAuditWebhookApprovalBadResponse$.inboundSchema = TaskAuditWebhookApprovalBadResponse$inboundSchema;
    /** @deprecated use `TaskAuditWebhookApprovalBadResponse$outboundSchema` instead. */
    TaskAuditWebhookApprovalBadResponse$.outboundSchema = TaskAuditWebhookApprovalBadResponse$outboundSchema;
})(TaskAuditWebhookApprovalBadResponse$ || (TaskAuditWebhookApprovalBadResponse$ = {}));
export function taskAuditWebhookApprovalBadResponseToJSON(taskAuditWebhookApprovalBadResponse) {
    return JSON.stringify(TaskAuditWebhookApprovalBadResponse$outboundSchema.parse(taskAuditWebhookApprovalBadResponse));
}
export function taskAuditWebhookApprovalBadResponseFromJSON(jsonString) {
    return safeParse(jsonString, (x) => TaskAuditWebhookApprovalBadResponse$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'TaskAuditWebhookApprovalBadResponse' from JSON`);
}
