/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import {
  TaskExpandMask,
  TaskExpandMask$Outbound,
  TaskExpandMask$outboundSchema,
} from "./taskexpandmask.js";

/**
 * The TaskActionsServiceDenyRequest object lets you deny a task.
 */
export type TaskActionsServiceDenyRequest = {
  /**
   * The comment attached to the request.
   */
  comment?: string | null | undefined;
  expandMask?: TaskExpandMask | null | undefined;
  /**
   * The ID of the currently policy step. This is the step you want to deny.
   */
  policyStepId?: string | null | undefined;
};

/** @internal */
export type TaskActionsServiceDenyRequest$Outbound = {
  comment?: string | null | undefined;
  expandMask?: TaskExpandMask$Outbound | null | undefined;
  policyStepId?: string | null | undefined;
};

/** @internal */
export const TaskActionsServiceDenyRequest$outboundSchema: z.ZodType<
  TaskActionsServiceDenyRequest$Outbound,
  z.ZodTypeDef,
  TaskActionsServiceDenyRequest
> = z.object({
  comment: z.nullable(z.string()).optional(),
  expandMask: z.nullable(TaskExpandMask$outboundSchema).optional(),
  policyStepId: z.nullable(z.string()).optional(),
});

export function taskActionsServiceDenyRequestToJSON(
  taskActionsServiceDenyRequest: TaskActionsServiceDenyRequest,
): string {
  return JSON.stringify(
    TaskActionsServiceDenyRequest$outboundSchema.parse(
      taskActionsServiceDenyRequest,
    ),
  );
}
