/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import {
  TaskExpandMask,
  TaskExpandMask$Outbound,
  TaskExpandMask$outboundSchema,
} from "./taskexpandmask.js";

/**
 * The TaskActionsServiceSkipStepRequest object lets you skip a policy step in a task.
 */
export type TaskActionsServiceSkipStepRequest = {
  /**
   * The comment attached to the request.
   */
  comment?: string | null | undefined;
  expandMask?: TaskExpandMask | null | undefined;
  /**
   * The ID of the policy step to skip.
   */
  policyStepId: string;
};

/** @internal */
export type TaskActionsServiceSkipStepRequest$Outbound = {
  comment?: string | null | undefined;
  expandMask?: TaskExpandMask$Outbound | null | undefined;
  policyStepId: string;
};

/** @internal */
export const TaskActionsServiceSkipStepRequest$outboundSchema: z.ZodType<
  TaskActionsServiceSkipStepRequest$Outbound,
  z.ZodTypeDef,
  TaskActionsServiceSkipStepRequest
> = z.object({
  comment: z.nullable(z.string()).optional(),
  expandMask: z.nullable(TaskExpandMask$outboundSchema).optional(),
  policyStepId: z.string(),
});

export function taskActionsServiceSkipStepRequestToJSON(
  taskActionsServiceSkipStepRequest: TaskActionsServiceSkipStepRequest,
): string {
  return JSON.stringify(
    TaskActionsServiceSkipStepRequest$outboundSchema.parse(
      taskActionsServiceSkipStepRequest,
    ),
  );
}
