/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * The TaskAuditApprovalAutoAcceptedByPolicy message.
 */
export type TaskAuditApprovalAutoAcceptedByPolicy = {};

/** @internal */
export const TaskAuditApprovalAutoAcceptedByPolicy$inboundSchema: z.ZodType<
  TaskAuditApprovalAutoAcceptedByPolicy,
  z.ZodTypeDef,
  unknown
> = z.object({});

export function taskAuditApprovalAutoAcceptedByPolicyFromJSON(
  jsonString: string,
): SafeParseResult<TaskAuditApprovalAutoAcceptedByPolicy, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      TaskAuditApprovalAutoAcceptedByPolicy$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TaskAuditApprovalAutoAcceptedByPolicy' from JSON`,
  );
}
