/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * The TaskAuditPolicyEvaluationStep message.
 */
export type TaskAuditPolicyEvaluationStep = {
  /**
   * The stepComment field.
   */
  stepComment?: string | null | undefined;
};

/** @internal */
export const TaskAuditPolicyEvaluationStep$inboundSchema: z.ZodType<
  TaskAuditPolicyEvaluationStep,
  z.ZodTypeDef,
  unknown
> = z.object({
  stepComment: z.nullable(z.string()).optional(),
});

export function taskAuditPolicyEvaluationStepFromJSON(
  jsonString: string,
): SafeParseResult<TaskAuditPolicyEvaluationStep, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TaskAuditPolicyEvaluationStep$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TaskAuditPolicyEvaluationStep' from JSON`,
  );
}
