/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import {
  TenantAuthConfigInput,
  TenantAuthConfigInput$Outbound,
  TenantAuthConfigInput$outboundSchema,
} from "./tenantauthconfig.js";

/**
 * The TenantAuthConfigServiceUpdateRequest message.
 */
export type TenantAuthConfigServiceUpdateRequest = {
  /**
   * The TenantAuthConfig message.
   *
   * @remarks
   *
   * This message contains a oneof named provider_config. Only a single field of the following list may be set at a time:
   *   - google
   *   - microsoft
   *   - okta
   *   - onelogin
   *   - jumpcloud
   *   - pingone
   *   - oidc
   *   - c1Local
   */
  tenantAuthConfig?: TenantAuthConfigInput | undefined;
  updateMask?: string | null | undefined;
};

/** @internal */
export type TenantAuthConfigServiceUpdateRequest$Outbound = {
  authConfig?: TenantAuthConfigInput$Outbound | undefined;
  updateMask?: string | null | undefined;
};

/** @internal */
export const TenantAuthConfigServiceUpdateRequest$outboundSchema: z.ZodType<
  TenantAuthConfigServiceUpdateRequest$Outbound,
  z.ZodTypeDef,
  TenantAuthConfigServiceUpdateRequest
> = z.object({
  tenantAuthConfig: TenantAuthConfigInput$outboundSchema.optional(),
  updateMask: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    tenantAuthConfig: "authConfig",
  });
});

export function tenantAuthConfigServiceUpdateRequestToJSON(
  tenantAuthConfigServiceUpdateRequest: TenantAuthConfigServiceUpdateRequest,
): string {
  return JSON.stringify(
    TenantAuthConfigServiceUpdateRequest$outboundSchema.parse(
      tenantAuthConfigServiceUpdateRequest,
    ),
  );
}
