/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  AuthConfigC1Local,
  AuthConfigC1Local$inboundSchema,
  AuthConfigC1Local$Outbound,
  AuthConfigC1Local$outboundSchema,
} from "./authconfigc1local.js";
import {
  AuthConfigGoogle,
  AuthConfigGoogle$inboundSchema,
  AuthConfigGoogle$Outbound,
  AuthConfigGoogle$outboundSchema,
} from "./authconfiggoogle.js";
import {
  AuthConfigJumpCloud,
  AuthConfigJumpCloud$inboundSchema,
  AuthConfigJumpCloud$Outbound,
  AuthConfigJumpCloud$outboundSchema,
} from "./authconfigjumpcloud.js";
import {
  AuthConfigMicrosoft,
  AuthConfigMicrosoft$inboundSchema,
  AuthConfigMicrosoft$Outbound,
  AuthConfigMicrosoft$outboundSchema,
} from "./authconfigmicrosoft.js";
import {
  AuthConfigOIDC,
  AuthConfigOIDC$inboundSchema,
  AuthConfigOIDC$Outbound,
  AuthConfigOIDC$outboundSchema,
} from "./authconfigoidc.js";
import {
  AuthConfigOkta,
  AuthConfigOkta$inboundSchema,
  AuthConfigOkta$Outbound,
  AuthConfigOkta$outboundSchema,
} from "./authconfigokta.js";
import {
  AuthConfigOneLogin,
  AuthConfigOneLogin$inboundSchema,
  AuthConfigOneLogin$Outbound,
  AuthConfigOneLogin$outboundSchema,
} from "./authconfigonelogin.js";
import {
  AuthConfigPingOne,
  AuthConfigPingOne$inboundSchema,
  AuthConfigPingOne$Outbound,
  AuthConfigPingOne$outboundSchema,
} from "./authconfigpingone.js";

/**
 * Provider type (read-only after creation — provider config determines type).
 */
export const ProviderType = {
  AuthConfigProviderTypeUnspecified: "AUTH_CONFIG_PROVIDER_TYPE_UNSPECIFIED",
  AuthConfigProviderTypeGoogle: "AUTH_CONFIG_PROVIDER_TYPE_GOOGLE",
  AuthConfigProviderTypeMicrosoft: "AUTH_CONFIG_PROVIDER_TYPE_MICROSOFT",
  AuthConfigProviderTypeOkta: "AUTH_CONFIG_PROVIDER_TYPE_OKTA",
  AuthConfigProviderTypeOnelogin: "AUTH_CONFIG_PROVIDER_TYPE_ONELOGIN",
  AuthConfigProviderTypeJumpcloud: "AUTH_CONFIG_PROVIDER_TYPE_JUMPCLOUD",
  AuthConfigProviderTypePingone: "AUTH_CONFIG_PROVIDER_TYPE_PINGONE",
  AuthConfigProviderTypeOidc: "AUTH_CONFIG_PROVIDER_TYPE_OIDC",
  AuthConfigProviderTypeC1Local: "AUTH_CONFIG_PROVIDER_TYPE_C1_LOCAL",
} as const;
/**
 * Provider type (read-only after creation — provider config determines type).
 */
export type ProviderType = OpenEnum<typeof ProviderType>;

/**
 * The status field.
 */
export const TenantAuthConfigStatus = {
  AuthConfigStatusUnspecified: "AUTH_CONFIG_STATUS_UNSPECIFIED",
  AuthConfigStatusActive: "AUTH_CONFIG_STATUS_ACTIVE",
  AuthConfigStatusDeprecated: "AUTH_CONFIG_STATUS_DEPRECATED",
  AuthConfigStatusDisabled: "AUTH_CONFIG_STATUS_DISABLED",
} as const;
/**
 * The status field.
 */
export type TenantAuthConfigStatus = OpenEnum<typeof TenantAuthConfigStatus>;

/**
 * The TenantAuthConfig message.
 *
 * @remarks
 *
 * This message contains a oneof named provider_config. Only a single field of the following list may be set at a time:
 *   - google
 *   - microsoft
 *   - okta
 *   - onelogin
 *   - jumpcloud
 *   - pingone
 *   - oidc
 *   - c1Local
 */
export type TenantAuthConfig = {
  /**
   * Bootstrap routing: email domains that route unknown users to this config.
   */
  bootstrapDomains?: Array<string> | null | undefined;
  c1Local?: AuthConfigC1Local | null | undefined;
  createdAt?: Date | null | undefined;
  deprecationDeadline?: Date | null | undefined;
  /**
   * User-visible message shown when status=DEPRECATED.
   */
  deprecationMessage?: string | null | undefined;
  /**
   * The displayName field.
   */
  displayName?: string | null | undefined;
  google?: AuthConfigGoogle | null | undefined;
  /**
   * The id field.
   */
  id?: string | null | undefined;
  /**
   * The isDefaultBootstrap field.
   */
  isDefaultBootstrap?: boolean | null | undefined;
  jumpcloud?: AuthConfigJumpCloud | null | undefined;
  microsoft?: AuthConfigMicrosoft | null | undefined;
  oidc?: AuthConfigOIDC | null | undefined;
  okta?: AuthConfigOkta | null | undefined;
  onelogin?: AuthConfigOneLogin | null | undefined;
  pingone?: AuthConfigPingOne | null | undefined;
  /**
   * Provider type (read-only after creation — provider config determines type).
   */
  providerType?: ProviderType | null | undefined;
  /**
   * The status field.
   */
  status?: TenantAuthConfigStatus | null | undefined;
  updatedAt?: Date | null | undefined;
};

/**
 * The TenantAuthConfig message.
 *
 * @remarks
 *
 * This message contains a oneof named provider_config. Only a single field of the following list may be set at a time:
 *   - google
 *   - microsoft
 *   - okta
 *   - onelogin
 *   - jumpcloud
 *   - pingone
 *   - oidc
 *   - c1Local
 */
export type TenantAuthConfigInput = {
  /**
   * Bootstrap routing: email domains that route unknown users to this config.
   */
  bootstrapDomains?: Array<string> | null | undefined;
  c1Local?: AuthConfigC1Local | null | undefined;
  deprecationDeadline?: Date | null | undefined;
  /**
   * User-visible message shown when status=DEPRECATED.
   */
  deprecationMessage?: string | null | undefined;
  /**
   * The displayName field.
   */
  displayName?: string | null | undefined;
  google?: AuthConfigGoogle | null | undefined;
  /**
   * The id field.
   */
  id?: string | null | undefined;
  /**
   * The isDefaultBootstrap field.
   */
  isDefaultBootstrap?: boolean | null | undefined;
  jumpcloud?: AuthConfigJumpCloud | null | undefined;
  microsoft?: AuthConfigMicrosoft | null | undefined;
  oidc?: AuthConfigOIDC | null | undefined;
  okta?: AuthConfigOkta | null | undefined;
  onelogin?: AuthConfigOneLogin | null | undefined;
  pingone?: AuthConfigPingOne | null | undefined;
  /**
   * The status field.
   */
  status?: TenantAuthConfigStatus | null | undefined;
};

/** @internal */
export const ProviderType$inboundSchema: z.ZodType<
  ProviderType,
  z.ZodTypeDef,
  unknown
> = openEnums.inboundSchema(ProviderType);

/** @internal */
export const TenantAuthConfigStatus$inboundSchema: z.ZodType<
  TenantAuthConfigStatus,
  z.ZodTypeDef,
  unknown
> = openEnums.inboundSchema(TenantAuthConfigStatus);
/** @internal */
export const TenantAuthConfigStatus$outboundSchema: z.ZodType<
  string,
  z.ZodTypeDef,
  TenantAuthConfigStatus
> = openEnums.outboundSchema(TenantAuthConfigStatus);

/** @internal */
export const TenantAuthConfig$inboundSchema: z.ZodType<
  TenantAuthConfig,
  z.ZodTypeDef,
  unknown
> = z.object({
  bootstrapDomains: z.nullable(z.array(z.string())).optional(),
  c1Local: z.nullable(AuthConfigC1Local$inboundSchema).optional(),
  createdAt: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
  deprecationDeadline: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
  deprecationMessage: z.nullable(z.string()).optional(),
  displayName: z.nullable(z.string()).optional(),
  google: z.nullable(AuthConfigGoogle$inboundSchema).optional(),
  id: z.nullable(z.string()).optional(),
  isDefaultBootstrap: z.nullable(z.boolean()).optional(),
  jumpcloud: z.nullable(AuthConfigJumpCloud$inboundSchema).optional(),
  microsoft: z.nullable(AuthConfigMicrosoft$inboundSchema).optional(),
  oidc: z.nullable(AuthConfigOIDC$inboundSchema).optional(),
  okta: z.nullable(AuthConfigOkta$inboundSchema).optional(),
  onelogin: z.nullable(AuthConfigOneLogin$inboundSchema).optional(),
  pingone: z.nullable(AuthConfigPingOne$inboundSchema).optional(),
  providerType: z.nullable(ProviderType$inboundSchema).optional(),
  status: z.nullable(TenantAuthConfigStatus$inboundSchema).optional(),
  updatedAt: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
});

export function tenantAuthConfigFromJSON(
  jsonString: string,
): SafeParseResult<TenantAuthConfig, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TenantAuthConfig$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TenantAuthConfig' from JSON`,
  );
}

/** @internal */
export type TenantAuthConfigInput$Outbound = {
  bootstrapDomains?: Array<string> | null | undefined;
  c1Local?: AuthConfigC1Local$Outbound | null | undefined;
  deprecationDeadline?: string | null | undefined;
  deprecationMessage?: string | null | undefined;
  displayName?: string | null | undefined;
  google?: AuthConfigGoogle$Outbound | null | undefined;
  id?: string | null | undefined;
  isDefaultBootstrap?: boolean | null | undefined;
  jumpcloud?: AuthConfigJumpCloud$Outbound | null | undefined;
  microsoft?: AuthConfigMicrosoft$Outbound | null | undefined;
  oidc?: AuthConfigOIDC$Outbound | null | undefined;
  okta?: AuthConfigOkta$Outbound | null | undefined;
  onelogin?: AuthConfigOneLogin$Outbound | null | undefined;
  pingone?: AuthConfigPingOne$Outbound | null | undefined;
  status?: string | null | undefined;
};

/** @internal */
export const TenantAuthConfigInput$outboundSchema: z.ZodType<
  TenantAuthConfigInput$Outbound,
  z.ZodTypeDef,
  TenantAuthConfigInput
> = z.object({
  bootstrapDomains: z.nullable(z.array(z.string())).optional(),
  c1Local: z.nullable(AuthConfigC1Local$outboundSchema).optional(),
  deprecationDeadline: z.nullable(z.date().transform(v => v.toISOString()))
    .optional(),
  deprecationMessage: z.nullable(z.string()).optional(),
  displayName: z.nullable(z.string()).optional(),
  google: z.nullable(AuthConfigGoogle$outboundSchema).optional(),
  id: z.nullable(z.string()).optional(),
  isDefaultBootstrap: z.nullable(z.boolean()).optional(),
  jumpcloud: z.nullable(AuthConfigJumpCloud$outboundSchema).optional(),
  microsoft: z.nullable(AuthConfigMicrosoft$outboundSchema).optional(),
  oidc: z.nullable(AuthConfigOIDC$outboundSchema).optional(),
  okta: z.nullable(AuthConfigOkta$outboundSchema).optional(),
  onelogin: z.nullable(AuthConfigOneLogin$outboundSchema).optional(),
  pingone: z.nullable(AuthConfigPingOne$outboundSchema).optional(),
  status: z.nullable(TenantAuthConfigStatus$outboundSchema).optional(),
});

export function tenantAuthConfigInputToJSON(
  tenantAuthConfigInput: TenantAuthConfigInput,
): string {
  return JSON.stringify(
    TenantAuthConfigInput$outboundSchema.parse(tenantAuthConfigInput),
  );
}
