/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * The TenantAuthConfigServiceDeleteResponse message.
 */
export type TenantAuthConfigServiceDeleteResponse = {};

/** @internal */
export const TenantAuthConfigServiceDeleteResponse$inboundSchema: z.ZodType<
  TenantAuthConfigServiceDeleteResponse,
  z.ZodTypeDef,
  unknown
> = z.object({});

export function tenantAuthConfigServiceDeleteResponseFromJSON(
  jsonString: string,
): SafeParseResult<TenantAuthConfigServiceDeleteResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      TenantAuthConfigServiceDeleteResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TenantAuthConfigServiceDeleteResponse' from JSON`,
  );
}
