/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * The ToggleField message.
 */
export type ToggleField = {};

/** @internal */
export const ToggleField$inboundSchema: z.ZodType<
  ToggleField,
  z.ZodTypeDef,
  unknown
> = z.object({});

/** @internal */
export type ToggleField$Outbound = {};

/** @internal */
export const ToggleField$outboundSchema: z.ZodType<
  ToggleField$Outbound,
  z.ZodTypeDef,
  ToggleField
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ToggleField$ {
  /** @deprecated use `ToggleField$inboundSchema` instead. */
  export const inboundSchema = ToggleField$inboundSchema;
  /** @deprecated use `ToggleField$outboundSchema` instead. */
  export const outboundSchema = ToggleField$outboundSchema;
  /** @deprecated use `ToggleField$Outbound` instead. */
  export type Outbound = ToggleField$Outbound;
}

export function toggleFieldToJSON(toggleField: ToggleField): string {
  return JSON.stringify(ToggleField$outboundSchema.parse(toggleField));
}

export function toggleFieldFromJSON(
  jsonString: string,
): SafeParseResult<ToggleField, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ToggleField$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ToggleField' from JSON`,
  );
}
