/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import {
  ConnectorScheduleCron,
  ConnectorScheduleCron$Outbound,
  ConnectorScheduleCron$outboundSchema,
} from "./connectorschedulecron.js";

/**
 * The UpdateConnectorScheduleRequest message contains the fields required to update a connector's sync schedule.
 *
 * @remarks
 *
 * This message contains a oneof named schedule. Only a single field of the following list may be set at a time:
 *   - cron
 */
export type UpdateConnectorScheduleRequest = {
  cron?: ConnectorScheduleCron | null | undefined;
};

/** @internal */
export type UpdateConnectorScheduleRequest$Outbound = {
  cron?: ConnectorScheduleCron$Outbound | null | undefined;
};

/** @internal */
export const UpdateConnectorScheduleRequest$outboundSchema: z.ZodType<
  UpdateConnectorScheduleRequest$Outbound,
  z.ZodTypeDef,
  UpdateConnectorScheduleRequest
> = z.object({
  cron: z.nullable(ConnectorScheduleCron$outboundSchema).optional(),
});

export function updateConnectorScheduleRequestToJSON(
  updateConnectorScheduleRequest: UpdateConnectorScheduleRequest,
): string {
  return JSON.stringify(
    UpdateConnectorScheduleRequest$outboundSchema.parse(
      updateConnectorScheduleRequest,
    ),
  );
}
