/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * The WaitCondition message.
 */
export type WaitCondition = {
  /**
   * The condition that has to be true for this wait condition to continue.
   */
  condition?: string | null | undefined;
};

/** @internal */
export const WaitCondition$inboundSchema: z.ZodType<
  WaitCondition,
  z.ZodTypeDef,
  unknown
> = z.object({
  condition: z.nullable(z.string()).optional(),
});
/** @internal */
export type WaitCondition$Outbound = {
  condition?: string | null | undefined;
};

/** @internal */
export const WaitCondition$outboundSchema: z.ZodType<
  WaitCondition$Outbound,
  z.ZodTypeDef,
  WaitCondition
> = z.object({
  condition: z.nullable(z.string()).optional(),
});

export function waitConditionToJSON(waitCondition: WaitCondition): string {
  return JSON.stringify(WaitCondition$outboundSchema.parse(waitCondition));
}
export function waitConditionFromJSON(
  jsonString: string,
): SafeParseResult<WaitCondition, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WaitCondition$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WaitCondition' from JSON`,
  );
}
