/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

/**
 * The WebhooksServiceCreateRequest message.
 */
export type WebhooksServiceCreateRequest = {
  callbackTimeout?: string | undefined;
  /**
   * An optional description of the webhook's purpose.
   */
  description?: string | null | undefined;
  /**
   * The human-readable name for the new webhook.
   */
  displayName: string;
  /**
   * The destination URL that will receive event notification HTTP callbacks.
   */
  url: string;
};

/** @internal */
export type WebhooksServiceCreateRequest$Outbound = {
  callbackTimeout?: string | undefined;
  description?: string | null | undefined;
  displayName: string;
  url: string;
};

/** @internal */
export const WebhooksServiceCreateRequest$outboundSchema: z.ZodType<
  WebhooksServiceCreateRequest$Outbound,
  z.ZodTypeDef,
  WebhooksServiceCreateRequest
> = z.object({
  callbackTimeout: z.string().optional(),
  description: z.nullable(z.string()).optional(),
  displayName: z.string(),
  url: z.string(),
});

export function webhooksServiceCreateRequestToJSON(
  webhooksServiceCreateRequest: WebhooksServiceCreateRequest,
): string {
  return JSON.stringify(
    WebhooksServiceCreateRequest$outboundSchema.parse(
      webhooksServiceCreateRequest,
    ),
  );
}
