/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type C1ApiWebhooksV1WebhooksServiceGetRequest = {
  id: string | null;
};

export type C1ApiWebhooksV1WebhooksServiceGetResponse = {
  /**
   * HTTP response content type for this operation
   */
  contentType: string;
  /**
   * HTTP response status code for this operation
   */
  statusCode: number;
  /**
   * Raw HTTP response; suitable for custom response parsing
   */
  rawResponse: Response;
  /**
   * Successful response
   */
  webhooksServiceGetResponse?: shared.WebhooksServiceGetResponse | undefined;
};

/** @internal */
export const C1ApiWebhooksV1WebhooksServiceGetRequest$inboundSchema: z.ZodType<
  C1ApiWebhooksV1WebhooksServiceGetRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.nullable(z.string()),
});

/** @internal */
export type C1ApiWebhooksV1WebhooksServiceGetRequest$Outbound = {
  id: string | null;
};

/** @internal */
export const C1ApiWebhooksV1WebhooksServiceGetRequest$outboundSchema: z.ZodType<
  C1ApiWebhooksV1WebhooksServiceGetRequest$Outbound,
  z.ZodTypeDef,
  C1ApiWebhooksV1WebhooksServiceGetRequest
> = z.object({
  id: z.nullable(z.string()),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace C1ApiWebhooksV1WebhooksServiceGetRequest$ {
  /** @deprecated use `C1ApiWebhooksV1WebhooksServiceGetRequest$inboundSchema` instead. */
  export const inboundSchema =
    C1ApiWebhooksV1WebhooksServiceGetRequest$inboundSchema;
  /** @deprecated use `C1ApiWebhooksV1WebhooksServiceGetRequest$outboundSchema` instead. */
  export const outboundSchema =
    C1ApiWebhooksV1WebhooksServiceGetRequest$outboundSchema;
  /** @deprecated use `C1ApiWebhooksV1WebhooksServiceGetRequest$Outbound` instead. */
  export type Outbound = C1ApiWebhooksV1WebhooksServiceGetRequest$Outbound;
}

export function c1ApiWebhooksV1WebhooksServiceGetRequestToJSON(
  c1ApiWebhooksV1WebhooksServiceGetRequest:
    C1ApiWebhooksV1WebhooksServiceGetRequest,
): string {
  return JSON.stringify(
    C1ApiWebhooksV1WebhooksServiceGetRequest$outboundSchema.parse(
      c1ApiWebhooksV1WebhooksServiceGetRequest,
    ),
  );
}

export function c1ApiWebhooksV1WebhooksServiceGetRequestFromJSON(
  jsonString: string,
): SafeParseResult<
  C1ApiWebhooksV1WebhooksServiceGetRequest,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      C1ApiWebhooksV1WebhooksServiceGetRequest$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'C1ApiWebhooksV1WebhooksServiceGetRequest' from JSON`,
  );
}

/** @internal */
export const C1ApiWebhooksV1WebhooksServiceGetResponse$inboundSchema: z.ZodType<
  C1ApiWebhooksV1WebhooksServiceGetResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  StatusCode: z.number().int(),
  RawResponse: z.instanceof(Response),
  WebhooksServiceGetResponse: shared.WebhooksServiceGetResponse$inboundSchema
    .optional(),
}).transform((v) => {
  return remap$(v, {
    "ContentType": "contentType",
    "StatusCode": "statusCode",
    "RawResponse": "rawResponse",
    "WebhooksServiceGetResponse": "webhooksServiceGetResponse",
  });
});

/** @internal */
export type C1ApiWebhooksV1WebhooksServiceGetResponse$Outbound = {
  ContentType: string;
  StatusCode: number;
  RawResponse: never;
  WebhooksServiceGetResponse?:
    | shared.WebhooksServiceGetResponse$Outbound
    | undefined;
};

/** @internal */
export const C1ApiWebhooksV1WebhooksServiceGetResponse$outboundSchema:
  z.ZodType<
    C1ApiWebhooksV1WebhooksServiceGetResponse$Outbound,
    z.ZodTypeDef,
    C1ApiWebhooksV1WebhooksServiceGetResponse
  > = z.object({
    contentType: z.string(),
    statusCode: z.number().int(),
    rawResponse: z.instanceof(Response).transform(() => {
      throw new Error("Response cannot be serialized");
    }),
    webhooksServiceGetResponse: shared.WebhooksServiceGetResponse$outboundSchema
      .optional(),
  }).transform((v) => {
    return remap$(v, {
      contentType: "ContentType",
      statusCode: "StatusCode",
      rawResponse: "RawResponse",
      webhooksServiceGetResponse: "WebhooksServiceGetResponse",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace C1ApiWebhooksV1WebhooksServiceGetResponse$ {
  /** @deprecated use `C1ApiWebhooksV1WebhooksServiceGetResponse$inboundSchema` instead. */
  export const inboundSchema =
    C1ApiWebhooksV1WebhooksServiceGetResponse$inboundSchema;
  /** @deprecated use `C1ApiWebhooksV1WebhooksServiceGetResponse$outboundSchema` instead. */
  export const outboundSchema =
    C1ApiWebhooksV1WebhooksServiceGetResponse$outboundSchema;
  /** @deprecated use `C1ApiWebhooksV1WebhooksServiceGetResponse$Outbound` instead. */
  export type Outbound = C1ApiWebhooksV1WebhooksServiceGetResponse$Outbound;
}

export function c1ApiWebhooksV1WebhooksServiceGetResponseToJSON(
  c1ApiWebhooksV1WebhooksServiceGetResponse:
    C1ApiWebhooksV1WebhooksServiceGetResponse,
): string {
  return JSON.stringify(
    C1ApiWebhooksV1WebhooksServiceGetResponse$outboundSchema.parse(
      c1ApiWebhooksV1WebhooksServiceGetResponse,
    ),
  );
}

export function c1ApiWebhooksV1WebhooksServiceGetResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  C1ApiWebhooksV1WebhooksServiceGetResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      C1ApiWebhooksV1WebhooksServiceGetResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'C1ApiWebhooksV1WebhooksServiceGetResponse' from JSON`,
  );
}
