/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type C1ApiAppV1AppResourceTypeServiceCreateManuallyManagedResourceTypeRequest =
  {
    appId: string | null;
    createManuallyManagedResourceTypeRequest?:
      | shared.CreateManuallyManagedResourceTypeRequest
      | undefined;
  };

export type C1ApiAppV1AppResourceTypeServiceCreateManuallyManagedResourceTypeResponse =
  {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
    /**
     * Successful response
     */
    createManuallyManagedResourceTypeResponse?:
      | shared.CreateManuallyManagedResourceTypeResponse
      | undefined;
  };

/** @internal */
export type C1ApiAppV1AppResourceTypeServiceCreateManuallyManagedResourceTypeRequest$Outbound =
  {
    app_id: string | null;
    CreateManuallyManagedResourceTypeRequest?:
      | shared.CreateManuallyManagedResourceTypeRequest$Outbound
      | undefined;
  };

/** @internal */
export const C1ApiAppV1AppResourceTypeServiceCreateManuallyManagedResourceTypeRequest$outboundSchema:
  z.ZodType<
    C1ApiAppV1AppResourceTypeServiceCreateManuallyManagedResourceTypeRequest$Outbound,
    z.ZodTypeDef,
    C1ApiAppV1AppResourceTypeServiceCreateManuallyManagedResourceTypeRequest
  > = z.object({
    appId: z.nullable(z.string()),
    createManuallyManagedResourceTypeRequest: shared
      .CreateManuallyManagedResourceTypeRequest$outboundSchema.optional(),
  }).transform((v) => {
    return remap$(v, {
      appId: "app_id",
      createManuallyManagedResourceTypeRequest:
        "CreateManuallyManagedResourceTypeRequest",
    });
  });

export function c1ApiAppV1AppResourceTypeServiceCreateManuallyManagedResourceTypeRequestToJSON(
  c1ApiAppV1AppResourceTypeServiceCreateManuallyManagedResourceTypeRequest:
    C1ApiAppV1AppResourceTypeServiceCreateManuallyManagedResourceTypeRequest,
): string {
  return JSON.stringify(
    C1ApiAppV1AppResourceTypeServiceCreateManuallyManagedResourceTypeRequest$outboundSchema
      .parse(
        c1ApiAppV1AppResourceTypeServiceCreateManuallyManagedResourceTypeRequest,
      ),
  );
}

/** @internal */
export const C1ApiAppV1AppResourceTypeServiceCreateManuallyManagedResourceTypeResponse$inboundSchema:
  z.ZodType<
    C1ApiAppV1AppResourceTypeServiceCreateManuallyManagedResourceTypeResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    ContentType: z.string(),
    StatusCode: z.number().int(),
    RawResponse: z.instanceof(Response),
    CreateManuallyManagedResourceTypeResponse: shared
      .CreateManuallyManagedResourceTypeResponse$inboundSchema.optional(),
  }).transform((v) => {
    return remap$(v, {
      "ContentType": "contentType",
      "StatusCode": "statusCode",
      "RawResponse": "rawResponse",
      "CreateManuallyManagedResourceTypeResponse":
        "createManuallyManagedResourceTypeResponse",
    });
  });

export function c1ApiAppV1AppResourceTypeServiceCreateManuallyManagedResourceTypeResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  C1ApiAppV1AppResourceTypeServiceCreateManuallyManagedResourceTypeResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      C1ApiAppV1AppResourceTypeServiceCreateManuallyManagedResourceTypeResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'C1ApiAppV1AppResourceTypeServiceCreateManuallyManagedResourceTypeResponse' from JSON`,
  );
}
