/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type C1ApiServicePrincipalV1ServicePrincipalServiceGetRequest = {
  id: string;
};

export type C1ApiServicePrincipalV1ServicePrincipalServiceGetResponse = {
  /**
   * HTTP response content type for this operation
   */
  contentType: string;
  /**
   * HTTP response status code for this operation
   */
  statusCode: number;
  /**
   * Raw HTTP response; suitable for custom response parsing
   */
  rawResponse: Response;
  /**
   * Successful response
   */
  servicePrincipalServiceGetResponse?:
    | shared.ServicePrincipalServiceGetResponse
    | undefined;
};

/** @internal */
export type C1ApiServicePrincipalV1ServicePrincipalServiceGetRequest$Outbound =
  {
    id: string;
  };

/** @internal */
export const C1ApiServicePrincipalV1ServicePrincipalServiceGetRequest$outboundSchema:
  z.ZodType<
    C1ApiServicePrincipalV1ServicePrincipalServiceGetRequest$Outbound,
    z.ZodTypeDef,
    C1ApiServicePrincipalV1ServicePrincipalServiceGetRequest
  > = z.object({
    id: z.string(),
  });

export function c1ApiServicePrincipalV1ServicePrincipalServiceGetRequestToJSON(
  c1ApiServicePrincipalV1ServicePrincipalServiceGetRequest:
    C1ApiServicePrincipalV1ServicePrincipalServiceGetRequest,
): string {
  return JSON.stringify(
    C1ApiServicePrincipalV1ServicePrincipalServiceGetRequest$outboundSchema
      .parse(c1ApiServicePrincipalV1ServicePrincipalServiceGetRequest),
  );
}

/** @internal */
export const C1ApiServicePrincipalV1ServicePrincipalServiceGetResponse$inboundSchema:
  z.ZodType<
    C1ApiServicePrincipalV1ServicePrincipalServiceGetResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    ContentType: z.string(),
    StatusCode: z.number().int(),
    RawResponse: z.instanceof(Response),
    ServicePrincipalServiceGetResponse: shared
      .ServicePrincipalServiceGetResponse$inboundSchema.optional(),
  }).transform((v) => {
    return remap$(v, {
      "ContentType": "contentType",
      "StatusCode": "statusCode",
      "RawResponse": "rawResponse",
      "ServicePrincipalServiceGetResponse":
        "servicePrincipalServiceGetResponse",
    });
  });

export function c1ApiServicePrincipalV1ServicePrincipalServiceGetResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  C1ApiServicePrincipalV1ServicePrincipalServiceGetResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      C1ApiServicePrincipalV1ServicePrincipalServiceGetResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'C1ApiServicePrincipalV1ServicePrincipalServiceGetResponse' from JSON`,
  );
}
