/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type C1ApiFunctionsV1FunctionsServiceListTagsRequest = {
  functionId: string | null;
};

export type C1ApiFunctionsV1FunctionsServiceListTagsResponse = {
  /**
   * HTTP response content type for this operation
   */
  contentType: string;
  /**
   * HTTP response status code for this operation
   */
  statusCode: number;
  /**
   * Raw HTTP response; suitable for custom response parsing
   */
  rawResponse: Response;
  /**
   * Successful response
   */
  functionsServiceListTagsResponse?:
    | shared.FunctionsServiceListTagsResponse
    | undefined;
};

/** @internal */
export type C1ApiFunctionsV1FunctionsServiceListTagsRequest$Outbound = {
  function_id: string | null;
};

/** @internal */
export const C1ApiFunctionsV1FunctionsServiceListTagsRequest$outboundSchema:
  z.ZodType<
    C1ApiFunctionsV1FunctionsServiceListTagsRequest$Outbound,
    z.ZodTypeDef,
    C1ApiFunctionsV1FunctionsServiceListTagsRequest
  > = z.object({
    functionId: z.nullable(z.string()),
  }).transform((v) => {
    return remap$(v, {
      functionId: "function_id",
    });
  });

export function c1ApiFunctionsV1FunctionsServiceListTagsRequestToJSON(
  c1ApiFunctionsV1FunctionsServiceListTagsRequest:
    C1ApiFunctionsV1FunctionsServiceListTagsRequest,
): string {
  return JSON.stringify(
    C1ApiFunctionsV1FunctionsServiceListTagsRequest$outboundSchema.parse(
      c1ApiFunctionsV1FunctionsServiceListTagsRequest,
    ),
  );
}

/** @internal */
export const C1ApiFunctionsV1FunctionsServiceListTagsResponse$inboundSchema:
  z.ZodType<
    C1ApiFunctionsV1FunctionsServiceListTagsResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    ContentType: z.string(),
    StatusCode: z.number().int(),
    RawResponse: z.instanceof(Response),
    FunctionsServiceListTagsResponse: shared
      .FunctionsServiceListTagsResponse$inboundSchema.optional(),
  }).transform((v) => {
    return remap$(v, {
      "ContentType": "contentType",
      "StatusCode": "statusCode",
      "RawResponse": "rawResponse",
      "FunctionsServiceListTagsResponse": "functionsServiceListTagsResponse",
    });
  });

export function c1ApiFunctionsV1FunctionsServiceListTagsResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  C1ApiFunctionsV1FunctionsServiceListTagsResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      C1ApiFunctionsV1FunctionsServiceListTagsResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'C1ApiFunctionsV1FunctionsServiceListTagsResponse' from JSON`,
  );
}
