/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type C1ApiAccessreviewV1AccessReviewSetupEntitlementServiceSetCampaignScopeAndEntitlementsRequest =
  {
    accessReviewId: string;
    accessReviewSetupEntitlementAndScopeServiceSetRequest?:
      | shared.AccessReviewSetupEntitlementAndScopeServiceSetRequest
      | undefined;
  };

export type C1ApiAccessreviewV1AccessReviewSetupEntitlementServiceSetCampaignScopeAndEntitlementsResponse =
  {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
    /**
     * Successful response
     */
    accessReviewSetupEntitlementAndScopeServiceSetResponse?:
      | shared.AccessReviewSetupEntitlementAndScopeServiceSetResponse
      | undefined;
  };

/** @internal */
export type C1ApiAccessreviewV1AccessReviewSetupEntitlementServiceSetCampaignScopeAndEntitlementsRequest$Outbound =
  {
    access_review_id: string;
    AccessReviewSetupEntitlementAndScopeServiceSetRequest?:
      | shared.AccessReviewSetupEntitlementAndScopeServiceSetRequest$Outbound
      | undefined;
  };

/** @internal */
export const C1ApiAccessreviewV1AccessReviewSetupEntitlementServiceSetCampaignScopeAndEntitlementsRequest$outboundSchema:
  z.ZodType<
    C1ApiAccessreviewV1AccessReviewSetupEntitlementServiceSetCampaignScopeAndEntitlementsRequest$Outbound,
    z.ZodTypeDef,
    C1ApiAccessreviewV1AccessReviewSetupEntitlementServiceSetCampaignScopeAndEntitlementsRequest
  > = z.object({
    accessReviewId: z.string(),
    accessReviewSetupEntitlementAndScopeServiceSetRequest: shared
      .AccessReviewSetupEntitlementAndScopeServiceSetRequest$outboundSchema
      .optional(),
  }).transform((v) => {
    return remap$(v, {
      accessReviewId: "access_review_id",
      accessReviewSetupEntitlementAndScopeServiceSetRequest:
        "AccessReviewSetupEntitlementAndScopeServiceSetRequest",
    });
  });

export function c1ApiAccessreviewV1AccessReviewSetupEntitlementServiceSetCampaignScopeAndEntitlementsRequestToJSON(
  c1ApiAccessreviewV1AccessReviewSetupEntitlementServiceSetCampaignScopeAndEntitlementsRequest:
    C1ApiAccessreviewV1AccessReviewSetupEntitlementServiceSetCampaignScopeAndEntitlementsRequest,
): string {
  return JSON.stringify(
    C1ApiAccessreviewV1AccessReviewSetupEntitlementServiceSetCampaignScopeAndEntitlementsRequest$outboundSchema
      .parse(
        c1ApiAccessreviewV1AccessReviewSetupEntitlementServiceSetCampaignScopeAndEntitlementsRequest,
      ),
  );
}

/** @internal */
export const C1ApiAccessreviewV1AccessReviewSetupEntitlementServiceSetCampaignScopeAndEntitlementsResponse$inboundSchema:
  z.ZodType<
    C1ApiAccessreviewV1AccessReviewSetupEntitlementServiceSetCampaignScopeAndEntitlementsResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    ContentType: z.string(),
    StatusCode: z.number().int(),
    RawResponse: z.instanceof(Response),
    AccessReviewSetupEntitlementAndScopeServiceSetResponse: shared
      .AccessReviewSetupEntitlementAndScopeServiceSetResponse$inboundSchema
      .optional(),
  }).transform((v) => {
    return remap$(v, {
      "ContentType": "contentType",
      "StatusCode": "statusCode",
      "RawResponse": "rawResponse",
      "AccessReviewSetupEntitlementAndScopeServiceSetResponse":
        "accessReviewSetupEntitlementAndScopeServiceSetResponse",
    });
  });

export function c1ApiAccessreviewV1AccessReviewSetupEntitlementServiceSetCampaignScopeAndEntitlementsResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  C1ApiAccessreviewV1AccessReviewSetupEntitlementServiceSetCampaignScopeAndEntitlementsResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      C1ApiAccessreviewV1AccessReviewSetupEntitlementServiceSetCampaignScopeAndEntitlementsResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'C1ApiAccessreviewV1AccessReviewSetupEntitlementServiceSetCampaignScopeAndEntitlementsResponse' from JSON`,
  );
}
