/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type C1ApiAppV2AppOwnersGetEntitlementOwnerRequest = {
  appId: string;
  roleSlug: string;
  appEntitlementRefAppId: string;
  appEntitlementRefId: string;
};

export type C1ApiAppV2AppOwnersGetEntitlementOwnerResponse = {
  /**
   * HTTP response content type for this operation
   */
  contentType: string;
  /**
   * HTTP response status code for this operation
   */
  statusCode: number;
  /**
   * Raw HTTP response; suitable for custom response parsing
   */
  rawResponse: Response;
  /**
   * GetEntitlementOwnerResponse is the response for getting an entitlement ownership source.
   */
  getEntitlementOwnerResponse?: shared.GetEntitlementOwnerResponse | undefined;
};

/** @internal */
export type C1ApiAppV2AppOwnersGetEntitlementOwnerRequest$Outbound = {
  app_id: string;
  role_slug: string;
  app_entitlement_ref_app_id: string;
  app_entitlement_ref_id: string;
};

/** @internal */
export const C1ApiAppV2AppOwnersGetEntitlementOwnerRequest$outboundSchema:
  z.ZodType<
    C1ApiAppV2AppOwnersGetEntitlementOwnerRequest$Outbound,
    z.ZodTypeDef,
    C1ApiAppV2AppOwnersGetEntitlementOwnerRequest
  > = z.object({
    appId: z.string(),
    roleSlug: z.string(),
    appEntitlementRefAppId: z.string(),
    appEntitlementRefId: z.string(),
  }).transform((v) => {
    return remap$(v, {
      appId: "app_id",
      roleSlug: "role_slug",
      appEntitlementRefAppId: "app_entitlement_ref_app_id",
      appEntitlementRefId: "app_entitlement_ref_id",
    });
  });

export function c1ApiAppV2AppOwnersGetEntitlementOwnerRequestToJSON(
  c1ApiAppV2AppOwnersGetEntitlementOwnerRequest:
    C1ApiAppV2AppOwnersGetEntitlementOwnerRequest,
): string {
  return JSON.stringify(
    C1ApiAppV2AppOwnersGetEntitlementOwnerRequest$outboundSchema.parse(
      c1ApiAppV2AppOwnersGetEntitlementOwnerRequest,
    ),
  );
}

/** @internal */
export const C1ApiAppV2AppOwnersGetEntitlementOwnerResponse$inboundSchema:
  z.ZodType<
    C1ApiAppV2AppOwnersGetEntitlementOwnerResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    ContentType: z.string(),
    StatusCode: z.number().int(),
    RawResponse: z.instanceof(Response),
    GetEntitlementOwnerResponse: shared
      .GetEntitlementOwnerResponse$inboundSchema.optional(),
  }).transform((v) => {
    return remap$(v, {
      "ContentType": "contentType",
      "StatusCode": "statusCode",
      "RawResponse": "rawResponse",
      "GetEntitlementOwnerResponse": "getEntitlementOwnerResponse",
    });
  });

export function c1ApiAppV2AppOwnersGetEntitlementOwnerResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  C1ApiAppV2AppOwnersGetEntitlementOwnerResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      C1ApiAppV2AppOwnersGetEntitlementOwnerResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'C1ApiAppV2AppOwnersGetEntitlementOwnerResponse' from JSON`,
  );
}
