/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import * as shared from "../shared/index.js";
/** @internal */
export const C1ApiPolicyV1PoliciesUpdateRequest$inboundSchema = z.object({
    id: z.nullable(z.string()),
    UpdatePolicyRequest: shared.UpdatePolicyRequest$inboundSchema.optional(),
}).transform((v) => {
    return remap$(v, {
        "UpdatePolicyRequest": "updatePolicyRequest",
    });
});
/** @internal */
export const C1ApiPolicyV1PoliciesUpdateRequest$outboundSchema = z.object({
    id: z.nullable(z.string()),
    updatePolicyRequest: shared.UpdatePolicyRequest$outboundSchema.optional(),
}).transform((v) => {
    return remap$(v, {
        updatePolicyRequest: "UpdatePolicyRequest",
    });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export var C1ApiPolicyV1PoliciesUpdateRequest$;
(function (C1ApiPolicyV1PoliciesUpdateRequest$) {
    /** @deprecated use `C1ApiPolicyV1PoliciesUpdateRequest$inboundSchema` instead. */
    C1ApiPolicyV1PoliciesUpdateRequest$.inboundSchema = C1ApiPolicyV1PoliciesUpdateRequest$inboundSchema;
    /** @deprecated use `C1ApiPolicyV1PoliciesUpdateRequest$outboundSchema` instead. */
    C1ApiPolicyV1PoliciesUpdateRequest$.outboundSchema = C1ApiPolicyV1PoliciesUpdateRequest$outboundSchema;
})(C1ApiPolicyV1PoliciesUpdateRequest$ || (C1ApiPolicyV1PoliciesUpdateRequest$ = {}));
export function c1ApiPolicyV1PoliciesUpdateRequestToJSON(c1ApiPolicyV1PoliciesUpdateRequest) {
    return JSON.stringify(C1ApiPolicyV1PoliciesUpdateRequest$outboundSchema.parse(c1ApiPolicyV1PoliciesUpdateRequest));
}
export function c1ApiPolicyV1PoliciesUpdateRequestFromJSON(jsonString) {
    return safeParse(jsonString, (x) => C1ApiPolicyV1PoliciesUpdateRequest$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'C1ApiPolicyV1PoliciesUpdateRequest' from JSON`);
}
/** @internal */
export const C1ApiPolicyV1PoliciesUpdateResponse$inboundSchema = z.object({
    ContentType: z.string(),
    StatusCode: z.number().int(),
    RawResponse: z.instanceof(Response),
    UpdatePolicyResponse: shared.UpdatePolicyResponse$inboundSchema.optional(),
}).transform((v) => {
    return remap$(v, {
        "ContentType": "contentType",
        "StatusCode": "statusCode",
        "RawResponse": "rawResponse",
        "UpdatePolicyResponse": "updatePolicyResponse",
    });
});
/** @internal */
export const C1ApiPolicyV1PoliciesUpdateResponse$outboundSchema = z.object({
    contentType: z.string(),
    statusCode: z.number().int(),
    rawResponse: z.instanceof(Response).transform(() => {
        throw new Error("Response cannot be serialized");
    }),
    updatePolicyResponse: shared.UpdatePolicyResponse$outboundSchema.optional(),
}).transform((v) => {
    return remap$(v, {
        contentType: "ContentType",
        statusCode: "StatusCode",
        rawResponse: "RawResponse",
        updatePolicyResponse: "UpdatePolicyResponse",
    });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export var C1ApiPolicyV1PoliciesUpdateResponse$;
(function (C1ApiPolicyV1PoliciesUpdateResponse$) {
    /** @deprecated use `C1ApiPolicyV1PoliciesUpdateResponse$inboundSchema` instead. */
    C1ApiPolicyV1PoliciesUpdateResponse$.inboundSchema = C1ApiPolicyV1PoliciesUpdateResponse$inboundSchema;
    /** @deprecated use `C1ApiPolicyV1PoliciesUpdateResponse$outboundSchema` instead. */
    C1ApiPolicyV1PoliciesUpdateResponse$.outboundSchema = C1ApiPolicyV1PoliciesUpdateResponse$outboundSchema;
})(C1ApiPolicyV1PoliciesUpdateResponse$ || (C1ApiPolicyV1PoliciesUpdateResponse$ = {}));
export function c1ApiPolicyV1PoliciesUpdateResponseToJSON(c1ApiPolicyV1PoliciesUpdateResponse) {
    return JSON.stringify(C1ApiPolicyV1PoliciesUpdateResponse$outboundSchema.parse(c1ApiPolicyV1PoliciesUpdateResponse));
}
export function c1ApiPolicyV1PoliciesUpdateResponseFromJSON(jsonString) {
    return safeParse(jsonString, (x) => C1ApiPolicyV1PoliciesUpdateResponse$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'C1ApiPolicyV1PoliciesUpdateResponse' from JSON`);
}
