/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type C1ApiHooksV1HooksServiceListRequest = {
  pageSize?: number | undefined;
  pageToken?: string | undefined;
};

export type C1ApiHooksV1HooksServiceListResponse = {
  /**
   * HTTP response content type for this operation
   */
  contentType: string;
  /**
   * HTTP response status code for this operation
   */
  statusCode: number;
  /**
   * Raw HTTP response; suitable for custom response parsing
   */
  rawResponse: Response;
  /**
   * Successful response
   */
  hooksServiceListResponse?: shared.HooksServiceListResponse | undefined;
};

/** @internal */
export type C1ApiHooksV1HooksServiceListRequest$Outbound = {
  page_size?: number | undefined;
  page_token?: string | undefined;
};

/** @internal */
export const C1ApiHooksV1HooksServiceListRequest$outboundSchema: z.ZodType<
  C1ApiHooksV1HooksServiceListRequest$Outbound,
  z.ZodTypeDef,
  C1ApiHooksV1HooksServiceListRequest
> = z.object({
  pageSize: z.number().int().optional(),
  pageToken: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    pageSize: "page_size",
    pageToken: "page_token",
  });
});

export function c1ApiHooksV1HooksServiceListRequestToJSON(
  c1ApiHooksV1HooksServiceListRequest: C1ApiHooksV1HooksServiceListRequest,
): string {
  return JSON.stringify(
    C1ApiHooksV1HooksServiceListRequest$outboundSchema.parse(
      c1ApiHooksV1HooksServiceListRequest,
    ),
  );
}

/** @internal */
export const C1ApiHooksV1HooksServiceListResponse$inboundSchema: z.ZodType<
  C1ApiHooksV1HooksServiceListResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  StatusCode: z.number().int(),
  RawResponse: z.instanceof(Response),
  HooksServiceListResponse: shared.HooksServiceListResponse$inboundSchema
    .optional(),
}).transform((v) => {
  return remap$(v, {
    "ContentType": "contentType",
    "StatusCode": "statusCode",
    "RawResponse": "rawResponse",
    "HooksServiceListResponse": "hooksServiceListResponse",
  });
});

export function c1ApiHooksV1HooksServiceListResponseFromJSON(
  jsonString: string,
): SafeParseResult<C1ApiHooksV1HooksServiceListResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      C1ApiHooksV1HooksServiceListResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'C1ApiHooksV1HooksServiceListResponse' from JSON`,
  );
}
