/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type C1ApiRequestcatalogV1RequestCatalogManagementServiceRemoveAppEntitlementsRequest =
  {
    catalogId: string | null;
    requestCatalogManagementServiceRemoveAppEntitlementsRequest?:
      | shared.RequestCatalogManagementServiceRemoveAppEntitlementsRequest
      | undefined;
  };

export type C1ApiRequestcatalogV1RequestCatalogManagementServiceRemoveAppEntitlementsResponse =
  {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
    /**
     * Empty response with a status code indicating success
     */
    requestCatalogManagementServiceRemoveAppEntitlementsResponse?:
      | shared.RequestCatalogManagementServiceRemoveAppEntitlementsResponse
      | undefined;
  };

/** @internal */
export type C1ApiRequestcatalogV1RequestCatalogManagementServiceRemoveAppEntitlementsRequest$Outbound =
  {
    catalog_id: string | null;
    RequestCatalogManagementServiceRemoveAppEntitlementsRequest?:
      | shared.RequestCatalogManagementServiceRemoveAppEntitlementsRequest$Outbound
      | undefined;
  };

/** @internal */
export const C1ApiRequestcatalogV1RequestCatalogManagementServiceRemoveAppEntitlementsRequest$outboundSchema:
  z.ZodType<
    C1ApiRequestcatalogV1RequestCatalogManagementServiceRemoveAppEntitlementsRequest$Outbound,
    z.ZodTypeDef,
    C1ApiRequestcatalogV1RequestCatalogManagementServiceRemoveAppEntitlementsRequest
  > = z.object({
    catalogId: z.nullable(z.string()),
    requestCatalogManagementServiceRemoveAppEntitlementsRequest: shared
      .RequestCatalogManagementServiceRemoveAppEntitlementsRequest$outboundSchema
      .optional(),
  }).transform((v) => {
    return remap$(v, {
      catalogId: "catalog_id",
      requestCatalogManagementServiceRemoveAppEntitlementsRequest:
        "RequestCatalogManagementServiceRemoveAppEntitlementsRequest",
    });
  });

export function c1ApiRequestcatalogV1RequestCatalogManagementServiceRemoveAppEntitlementsRequestToJSON(
  c1ApiRequestcatalogV1RequestCatalogManagementServiceRemoveAppEntitlementsRequest:
    C1ApiRequestcatalogV1RequestCatalogManagementServiceRemoveAppEntitlementsRequest,
): string {
  return JSON.stringify(
    C1ApiRequestcatalogV1RequestCatalogManagementServiceRemoveAppEntitlementsRequest$outboundSchema
      .parse(
        c1ApiRequestcatalogV1RequestCatalogManagementServiceRemoveAppEntitlementsRequest,
      ),
  );
}

/** @internal */
export const C1ApiRequestcatalogV1RequestCatalogManagementServiceRemoveAppEntitlementsResponse$inboundSchema:
  z.ZodType<
    C1ApiRequestcatalogV1RequestCatalogManagementServiceRemoveAppEntitlementsResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    ContentType: z.string(),
    StatusCode: z.number().int(),
    RawResponse: z.instanceof(Response),
    RequestCatalogManagementServiceRemoveAppEntitlementsResponse: shared
      .RequestCatalogManagementServiceRemoveAppEntitlementsResponse$inboundSchema
      .optional(),
  }).transform((v) => {
    return remap$(v, {
      "ContentType": "contentType",
      "StatusCode": "statusCode",
      "RawResponse": "rawResponse",
      "RequestCatalogManagementServiceRemoveAppEntitlementsResponse":
        "requestCatalogManagementServiceRemoveAppEntitlementsResponse",
    });
  });

export function c1ApiRequestcatalogV1RequestCatalogManagementServiceRemoveAppEntitlementsResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  C1ApiRequestcatalogV1RequestCatalogManagementServiceRemoveAppEntitlementsResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      C1ApiRequestcatalogV1RequestCatalogManagementServiceRemoveAppEntitlementsResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'C1ApiRequestcatalogV1RequestCatalogManagementServiceRemoveAppEntitlementsResponse' from JSON`,
  );
}
