/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type C1ApiStepupV1StepUpProviderServiceUpdateRequest = {
  id: string | null;
  updateStepUpProviderRequest?: shared.UpdateStepUpProviderRequest | undefined;
};

export type C1ApiStepupV1StepUpProviderServiceUpdateResponse = {
  /**
   * HTTP response content type for this operation
   */
  contentType: string;
  /**
   * HTTP response status code for this operation
   */
  statusCode: number;
  /**
   * Raw HTTP response; suitable for custom response parsing
   */
  rawResponse: Response;
  /**
   * Successful response
   */
  updateStepUpProviderResponse?:
    | shared.UpdateStepUpProviderResponse
    | undefined;
};

/** @internal */
export const C1ApiStepupV1StepUpProviderServiceUpdateRequest$inboundSchema:
  z.ZodType<
    C1ApiStepupV1StepUpProviderServiceUpdateRequest,
    z.ZodTypeDef,
    unknown
  > = z.object({
    id: z.nullable(z.string()),
    UpdateStepUpProviderRequest: shared
      .UpdateStepUpProviderRequest$inboundSchema.optional(),
  }).transform((v) => {
    return remap$(v, {
      "UpdateStepUpProviderRequest": "updateStepUpProviderRequest",
    });
  });

/** @internal */
export type C1ApiStepupV1StepUpProviderServiceUpdateRequest$Outbound = {
  id: string | null;
  UpdateStepUpProviderRequest?:
    | shared.UpdateStepUpProviderRequest$Outbound
    | undefined;
};

/** @internal */
export const C1ApiStepupV1StepUpProviderServiceUpdateRequest$outboundSchema:
  z.ZodType<
    C1ApiStepupV1StepUpProviderServiceUpdateRequest$Outbound,
    z.ZodTypeDef,
    C1ApiStepupV1StepUpProviderServiceUpdateRequest
  > = z.object({
    id: z.nullable(z.string()),
    updateStepUpProviderRequest: shared
      .UpdateStepUpProviderRequest$outboundSchema.optional(),
  }).transform((v) => {
    return remap$(v, {
      updateStepUpProviderRequest: "UpdateStepUpProviderRequest",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace C1ApiStepupV1StepUpProviderServiceUpdateRequest$ {
  /** @deprecated use `C1ApiStepupV1StepUpProviderServiceUpdateRequest$inboundSchema` instead. */
  export const inboundSchema =
    C1ApiStepupV1StepUpProviderServiceUpdateRequest$inboundSchema;
  /** @deprecated use `C1ApiStepupV1StepUpProviderServiceUpdateRequest$outboundSchema` instead. */
  export const outboundSchema =
    C1ApiStepupV1StepUpProviderServiceUpdateRequest$outboundSchema;
  /** @deprecated use `C1ApiStepupV1StepUpProviderServiceUpdateRequest$Outbound` instead. */
  export type Outbound =
    C1ApiStepupV1StepUpProviderServiceUpdateRequest$Outbound;
}

export function c1ApiStepupV1StepUpProviderServiceUpdateRequestToJSON(
  c1ApiStepupV1StepUpProviderServiceUpdateRequest:
    C1ApiStepupV1StepUpProviderServiceUpdateRequest,
): string {
  return JSON.stringify(
    C1ApiStepupV1StepUpProviderServiceUpdateRequest$outboundSchema.parse(
      c1ApiStepupV1StepUpProviderServiceUpdateRequest,
    ),
  );
}

export function c1ApiStepupV1StepUpProviderServiceUpdateRequestFromJSON(
  jsonString: string,
): SafeParseResult<
  C1ApiStepupV1StepUpProviderServiceUpdateRequest,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      C1ApiStepupV1StepUpProviderServiceUpdateRequest$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'C1ApiStepupV1StepUpProviderServiceUpdateRequest' from JSON`,
  );
}

/** @internal */
export const C1ApiStepupV1StepUpProviderServiceUpdateResponse$inboundSchema:
  z.ZodType<
    C1ApiStepupV1StepUpProviderServiceUpdateResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    ContentType: z.string(),
    StatusCode: z.number().int(),
    RawResponse: z.instanceof(Response),
    UpdateStepUpProviderResponse: shared
      .UpdateStepUpProviderResponse$inboundSchema.optional(),
  }).transform((v) => {
    return remap$(v, {
      "ContentType": "contentType",
      "StatusCode": "statusCode",
      "RawResponse": "rawResponse",
      "UpdateStepUpProviderResponse": "updateStepUpProviderResponse",
    });
  });

/** @internal */
export type C1ApiStepupV1StepUpProviderServiceUpdateResponse$Outbound = {
  ContentType: string;
  StatusCode: number;
  RawResponse: never;
  UpdateStepUpProviderResponse?:
    | shared.UpdateStepUpProviderResponse$Outbound
    | undefined;
};

/** @internal */
export const C1ApiStepupV1StepUpProviderServiceUpdateResponse$outboundSchema:
  z.ZodType<
    C1ApiStepupV1StepUpProviderServiceUpdateResponse$Outbound,
    z.ZodTypeDef,
    C1ApiStepupV1StepUpProviderServiceUpdateResponse
  > = z.object({
    contentType: z.string(),
    statusCode: z.number().int(),
    rawResponse: z.instanceof(Response).transform(() => {
      throw new Error("Response cannot be serialized");
    }),
    updateStepUpProviderResponse: shared
      .UpdateStepUpProviderResponse$outboundSchema.optional(),
  }).transform((v) => {
    return remap$(v, {
      contentType: "ContentType",
      statusCode: "StatusCode",
      rawResponse: "RawResponse",
      updateStepUpProviderResponse: "UpdateStepUpProviderResponse",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace C1ApiStepupV1StepUpProviderServiceUpdateResponse$ {
  /** @deprecated use `C1ApiStepupV1StepUpProviderServiceUpdateResponse$inboundSchema` instead. */
  export const inboundSchema =
    C1ApiStepupV1StepUpProviderServiceUpdateResponse$inboundSchema;
  /** @deprecated use `C1ApiStepupV1StepUpProviderServiceUpdateResponse$outboundSchema` instead. */
  export const outboundSchema =
    C1ApiStepupV1StepUpProviderServiceUpdateResponse$outboundSchema;
  /** @deprecated use `C1ApiStepupV1StepUpProviderServiceUpdateResponse$Outbound` instead. */
  export type Outbound =
    C1ApiStepupV1StepUpProviderServiceUpdateResponse$Outbound;
}

export function c1ApiStepupV1StepUpProviderServiceUpdateResponseToJSON(
  c1ApiStepupV1StepUpProviderServiceUpdateResponse:
    C1ApiStepupV1StepUpProviderServiceUpdateResponse,
): string {
  return JSON.stringify(
    C1ApiStepupV1StepUpProviderServiceUpdateResponse$outboundSchema.parse(
      c1ApiStepupV1StepUpProviderServiceUpdateResponse,
    ),
  );
}

export function c1ApiStepupV1StepUpProviderServiceUpdateResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  C1ApiStepupV1StepUpProviderServiceUpdateResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      C1ApiStepupV1StepUpProviderServiceUpdateResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'C1ApiStepupV1StepUpProviderServiceUpdateResponse' from JSON`,
  );
}
