/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type C1ApiAppV1AppResourceOwnersListOwnerIDsRequest = {
  appId: string | null;
  resourceTypeId: string | null;
  resourceId: string | null;
};

export type C1ApiAppV1AppResourceOwnersListOwnerIDsResponse = {
  /**
   * HTTP response content type for this operation
   */
  contentType: string;
  /**
   * HTTP response status code for this operation
   */
  statusCode: number;
  /**
   * Raw HTTP response; suitable for custom response parsing
   */
  rawResponse: Response;
  /**
   * The response message for listing app resource owners IDs.
   */
  listAppResourceOwnerIDsResponse?:
    | shared.ListAppResourceOwnerIDsResponse
    | undefined;
};

/** @internal */
export type C1ApiAppV1AppResourceOwnersListOwnerIDsRequest$Outbound = {
  app_id: string | null;
  resource_type_id: string | null;
  resource_id: string | null;
};

/** @internal */
export const C1ApiAppV1AppResourceOwnersListOwnerIDsRequest$outboundSchema:
  z.ZodType<
    C1ApiAppV1AppResourceOwnersListOwnerIDsRequest$Outbound,
    z.ZodTypeDef,
    C1ApiAppV1AppResourceOwnersListOwnerIDsRequest
  > = z.object({
    appId: z.nullable(z.string()),
    resourceTypeId: z.nullable(z.string()),
    resourceId: z.nullable(z.string()),
  }).transform((v) => {
    return remap$(v, {
      appId: "app_id",
      resourceTypeId: "resource_type_id",
      resourceId: "resource_id",
    });
  });

export function c1ApiAppV1AppResourceOwnersListOwnerIDsRequestToJSON(
  c1ApiAppV1AppResourceOwnersListOwnerIDsRequest:
    C1ApiAppV1AppResourceOwnersListOwnerIDsRequest,
): string {
  return JSON.stringify(
    C1ApiAppV1AppResourceOwnersListOwnerIDsRequest$outboundSchema.parse(
      c1ApiAppV1AppResourceOwnersListOwnerIDsRequest,
    ),
  );
}

/** @internal */
export const C1ApiAppV1AppResourceOwnersListOwnerIDsResponse$inboundSchema:
  z.ZodType<
    C1ApiAppV1AppResourceOwnersListOwnerIDsResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    ContentType: z.string(),
    StatusCode: z.number().int(),
    RawResponse: z.instanceof(Response),
    ListAppResourceOwnerIDsResponse: shared
      .ListAppResourceOwnerIDsResponse$inboundSchema.optional(),
  }).transform((v) => {
    return remap$(v, {
      "ContentType": "contentType",
      "StatusCode": "statusCode",
      "RawResponse": "rawResponse",
      "ListAppResourceOwnerIDsResponse": "listAppResourceOwnerIDsResponse",
    });
  });

export function c1ApiAppV1AppResourceOwnersListOwnerIDsResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  C1ApiAppV1AppResourceOwnersListOwnerIDsResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      C1ApiAppV1AppResourceOwnersListOwnerIDsResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'C1ApiAppV1AppResourceOwnersListOwnerIDsResponse' from JSON`,
  );
}
