/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type C1ApiFunctionsV1FunctionsServiceUpdateFunctionResponse = {
  /**
   * HTTP response content type for this operation
   */
  contentType: string;
  /**
   * HTTP response status code for this operation
   */
  statusCode: number;
  /**
   * Raw HTTP response; suitable for custom response parsing
   */
  rawResponse: Response;
  /**
   * Successful response
   */
  functionsServiceUpdateFunctionResponse?:
    | shared.FunctionsServiceUpdateFunctionResponse
    | undefined;
};

/** @internal */
export const C1ApiFunctionsV1FunctionsServiceUpdateFunctionResponse$inboundSchema:
  z.ZodType<
    C1ApiFunctionsV1FunctionsServiceUpdateFunctionResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    ContentType: z.string(),
    StatusCode: z.number().int(),
    RawResponse: z.instanceof(Response),
    FunctionsServiceUpdateFunctionResponse: shared
      .FunctionsServiceUpdateFunctionResponse$inboundSchema.optional(),
  }).transform((v) => {
    return remap$(v, {
      "ContentType": "contentType",
      "StatusCode": "statusCode",
      "RawResponse": "rawResponse",
      "FunctionsServiceUpdateFunctionResponse":
        "functionsServiceUpdateFunctionResponse",
    });
  });

export function c1ApiFunctionsV1FunctionsServiceUpdateFunctionResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  C1ApiFunctionsV1FunctionsServiceUpdateFunctionResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      C1ApiFunctionsV1FunctionsServiceUpdateFunctionResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'C1ApiFunctionsV1FunctionsServiceUpdateFunctionResponse' from JSON`,
  );
}
