/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import * as shared from "../shared/index.js";
/** @internal */
export const C1ApiPolicyV1PoliciesCreateResponse$inboundSchema = z.object({
    ContentType: z.string(),
    StatusCode: z.number().int(),
    RawResponse: z.instanceof(Response),
    CreatePolicyResponse: shared.CreatePolicyResponse$inboundSchema.optional(),
}).transform((v) => {
    return remap$(v, {
        "ContentType": "contentType",
        "StatusCode": "statusCode",
        "RawResponse": "rawResponse",
        "CreatePolicyResponse": "createPolicyResponse",
    });
});
/** @internal */
export const C1ApiPolicyV1PoliciesCreateResponse$outboundSchema = z.object({
    contentType: z.string(),
    statusCode: z.number().int(),
    rawResponse: z.instanceof(Response).transform(() => {
        throw new Error("Response cannot be serialized");
    }),
    createPolicyResponse: shared.CreatePolicyResponse$outboundSchema.optional(),
}).transform((v) => {
    return remap$(v, {
        contentType: "ContentType",
        statusCode: "StatusCode",
        rawResponse: "RawResponse",
        createPolicyResponse: "CreatePolicyResponse",
    });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export var C1ApiPolicyV1PoliciesCreateResponse$;
(function (C1ApiPolicyV1PoliciesCreateResponse$) {
    /** @deprecated use `C1ApiPolicyV1PoliciesCreateResponse$inboundSchema` instead. */
    C1ApiPolicyV1PoliciesCreateResponse$.inboundSchema = C1ApiPolicyV1PoliciesCreateResponse$inboundSchema;
    /** @deprecated use `C1ApiPolicyV1PoliciesCreateResponse$outboundSchema` instead. */
    C1ApiPolicyV1PoliciesCreateResponse$.outboundSchema = C1ApiPolicyV1PoliciesCreateResponse$outboundSchema;
})(C1ApiPolicyV1PoliciesCreateResponse$ || (C1ApiPolicyV1PoliciesCreateResponse$ = {}));
export function c1ApiPolicyV1PoliciesCreateResponseToJSON(c1ApiPolicyV1PoliciesCreateResponse) {
    return JSON.stringify(C1ApiPolicyV1PoliciesCreateResponse$outboundSchema.parse(c1ApiPolicyV1PoliciesCreateResponse));
}
export function c1ApiPolicyV1PoliciesCreateResponseFromJSON(jsonString) {
    return safeParse(jsonString, (x) => C1ApiPolicyV1PoliciesCreateResponse$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'C1ApiPolicyV1PoliciesCreateResponse' from JSON`);
}
