/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type C1ApiAppV1AppEntitlementOwnersRemoveRequest = {
  appId: string | null;
  entitlementId: string | null;
  userId: string | null;
  removeAppEntitlementOwnerRequest?:
    | shared.RemoveAppEntitlementOwnerRequest
    | undefined;
};

export type C1ApiAppV1AppEntitlementOwnersRemoveResponse = {
  /**
   * HTTP response content type for this operation
   */
  contentType: string;
  /**
   * HTTP response status code for this operation
   */
  statusCode: number;
  /**
   * Raw HTTP response; suitable for custom response parsing
   */
  rawResponse: Response;
  /**
   * The empty response message for removing an app entitlement owner.
   */
  removeAppEntitlementOwnerResponse?:
    | shared.RemoveAppEntitlementOwnerResponse
    | undefined;
};

/** @internal */
export const C1ApiAppV1AppEntitlementOwnersRemoveRequest$inboundSchema:
  z.ZodType<
    C1ApiAppV1AppEntitlementOwnersRemoveRequest,
    z.ZodTypeDef,
    unknown
  > = z.object({
    app_id: z.nullable(z.string()),
    entitlement_id: z.nullable(z.string()),
    user_id: z.nullable(z.string()),
    RemoveAppEntitlementOwnerRequest: shared
      .RemoveAppEntitlementOwnerRequest$inboundSchema.optional(),
  }).transform((v) => {
    return remap$(v, {
      "app_id": "appId",
      "entitlement_id": "entitlementId",
      "user_id": "userId",
      "RemoveAppEntitlementOwnerRequest": "removeAppEntitlementOwnerRequest",
    });
  });

/** @internal */
export type C1ApiAppV1AppEntitlementOwnersRemoveRequest$Outbound = {
  app_id: string | null;
  entitlement_id: string | null;
  user_id: string | null;
  RemoveAppEntitlementOwnerRequest?:
    | shared.RemoveAppEntitlementOwnerRequest$Outbound
    | undefined;
};

/** @internal */
export const C1ApiAppV1AppEntitlementOwnersRemoveRequest$outboundSchema:
  z.ZodType<
    C1ApiAppV1AppEntitlementOwnersRemoveRequest$Outbound,
    z.ZodTypeDef,
    C1ApiAppV1AppEntitlementOwnersRemoveRequest
  > = z.object({
    appId: z.nullable(z.string()),
    entitlementId: z.nullable(z.string()),
    userId: z.nullable(z.string()),
    removeAppEntitlementOwnerRequest: shared
      .RemoveAppEntitlementOwnerRequest$outboundSchema.optional(),
  }).transform((v) => {
    return remap$(v, {
      appId: "app_id",
      entitlementId: "entitlement_id",
      userId: "user_id",
      removeAppEntitlementOwnerRequest: "RemoveAppEntitlementOwnerRequest",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace C1ApiAppV1AppEntitlementOwnersRemoveRequest$ {
  /** @deprecated use `C1ApiAppV1AppEntitlementOwnersRemoveRequest$inboundSchema` instead. */
  export const inboundSchema =
    C1ApiAppV1AppEntitlementOwnersRemoveRequest$inboundSchema;
  /** @deprecated use `C1ApiAppV1AppEntitlementOwnersRemoveRequest$outboundSchema` instead. */
  export const outboundSchema =
    C1ApiAppV1AppEntitlementOwnersRemoveRequest$outboundSchema;
  /** @deprecated use `C1ApiAppV1AppEntitlementOwnersRemoveRequest$Outbound` instead. */
  export type Outbound = C1ApiAppV1AppEntitlementOwnersRemoveRequest$Outbound;
}

export function c1ApiAppV1AppEntitlementOwnersRemoveRequestToJSON(
  c1ApiAppV1AppEntitlementOwnersRemoveRequest:
    C1ApiAppV1AppEntitlementOwnersRemoveRequest,
): string {
  return JSON.stringify(
    C1ApiAppV1AppEntitlementOwnersRemoveRequest$outboundSchema.parse(
      c1ApiAppV1AppEntitlementOwnersRemoveRequest,
    ),
  );
}

export function c1ApiAppV1AppEntitlementOwnersRemoveRequestFromJSON(
  jsonString: string,
): SafeParseResult<
  C1ApiAppV1AppEntitlementOwnersRemoveRequest,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      C1ApiAppV1AppEntitlementOwnersRemoveRequest$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'C1ApiAppV1AppEntitlementOwnersRemoveRequest' from JSON`,
  );
}

/** @internal */
export const C1ApiAppV1AppEntitlementOwnersRemoveResponse$inboundSchema:
  z.ZodType<
    C1ApiAppV1AppEntitlementOwnersRemoveResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    ContentType: z.string(),
    StatusCode: z.number().int(),
    RawResponse: z.instanceof(Response),
    RemoveAppEntitlementOwnerResponse: shared
      .RemoveAppEntitlementOwnerResponse$inboundSchema.optional(),
  }).transform((v) => {
    return remap$(v, {
      "ContentType": "contentType",
      "StatusCode": "statusCode",
      "RawResponse": "rawResponse",
      "RemoveAppEntitlementOwnerResponse": "removeAppEntitlementOwnerResponse",
    });
  });

/** @internal */
export type C1ApiAppV1AppEntitlementOwnersRemoveResponse$Outbound = {
  ContentType: string;
  StatusCode: number;
  RawResponse: never;
  RemoveAppEntitlementOwnerResponse?:
    | shared.RemoveAppEntitlementOwnerResponse$Outbound
    | undefined;
};

/** @internal */
export const C1ApiAppV1AppEntitlementOwnersRemoveResponse$outboundSchema:
  z.ZodType<
    C1ApiAppV1AppEntitlementOwnersRemoveResponse$Outbound,
    z.ZodTypeDef,
    C1ApiAppV1AppEntitlementOwnersRemoveResponse
  > = z.object({
    contentType: z.string(),
    statusCode: z.number().int(),
    rawResponse: z.instanceof(Response).transform(() => {
      throw new Error("Response cannot be serialized");
    }),
    removeAppEntitlementOwnerResponse: shared
      .RemoveAppEntitlementOwnerResponse$outboundSchema.optional(),
  }).transform((v) => {
    return remap$(v, {
      contentType: "ContentType",
      statusCode: "StatusCode",
      rawResponse: "RawResponse",
      removeAppEntitlementOwnerResponse: "RemoveAppEntitlementOwnerResponse",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace C1ApiAppV1AppEntitlementOwnersRemoveResponse$ {
  /** @deprecated use `C1ApiAppV1AppEntitlementOwnersRemoveResponse$inboundSchema` instead. */
  export const inboundSchema =
    C1ApiAppV1AppEntitlementOwnersRemoveResponse$inboundSchema;
  /** @deprecated use `C1ApiAppV1AppEntitlementOwnersRemoveResponse$outboundSchema` instead. */
  export const outboundSchema =
    C1ApiAppV1AppEntitlementOwnersRemoveResponse$outboundSchema;
  /** @deprecated use `C1ApiAppV1AppEntitlementOwnersRemoveResponse$Outbound` instead. */
  export type Outbound = C1ApiAppV1AppEntitlementOwnersRemoveResponse$Outbound;
}

export function c1ApiAppV1AppEntitlementOwnersRemoveResponseToJSON(
  c1ApiAppV1AppEntitlementOwnersRemoveResponse:
    C1ApiAppV1AppEntitlementOwnersRemoveResponse,
): string {
  return JSON.stringify(
    C1ApiAppV1AppEntitlementOwnersRemoveResponse$outboundSchema.parse(
      c1ApiAppV1AppEntitlementOwnersRemoveResponse,
    ),
  );
}

export function c1ApiAppV1AppEntitlementOwnersRemoveResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  C1ApiAppV1AppEntitlementOwnersRemoveResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      C1ApiAppV1AppEntitlementOwnersRemoveResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'C1ApiAppV1AppEntitlementOwnersRemoveResponse' from JSON`,
  );
}
