/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type C1ApiAutomationsV1AutomationExecutionServiceListAutomationExecutionsResponse =
  {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
    /**
     * Successful response
     */
    listAutomationExecutionsResponse?:
      | shared.ListAutomationExecutionsResponse
      | undefined;
  };

/** @internal */
export const C1ApiAutomationsV1AutomationExecutionServiceListAutomationExecutionsResponse$inboundSchema:
  z.ZodType<
    C1ApiAutomationsV1AutomationExecutionServiceListAutomationExecutionsResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    ContentType: z.string(),
    StatusCode: z.number().int(),
    RawResponse: z.instanceof(Response),
    ListAutomationExecutionsResponse: shared
      .ListAutomationExecutionsResponse$inboundSchema.optional(),
  }).transform((v) => {
    return remap$(v, {
      "ContentType": "contentType",
      "StatusCode": "statusCode",
      "RawResponse": "rawResponse",
      "ListAutomationExecutionsResponse": "listAutomationExecutionsResponse",
    });
  });

export function c1ApiAutomationsV1AutomationExecutionServiceListAutomationExecutionsResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  C1ApiAutomationsV1AutomationExecutionServiceListAutomationExecutionsResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      C1ApiAutomationsV1AutomationExecutionServiceListAutomationExecutionsResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'C1ApiAutomationsV1AutomationExecutionServiceListAutomationExecutionsResponse' from JSON`,
  );
}
