/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type C1ApiAutomationsV1AutomationServiceListAutomationsResponse = {
  /**
   * HTTP response content type for this operation
   */
  contentType: string;
  /**
   * HTTP response status code for this operation
   */
  statusCode: number;
  /**
   * Raw HTTP response; suitable for custom response parsing
   */
  rawResponse: Response;
  /**
   * Successful response
   */
  listAutomationsResponse?: shared.ListAutomationsResponse | undefined;
};

/** @internal */
export const C1ApiAutomationsV1AutomationServiceListAutomationsResponse$inboundSchema:
  z.ZodType<
    C1ApiAutomationsV1AutomationServiceListAutomationsResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    ContentType: z.string(),
    StatusCode: z.number().int(),
    RawResponse: z.instanceof(Response),
    ListAutomationsResponse: shared.ListAutomationsResponse$inboundSchema
      .optional(),
  }).transform((v) => {
    return remap$(v, {
      "ContentType": "contentType",
      "StatusCode": "statusCode",
      "RawResponse": "rawResponse",
      "ListAutomationsResponse": "listAutomationsResponse",
    });
  });

/** @internal */
export type C1ApiAutomationsV1AutomationServiceListAutomationsResponse$Outbound =
  {
    ContentType: string;
    StatusCode: number;
    RawResponse: never;
    ListAutomationsResponse?:
      | shared.ListAutomationsResponse$Outbound
      | undefined;
  };

/** @internal */
export const C1ApiAutomationsV1AutomationServiceListAutomationsResponse$outboundSchema:
  z.ZodType<
    C1ApiAutomationsV1AutomationServiceListAutomationsResponse$Outbound,
    z.ZodTypeDef,
    C1ApiAutomationsV1AutomationServiceListAutomationsResponse
  > = z.object({
    contentType: z.string(),
    statusCode: z.number().int(),
    rawResponse: z.instanceof(Response).transform(() => {
      throw new Error("Response cannot be serialized");
    }),
    listAutomationsResponse: shared.ListAutomationsResponse$outboundSchema
      .optional(),
  }).transform((v) => {
    return remap$(v, {
      contentType: "ContentType",
      statusCode: "StatusCode",
      rawResponse: "RawResponse",
      listAutomationsResponse: "ListAutomationsResponse",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace C1ApiAutomationsV1AutomationServiceListAutomationsResponse$ {
  /** @deprecated use `C1ApiAutomationsV1AutomationServiceListAutomationsResponse$inboundSchema` instead. */
  export const inboundSchema =
    C1ApiAutomationsV1AutomationServiceListAutomationsResponse$inboundSchema;
  /** @deprecated use `C1ApiAutomationsV1AutomationServiceListAutomationsResponse$outboundSchema` instead. */
  export const outboundSchema =
    C1ApiAutomationsV1AutomationServiceListAutomationsResponse$outboundSchema;
  /** @deprecated use `C1ApiAutomationsV1AutomationServiceListAutomationsResponse$Outbound` instead. */
  export type Outbound =
    C1ApiAutomationsV1AutomationServiceListAutomationsResponse$Outbound;
}

export function c1ApiAutomationsV1AutomationServiceListAutomationsResponseToJSON(
  c1ApiAutomationsV1AutomationServiceListAutomationsResponse:
    C1ApiAutomationsV1AutomationServiceListAutomationsResponse,
): string {
  return JSON.stringify(
    C1ApiAutomationsV1AutomationServiceListAutomationsResponse$outboundSchema
      .parse(c1ApiAutomationsV1AutomationServiceListAutomationsResponse),
  );
}

export function c1ApiAutomationsV1AutomationServiceListAutomationsResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  C1ApiAutomationsV1AutomationServiceListAutomationsResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      C1ApiAutomationsV1AutomationServiceListAutomationsResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'C1ApiAutomationsV1AutomationServiceListAutomationsResponse' from JSON`,
  );
}
