/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type C1ApiWebhooksV1WebhooksServiceDeleteRequest = {
  id: string | null;
  webhooksServiceDeleteRequest?:
    | shared.WebhooksServiceDeleteRequest
    | undefined;
};

export type C1ApiWebhooksV1WebhooksServiceDeleteResponse = {
  /**
   * HTTP response content type for this operation
   */
  contentType: string;
  /**
   * HTTP response status code for this operation
   */
  statusCode: number;
  /**
   * Raw HTTP response; suitable for custom response parsing
   */
  rawResponse: Response;
  /**
   * Empty response body. Status code indicates success.
   */
  webhooksServiceDeleteResponse?:
    | shared.WebhooksServiceDeleteResponse
    | undefined;
};

/** @internal */
export type C1ApiWebhooksV1WebhooksServiceDeleteRequest$Outbound = {
  id: string | null;
  WebhooksServiceDeleteRequest?:
    | shared.WebhooksServiceDeleteRequest$Outbound
    | undefined;
};

/** @internal */
export const C1ApiWebhooksV1WebhooksServiceDeleteRequest$outboundSchema:
  z.ZodType<
    C1ApiWebhooksV1WebhooksServiceDeleteRequest$Outbound,
    z.ZodTypeDef,
    C1ApiWebhooksV1WebhooksServiceDeleteRequest
  > = z.object({
    id: z.nullable(z.string()),
    webhooksServiceDeleteRequest: shared
      .WebhooksServiceDeleteRequest$outboundSchema.optional(),
  }).transform((v) => {
    return remap$(v, {
      webhooksServiceDeleteRequest: "WebhooksServiceDeleteRequest",
    });
  });

export function c1ApiWebhooksV1WebhooksServiceDeleteRequestToJSON(
  c1ApiWebhooksV1WebhooksServiceDeleteRequest:
    C1ApiWebhooksV1WebhooksServiceDeleteRequest,
): string {
  return JSON.stringify(
    C1ApiWebhooksV1WebhooksServiceDeleteRequest$outboundSchema.parse(
      c1ApiWebhooksV1WebhooksServiceDeleteRequest,
    ),
  );
}

/** @internal */
export const C1ApiWebhooksV1WebhooksServiceDeleteResponse$inboundSchema:
  z.ZodType<
    C1ApiWebhooksV1WebhooksServiceDeleteResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    ContentType: z.string(),
    StatusCode: z.number().int(),
    RawResponse: z.instanceof(Response),
    WebhooksServiceDeleteResponse: shared
      .WebhooksServiceDeleteResponse$inboundSchema.optional(),
  }).transform((v) => {
    return remap$(v, {
      "ContentType": "contentType",
      "StatusCode": "statusCode",
      "RawResponse": "rawResponse",
      "WebhooksServiceDeleteResponse": "webhooksServiceDeleteResponse",
    });
  });

export function c1ApiWebhooksV1WebhooksServiceDeleteResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  C1ApiWebhooksV1WebhooksServiceDeleteResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      C1ApiWebhooksV1WebhooksServiceDeleteResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'C1ApiWebhooksV1WebhooksServiceDeleteResponse' from JSON`,
  );
}
