/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type C1ApiAppV2AppResourceOwnersV2CreateUserOwnerRequest = {
  appId: string;
  resourceTypeId: string;
  resourceId: string;
  roleSlug: string;
  userRefId: string;
  createAppResourceUserOwnerRequest?:
    | shared.CreateAppResourceUserOwnerRequest
    | undefined;
};

export type C1ApiAppV2AppResourceOwnersV2CreateUserOwnerResponse = {
  /**
   * HTTP response content type for this operation
   */
  contentType: string;
  /**
   * HTTP response status code for this operation
   */
  statusCode: number;
  /**
   * Raw HTTP response; suitable for custom response parsing
   */
  rawResponse: Response;
  /**
   * CreateAppResourceUserOwnerResponse is the response for creating a user ownership source on a resource.
   */
  createAppResourceUserOwnerResponse?:
    | shared.CreateAppResourceUserOwnerResponse
    | undefined;
};

/** @internal */
export type C1ApiAppV2AppResourceOwnersV2CreateUserOwnerRequest$Outbound = {
  app_id: string;
  resource_type_id: string;
  resource_id: string;
  role_slug: string;
  user_ref_id: string;
  CreateAppResourceUserOwnerRequest?:
    | shared.CreateAppResourceUserOwnerRequest$Outbound
    | undefined;
};

/** @internal */
export const C1ApiAppV2AppResourceOwnersV2CreateUserOwnerRequest$outboundSchema:
  z.ZodType<
    C1ApiAppV2AppResourceOwnersV2CreateUserOwnerRequest$Outbound,
    z.ZodTypeDef,
    C1ApiAppV2AppResourceOwnersV2CreateUserOwnerRequest
  > = z.object({
    appId: z.string(),
    resourceTypeId: z.string(),
    resourceId: z.string(),
    roleSlug: z.string(),
    userRefId: z.string(),
    createAppResourceUserOwnerRequest: shared
      .CreateAppResourceUserOwnerRequest$outboundSchema.optional(),
  }).transform((v) => {
    return remap$(v, {
      appId: "app_id",
      resourceTypeId: "resource_type_id",
      resourceId: "resource_id",
      roleSlug: "role_slug",
      userRefId: "user_ref_id",
      createAppResourceUserOwnerRequest: "CreateAppResourceUserOwnerRequest",
    });
  });

export function c1ApiAppV2AppResourceOwnersV2CreateUserOwnerRequestToJSON(
  c1ApiAppV2AppResourceOwnersV2CreateUserOwnerRequest:
    C1ApiAppV2AppResourceOwnersV2CreateUserOwnerRequest,
): string {
  return JSON.stringify(
    C1ApiAppV2AppResourceOwnersV2CreateUserOwnerRequest$outboundSchema.parse(
      c1ApiAppV2AppResourceOwnersV2CreateUserOwnerRequest,
    ),
  );
}

/** @internal */
export const C1ApiAppV2AppResourceOwnersV2CreateUserOwnerResponse$inboundSchema:
  z.ZodType<
    C1ApiAppV2AppResourceOwnersV2CreateUserOwnerResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    ContentType: z.string(),
    StatusCode: z.number().int(),
    RawResponse: z.instanceof(Response),
    CreateAppResourceUserOwnerResponse: shared
      .CreateAppResourceUserOwnerResponse$inboundSchema.optional(),
  }).transform((v) => {
    return remap$(v, {
      "ContentType": "contentType",
      "StatusCode": "statusCode",
      "RawResponse": "rawResponse",
      "CreateAppResourceUserOwnerResponse":
        "createAppResourceUserOwnerResponse",
    });
  });

export function c1ApiAppV2AppResourceOwnersV2CreateUserOwnerResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  C1ApiAppV2AppResourceOwnersV2CreateUserOwnerResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      C1ApiAppV2AppResourceOwnersV2CreateUserOwnerResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'C1ApiAppV2AppResourceOwnersV2CreateUserOwnerResponse' from JSON`,
  );
}
