/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type C1ApiFunctionsV1FunctionsServiceCreateInitialCommitRequest = {
  functionId: string | null;
  functionsServiceCreateInitialCommitRequest?:
    | shared.FunctionsServiceCreateInitialCommitRequest
    | undefined;
};

export type C1ApiFunctionsV1FunctionsServiceCreateInitialCommitResponse = {
  /**
   * HTTP response content type for this operation
   */
  contentType: string;
  /**
   * HTTP response status code for this operation
   */
  statusCode: number;
  /**
   * Raw HTTP response; suitable for custom response parsing
   */
  rawResponse: Response;
  /**
   * Successful response
   */
  functionsServiceCreateInitialCommitResponse?:
    | shared.FunctionsServiceCreateInitialCommitResponse
    | undefined;
};

/** @internal */
export type C1ApiFunctionsV1FunctionsServiceCreateInitialCommitRequest$Outbound =
  {
    function_id: string | null;
    FunctionsServiceCreateInitialCommitRequest?:
      | shared.FunctionsServiceCreateInitialCommitRequest$Outbound
      | undefined;
  };

/** @internal */
export const C1ApiFunctionsV1FunctionsServiceCreateInitialCommitRequest$outboundSchema:
  z.ZodType<
    C1ApiFunctionsV1FunctionsServiceCreateInitialCommitRequest$Outbound,
    z.ZodTypeDef,
    C1ApiFunctionsV1FunctionsServiceCreateInitialCommitRequest
  > = z.object({
    functionId: z.nullable(z.string()),
    functionsServiceCreateInitialCommitRequest: shared
      .FunctionsServiceCreateInitialCommitRequest$outboundSchema.optional(),
  }).transform((v) => {
    return remap$(v, {
      functionId: "function_id",
      functionsServiceCreateInitialCommitRequest:
        "FunctionsServiceCreateInitialCommitRequest",
    });
  });

export function c1ApiFunctionsV1FunctionsServiceCreateInitialCommitRequestToJSON(
  c1ApiFunctionsV1FunctionsServiceCreateInitialCommitRequest:
    C1ApiFunctionsV1FunctionsServiceCreateInitialCommitRequest,
): string {
  return JSON.stringify(
    C1ApiFunctionsV1FunctionsServiceCreateInitialCommitRequest$outboundSchema
      .parse(c1ApiFunctionsV1FunctionsServiceCreateInitialCommitRequest),
  );
}

/** @internal */
export const C1ApiFunctionsV1FunctionsServiceCreateInitialCommitResponse$inboundSchema:
  z.ZodType<
    C1ApiFunctionsV1FunctionsServiceCreateInitialCommitResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    ContentType: z.string(),
    StatusCode: z.number().int(),
    RawResponse: z.instanceof(Response),
    FunctionsServiceCreateInitialCommitResponse: shared
      .FunctionsServiceCreateInitialCommitResponse$inboundSchema.optional(),
  }).transform((v) => {
    return remap$(v, {
      "ContentType": "contentType",
      "StatusCode": "statusCode",
      "RawResponse": "rawResponse",
      "FunctionsServiceCreateInitialCommitResponse":
        "functionsServiceCreateInitialCommitResponse",
    });
  });

export function c1ApiFunctionsV1FunctionsServiceCreateInitialCommitResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  C1ApiFunctionsV1FunctionsServiceCreateInitialCommitResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      C1ApiFunctionsV1FunctionsServiceCreateInitialCommitResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'C1ApiFunctionsV1FunctionsServiceCreateInitialCommitResponse' from JSON`,
  );
}
