/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import * as shared from "../shared/index.js";
/** @internal */
export const C1ApiSystemlogV1ExportServiceCreateResponse$inboundSchema = z.object({
    ContentType: z.string(),
    StatusCode: z.number().int(),
    RawResponse: z.instanceof(Response),
    ExportServiceCreateResponse: shared
        .ExportServiceCreateResponse$inboundSchema.optional(),
}).transform((v) => {
    return remap$(v, {
        "ContentType": "contentType",
        "StatusCode": "statusCode",
        "RawResponse": "rawResponse",
        "ExportServiceCreateResponse": "exportServiceCreateResponse",
    });
});
/** @internal */
export const C1ApiSystemlogV1ExportServiceCreateResponse$outboundSchema = z.object({
    contentType: z.string(),
    statusCode: z.number().int(),
    rawResponse: z.instanceof(Response).transform(() => {
        throw new Error("Response cannot be serialized");
    }),
    exportServiceCreateResponse: shared
        .ExportServiceCreateResponse$outboundSchema.optional(),
}).transform((v) => {
    return remap$(v, {
        contentType: "ContentType",
        statusCode: "StatusCode",
        rawResponse: "RawResponse",
        exportServiceCreateResponse: "ExportServiceCreateResponse",
    });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export var C1ApiSystemlogV1ExportServiceCreateResponse$;
(function (C1ApiSystemlogV1ExportServiceCreateResponse$) {
    /** @deprecated use `C1ApiSystemlogV1ExportServiceCreateResponse$inboundSchema` instead. */
    C1ApiSystemlogV1ExportServiceCreateResponse$.inboundSchema = C1ApiSystemlogV1ExportServiceCreateResponse$inboundSchema;
    /** @deprecated use `C1ApiSystemlogV1ExportServiceCreateResponse$outboundSchema` instead. */
    C1ApiSystemlogV1ExportServiceCreateResponse$.outboundSchema = C1ApiSystemlogV1ExportServiceCreateResponse$outboundSchema;
})(C1ApiSystemlogV1ExportServiceCreateResponse$ || (C1ApiSystemlogV1ExportServiceCreateResponse$ = {}));
export function c1ApiSystemlogV1ExportServiceCreateResponseToJSON(c1ApiSystemlogV1ExportServiceCreateResponse) {
    return JSON.stringify(C1ApiSystemlogV1ExportServiceCreateResponse$outboundSchema.parse(c1ApiSystemlogV1ExportServiceCreateResponse));
}
export function c1ApiSystemlogV1ExportServiceCreateResponseFromJSON(jsonString) {
    return safeParse(jsonString, (x) => C1ApiSystemlogV1ExportServiceCreateResponse$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'C1ApiSystemlogV1ExportServiceCreateResponse' from JSON`);
}
