/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type C1ApiAccessreviewV1AccessReviewServiceListRequest = {
  pageSize?: number | undefined;
  pageToken?: string | undefined;
};

export type C1ApiAccessreviewV1AccessReviewServiceListResponse = {
  /**
   * HTTP response content type for this operation
   */
  contentType: string;
  /**
   * HTTP response status code for this operation
   */
  statusCode: number;
  /**
   * Raw HTTP response; suitable for custom response parsing
   */
  rawResponse: Response;
  /**
   * Successful response
   */
  accessReviewServiceListResponse?:
    | shared.AccessReviewServiceListResponse
    | undefined;
};

/** @internal */
export type C1ApiAccessreviewV1AccessReviewServiceListRequest$Outbound = {
  page_size?: number | undefined;
  page_token?: string | undefined;
};

/** @internal */
export const C1ApiAccessreviewV1AccessReviewServiceListRequest$outboundSchema:
  z.ZodType<
    C1ApiAccessreviewV1AccessReviewServiceListRequest$Outbound,
    z.ZodTypeDef,
    C1ApiAccessreviewV1AccessReviewServiceListRequest
  > = z.object({
    pageSize: z.number().int().optional(),
    pageToken: z.string().optional(),
  }).transform((v) => {
    return remap$(v, {
      pageSize: "page_size",
      pageToken: "page_token",
    });
  });

export function c1ApiAccessreviewV1AccessReviewServiceListRequestToJSON(
  c1ApiAccessreviewV1AccessReviewServiceListRequest:
    C1ApiAccessreviewV1AccessReviewServiceListRequest,
): string {
  return JSON.stringify(
    C1ApiAccessreviewV1AccessReviewServiceListRequest$outboundSchema.parse(
      c1ApiAccessreviewV1AccessReviewServiceListRequest,
    ),
  );
}

/** @internal */
export const C1ApiAccessreviewV1AccessReviewServiceListResponse$inboundSchema:
  z.ZodType<
    C1ApiAccessreviewV1AccessReviewServiceListResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    ContentType: z.string(),
    StatusCode: z.number().int(),
    RawResponse: z.instanceof(Response),
    AccessReviewServiceListResponse: shared
      .AccessReviewServiceListResponse$inboundSchema.optional(),
  }).transform((v) => {
    return remap$(v, {
      "ContentType": "contentType",
      "StatusCode": "statusCode",
      "RawResponse": "rawResponse",
      "AccessReviewServiceListResponse": "accessReviewServiceListResponse",
    });
  });

export function c1ApiAccessreviewV1AccessReviewServiceListResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  C1ApiAccessreviewV1AccessReviewServiceListResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      C1ApiAccessreviewV1AccessReviewServiceListResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'C1ApiAccessreviewV1AccessReviewServiceListResponse' from JSON`,
  );
}
