/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import * as shared from "../shared/index.js";
/** @internal */
export const C1ApiStepupV1StepUpProviderServiceSearchResponse$inboundSchema = z.object({
    ContentType: z.string(),
    StatusCode: z.number().int(),
    RawResponse: z.instanceof(Response),
    SearchStepUpProvidersResponse: shared
        .SearchStepUpProvidersResponse$inboundSchema.optional(),
}).transform((v) => {
    return remap$(v, {
        "ContentType": "contentType",
        "StatusCode": "statusCode",
        "RawResponse": "rawResponse",
        "SearchStepUpProvidersResponse": "searchStepUpProvidersResponse",
    });
});
/** @internal */
export const C1ApiStepupV1StepUpProviderServiceSearchResponse$outboundSchema = z.object({
    contentType: z.string(),
    statusCode: z.number().int(),
    rawResponse: z.instanceof(Response).transform(() => {
        throw new Error("Response cannot be serialized");
    }),
    searchStepUpProvidersResponse: shared
        .SearchStepUpProvidersResponse$outboundSchema.optional(),
}).transform((v) => {
    return remap$(v, {
        contentType: "ContentType",
        statusCode: "StatusCode",
        rawResponse: "RawResponse",
        searchStepUpProvidersResponse: "SearchStepUpProvidersResponse",
    });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export var C1ApiStepupV1StepUpProviderServiceSearchResponse$;
(function (C1ApiStepupV1StepUpProviderServiceSearchResponse$) {
    /** @deprecated use `C1ApiStepupV1StepUpProviderServiceSearchResponse$inboundSchema` instead. */
    C1ApiStepupV1StepUpProviderServiceSearchResponse$.inboundSchema = C1ApiStepupV1StepUpProviderServiceSearchResponse$inboundSchema;
    /** @deprecated use `C1ApiStepupV1StepUpProviderServiceSearchResponse$outboundSchema` instead. */
    C1ApiStepupV1StepUpProviderServiceSearchResponse$.outboundSchema = C1ApiStepupV1StepUpProviderServiceSearchResponse$outboundSchema;
})(C1ApiStepupV1StepUpProviderServiceSearchResponse$ || (C1ApiStepupV1StepUpProviderServiceSearchResponse$ = {}));
export function c1ApiStepupV1StepUpProviderServiceSearchResponseToJSON(c1ApiStepupV1StepUpProviderServiceSearchResponse) {
    return JSON.stringify(C1ApiStepupV1StepUpProviderServiceSearchResponse$outboundSchema.parse(c1ApiStepupV1StepUpProviderServiceSearchResponse));
}
export function c1ApiStepupV1StepUpProviderServiceSearchResponseFromJSON(jsonString) {
    return safeParse(jsonString, (x) => C1ApiStepupV1StepUpProviderServiceSearchResponse$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'C1ApiStepupV1StepUpProviderServiceSearchResponse' from JSON`);
}
