/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type C1ApiAuthConfigV1TenantAuthConfigServiceGetRequest = {
  id: string;
};

export type C1ApiAuthConfigV1TenantAuthConfigServiceGetResponse = {
  /**
   * HTTP response content type for this operation
   */
  contentType: string;
  /**
   * HTTP response status code for this operation
   */
  statusCode: number;
  /**
   * Raw HTTP response; suitable for custom response parsing
   */
  rawResponse: Response;
  /**
   * Successful response
   */
  tenantAuthConfigServiceGetResponse?:
    | shared.TenantAuthConfigServiceGetResponse
    | undefined;
};

/** @internal */
export type C1ApiAuthConfigV1TenantAuthConfigServiceGetRequest$Outbound = {
  id: string;
};

/** @internal */
export const C1ApiAuthConfigV1TenantAuthConfigServiceGetRequest$outboundSchema:
  z.ZodType<
    C1ApiAuthConfigV1TenantAuthConfigServiceGetRequest$Outbound,
    z.ZodTypeDef,
    C1ApiAuthConfigV1TenantAuthConfigServiceGetRequest
  > = z.object({
    id: z.string(),
  });

export function c1ApiAuthConfigV1TenantAuthConfigServiceGetRequestToJSON(
  c1ApiAuthConfigV1TenantAuthConfigServiceGetRequest:
    C1ApiAuthConfigV1TenantAuthConfigServiceGetRequest,
): string {
  return JSON.stringify(
    C1ApiAuthConfigV1TenantAuthConfigServiceGetRequest$outboundSchema.parse(
      c1ApiAuthConfigV1TenantAuthConfigServiceGetRequest,
    ),
  );
}

/** @internal */
export const C1ApiAuthConfigV1TenantAuthConfigServiceGetResponse$inboundSchema:
  z.ZodType<
    C1ApiAuthConfigV1TenantAuthConfigServiceGetResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    ContentType: z.string(),
    StatusCode: z.number().int(),
    RawResponse: z.instanceof(Response),
    TenantAuthConfigServiceGetResponse: shared
      .TenantAuthConfigServiceGetResponse$inboundSchema.optional(),
  }).transform((v) => {
    return remap$(v, {
      "ContentType": "contentType",
      "StatusCode": "statusCode",
      "RawResponse": "rawResponse",
      "TenantAuthConfigServiceGetResponse":
        "tenantAuthConfigServiceGetResponse",
    });
  });

export function c1ApiAuthConfigV1TenantAuthConfigServiceGetResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  C1ApiAuthConfigV1TenantAuthConfigServiceGetResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      C1ApiAuthConfigV1TenantAuthConfigServiceGetResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'C1ApiAuthConfigV1TenantAuthConfigServiceGetResponse' from JSON`,
  );
}
