/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type C1ApiDirectoryV1DirectoryServiceCreateResponse = {
  /**
   * HTTP response content type for this operation
   */
  contentType: string;
  /**
   * HTTP response status code for this operation
   */
  statusCode: number;
  /**
   * Raw HTTP response; suitable for custom response parsing
   */
  rawResponse: Response;
  /**
   * The DirectoryServiceCreateResponse message.
   */
  directoryServiceCreateResponse?:
    | shared.DirectoryServiceCreateResponse
    | undefined;
};

/** @internal */
export const C1ApiDirectoryV1DirectoryServiceCreateResponse$inboundSchema:
  z.ZodType<
    C1ApiDirectoryV1DirectoryServiceCreateResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    ContentType: z.string(),
    StatusCode: z.number().int(),
    RawResponse: z.instanceof(Response),
    DirectoryServiceCreateResponse: shared
      .DirectoryServiceCreateResponse$inboundSchema.optional(),
  }).transform((v) => {
    return remap$(v, {
      "ContentType": "contentType",
      "StatusCode": "statusCode",
      "RawResponse": "rawResponse",
      "DirectoryServiceCreateResponse": "directoryServiceCreateResponse",
    });
  });

/** @internal */
export type C1ApiDirectoryV1DirectoryServiceCreateResponse$Outbound = {
  ContentType: string;
  StatusCode: number;
  RawResponse: never;
  DirectoryServiceCreateResponse?:
    | shared.DirectoryServiceCreateResponse$Outbound
    | undefined;
};

/** @internal */
export const C1ApiDirectoryV1DirectoryServiceCreateResponse$outboundSchema:
  z.ZodType<
    C1ApiDirectoryV1DirectoryServiceCreateResponse$Outbound,
    z.ZodTypeDef,
    C1ApiDirectoryV1DirectoryServiceCreateResponse
  > = z.object({
    contentType: z.string(),
    statusCode: z.number().int(),
    rawResponse: z.instanceof(Response).transform(() => {
      throw new Error("Response cannot be serialized");
    }),
    directoryServiceCreateResponse: shared
      .DirectoryServiceCreateResponse$outboundSchema.optional(),
  }).transform((v) => {
    return remap$(v, {
      contentType: "ContentType",
      statusCode: "StatusCode",
      rawResponse: "RawResponse",
      directoryServiceCreateResponse: "DirectoryServiceCreateResponse",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace C1ApiDirectoryV1DirectoryServiceCreateResponse$ {
  /** @deprecated use `C1ApiDirectoryV1DirectoryServiceCreateResponse$inboundSchema` instead. */
  export const inboundSchema =
    C1ApiDirectoryV1DirectoryServiceCreateResponse$inboundSchema;
  /** @deprecated use `C1ApiDirectoryV1DirectoryServiceCreateResponse$outboundSchema` instead. */
  export const outboundSchema =
    C1ApiDirectoryV1DirectoryServiceCreateResponse$outboundSchema;
  /** @deprecated use `C1ApiDirectoryV1DirectoryServiceCreateResponse$Outbound` instead. */
  export type Outbound =
    C1ApiDirectoryV1DirectoryServiceCreateResponse$Outbound;
}

export function c1ApiDirectoryV1DirectoryServiceCreateResponseToJSON(
  c1ApiDirectoryV1DirectoryServiceCreateResponse:
    C1ApiDirectoryV1DirectoryServiceCreateResponse,
): string {
  return JSON.stringify(
    C1ApiDirectoryV1DirectoryServiceCreateResponse$outboundSchema.parse(
      c1ApiDirectoryV1DirectoryServiceCreateResponse,
    ),
  );
}

export function c1ApiDirectoryV1DirectoryServiceCreateResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  C1ApiDirectoryV1DirectoryServiceCreateResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      C1ApiDirectoryV1DirectoryServiceCreateResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'C1ApiDirectoryV1DirectoryServiceCreateResponse' from JSON`,
  );
}
