/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { appEntitlementsProxyCreate } from "../funcs/appEntitlementsProxyCreate.js";
import { appEntitlementsProxyDelete } from "../funcs/appEntitlementsProxyDelete.js";
import { appEntitlementsProxyGet } from "../funcs/appEntitlementsProxyGet.js";
import { ClientSDK } from "../lib/sdks.js";
import { unwrapAsync } from "./types/fp.js";
export class AppEntitlementsProxy extends ClientSDK {
    /**
     * Delete
     *
     * @remarks
     * Invokes the c1.api.app.v1.AppEntitlementsProxy.Delete method.
     */
    async delete(request, options) {
        return unwrapAsync(appEntitlementsProxyDelete(this, request, options));
    }
    /**
     * Get
     *
     * @remarks
     * Invokes the c1.api.app.v1.AppEntitlementsProxy.Get method.
     */
    async get(request, options) {
        return unwrapAsync(appEntitlementsProxyGet(this, request, options));
    }
    /**
     * Create
     *
     * @remarks
     * Invokes the c1.api.app.v1.AppEntitlementsProxy.Create method.
     */
    async create(request, options) {
        return unwrapAsync(appEntitlementsProxyCreate(this, request, options));
    }
}
