/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { requestCatalogSearchSearchEntitlements } from "../funcs/requestCatalogSearchSearchEntitlements.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "./models/operations/index.js";
import * as shared from "./models/shared/index.js";
import { unwrapAsync } from "./types/fp.js";

export class RequestCatalogSearch extends ClientSDK {
  /**
   * Search Entitlements
   *
   * @remarks
   * Search request catalogs based on filters specified in the request body.
   */
  async searchEntitlements(
    request?:
      | shared.RequestCatalogSearchServiceSearchEntitlementsRequest
      | undefined,
    options?: RequestOptions,
  ): Promise<
    operations.C1ApiRequestcatalogV1RequestCatalogSearchServiceSearchEntitlementsResponse
  > {
    return unwrapAsync(requestCatalogSearchSearchEntitlements(
      this,
      request,
      options,
    ));
  }
}
