import { ClientSDK } from "../lib/sdks.js";
import { AccessConflict } from "./accessconflict.js";
import { AccountProvisionPolicyTest } from "./accountprovisionpolicytest.js";
import { AppAccessRequestsDefaults } from "./appaccessrequestsdefaults.js";
import { AppEntitlementMonitorBinding } from "./appentitlementmonitorbinding.js";
import { AppEntitlementOwners } from "./appentitlementowners.js";
import { AppEntitlements } from "./appentitlements.js";
import { AppEntitlementSearch } from "./appentitlementsearch.js";
import { AppEntitlementsProxy } from "./appentitlementsproxy.js";
import { AppEntitlementUserBinding } from "./appentitlementuserbinding.js";
import { AppOwners } from "./appowners.js";
import { AppReport } from "./appreport.js";
import { AppReportAction } from "./appreportaction.js";
import { AppResource } from "./appresource.js";
import { AppResourceOwners } from "./appresourceowners.js";
import { AppResourceSearch } from "./appresourcesearch.js";
import { AppResourceType } from "./appresourcetype.js";
import { Apps } from "./apps.js";
import { AppSearch } from "./appsearch.js";
import { AppUsageControls } from "./appusagecontrols.js";
import { AppUser } from "./appuser.js";
import { Attributes } from "./attributes.js";
import { AttributeSearch } from "./attributesearch.js";
import { Auth } from "./auth.js";
import { Automation } from "./automation.js";
import { AutomationExecution } from "./automationexecution.js";
import { AutomationExecutionActions } from "./automationexecutionactions.js";
import { AutomationExecutionSearch } from "./automationexecutionsearch.js";
import { AutomationSearch } from "./automationsearch.js";
import { AWSExternalIDSettings } from "./awsexternalidsettings.js";
import { Connector } from "./connector.js";
import { Directory } from "./directory.js";
import { Export } from "./export.js";
import { ExportsSearch } from "./exportssearch.js";
import { Functions } from "./functions.js";
import { FunctionsSearch } from "./functionssearch.js";
import { OrgDomain } from "./orgdomain.js";
import { PersonalClient } from "./personalclient.js";
import { PersonalClientSearch } from "./personalclientsearch.js";
import { Policies } from "./policies.js";
import { PolicySearch } from "./policysearch.js";
import { PolicyValidate } from "./policyvalidate.js";
import { RequestCatalogManagement } from "./requestcatalogmanagement.js";
import { RequestCatalogSearch } from "./requestcatalogsearch.js";
import { Roles } from "./roles.js";
import { SessionSettings } from "./sessionsettings.js";
import { StepUpProvider } from "./stepupprovider.js";
import { StepUpTransaction } from "./stepuptransaction.js";
import { SystemLog } from "./systemlog.js";
import { Task } from "./task.js";
import { TaskActions } from "./taskactions.js";
import { TaskAudit } from "./taskaudit.js";
import { TaskSearch } from "./tasksearch.js";
import { User } from "./user.js";
import { UserSearch } from "./usersearch.js";
import { Webhooks } from "./webhooks.js";
import { WebhooksSearch } from "./webhookssearch.js";
export declare class ConductoroneSDKTypescript extends ClientSDK {
    private _accessConflict?;
    get accessConflict(): AccessConflict;
    private _appEntitlementMonitorBinding?;
    get appEntitlementMonitorBinding(): AppEntitlementMonitorBinding;
    private _apps?;
    get apps(): Apps;
    private _appAccessRequestsDefaults?;
    get appAccessRequestsDefaults(): AppAccessRequestsDefaults;
    private _appUser?;
    get appUser(): AppUser;
    private _connector?;
    get connector(): Connector;
    private _appEntitlements?;
    get appEntitlements(): AppEntitlements;
    private _appEntitlementSearch?;
    get appEntitlementSearch(): AppEntitlementSearch;
    private _appEntitlementUserBinding?;
    get appEntitlementUserBinding(): AppEntitlementUserBinding;
    private _appEntitlementOwners?;
    get appEntitlementOwners(): AppEntitlementOwners;
    private _appOwners?;
    get appOwners(): AppOwners;
    private _appReport?;
    get appReport(): AppReport;
    private _appReportAction?;
    get appReportAction(): AppReportAction;
    private _appResourceType?;
    get appResourceType(): AppResourceType;
    private _appResource?;
    get appResource(): AppResource;
    private _appResourceOwners?;
    get appResourceOwners(): AppResourceOwners;
    private _appUsageControls?;
    get appUsageControls(): AppUsageControls;
    private _appEntitlementsProxy?;
    get appEntitlementsProxy(): AppEntitlementsProxy;
    private _attributes?;
    get attributes(): Attributes;
    private _auth?;
    get auth(): Auth;
    private _automationExecution?;
    get automationExecution(): AutomationExecution;
    private _automationExecutionActions?;
    get automationExecutionActions(): AutomationExecutionActions;
    private _automationExecutionSearch?;
    get automationExecutionSearch(): AutomationExecutionSearch;
    private _automationSearch?;
    get automationSearch(): AutomationSearch;
    private _automation?;
    get automation(): Automation;
    private _requestCatalogManagement?;
    get requestCatalogManagement(): RequestCatalogManagement;
    private _directory?;
    get directory(): Directory;
    private _functions?;
    get functions(): Functions;
    private _personalClient?;
    get personalClient(): PersonalClient;
    private _roles?;
    get roles(): Roles;
    private _policies?;
    get policies(): Policies;
    private _accountProvisionPolicyTest?;
    get accountProvisionPolicyTest(): AccountProvisionPolicyTest;
    private _policyValidate?;
    get policyValidate(): PolicyValidate;
    private _appResourceSearch?;
    get appResourceSearch(): AppResourceSearch;
    private _appSearch?;
    get appSearch(): AppSearch;
    private _attributeSearch?;
    get attributeSearch(): AttributeSearch;
    private _functionsSearch?;
    get functionsSearch(): FunctionsSearch;
    private _personalClientSearch?;
    get personalClientSearch(): PersonalClientSearch;
    private _policySearch?;
    get policySearch(): PolicySearch;
    private _requestCatalogSearch?;
    get requestCatalogSearch(): RequestCatalogSearch;
    private _stepUpProvider?;
    get stepUpProvider(): StepUpProvider;
    private _stepUpTransaction?;
    get stepUpTransaction(): StepUpTransaction;
    private _exportsSearch?;
    get exportsSearch(): ExportsSearch;
    private _taskSearch?;
    get taskSearch(): TaskSearch;
    private _userSearch?;
    get userSearch(): UserSearch;
    private _webhooksSearch?;
    get webhooksSearch(): WebhooksSearch;
    private _awsExternalIDSettings?;
    get awsExternalIDSettings(): AWSExternalIDSettings;
    private _orgDomain?;
    get orgDomain(): OrgDomain;
    private _sessionSettings?;
    get sessionSettings(): SessionSettings;
    private _systemLog?;
    get systemLog(): SystemLog;
    private _export?;
    get export(): Export;
    private _taskAudit?;
    get taskAudit(): TaskAudit;
    private _task?;
    get task(): Task;
    private _taskActions?;
    get taskActions(): TaskActions;
    private _user?;
    get user(): User;
    private _webhooks?;
    get webhooks(): Webhooks;
}
