/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Transform } from "class-transformer";

/**
 * AttributeValue is the value of an attribute of a defined type.
 */
export class AttributeValue extends SpeakeasyBase {
    /**
     * The ID of the AttributeType that this AttributeValue belongs to.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "attributeTypeId" })
    attributeTypeId?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "createdAt" })
    @Transform(({ value }) => new Date(value), { toClassOnly: true })
    createdAt?: Date;

    @SpeakeasyMetadata()
    @Expose({ name: "deletedAt" })
    @Transform(({ value }) => new Date(value), { toClassOnly: true })
    deletedAt?: Date;

    /**
     * The ID of the AttributeValue.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "updatedAt" })
    @Transform(({ value }) => new Date(value), { toClassOnly: true })
    updatedAt?: Date;

    /**
     * The value of the AttributeValue. This is the string that will be displayed to the user.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "value" })
    value?: string;
}
