/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { ConnectorCredential } from "./connectorcredential";
import { Expose, Type } from "class-transformer";

/**
 * ConnectorServiceRotateCredentialResponse is the response returned by the rotate method.
 */
export class ConnectorServiceRotateCredentialResponse extends SpeakeasyBase {
    /**
     * ConnectorCredential is used by a connector to authenticate with conductor one.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "credential" })
    @Type(() => ConnectorCredential)
    connectorCredential?: ConnectorCredential;

    /**
     * The new clientSecret returned after rotating the connector credential.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "clientSecret" })
    clientSecret?: string;
}
