/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { ConnectorView, ConnectorView$ } from "./connectorview";
import * as z from "zod";

/**
 * Contains an arbitrary serialized message along with a @type that describes the type of the serialized message.
 */
export type ConnectorServiceUpdateResponseExpanded = {
    /**
     * The type of the serialized message.
     */
    atType?: string | undefined;
    additionalProperties: Record<string, any>;
};

/**
 * ConnectorServiceUpdateResponse is the response returned by the update method.
 */
export type ConnectorServiceUpdateResponse = {
    /**
     * The ConnectorView object provides a connector response object, as well as JSONPATHs to related objects provided by expanders.
     */
    connectorView?: ConnectorView | undefined;
    /**
     * The array of expanded items indicated by the request.
     */
    expanded?: Array<ConnectorServiceUpdateResponseExpanded> | null | undefined;
};

/** @internal */
export namespace ConnectorServiceUpdateResponseExpanded$ {
    export type Inbound = {
        [additionalProperties: string]: unknown;

        "@type"?: string | undefined;
    };

    export const inboundSchema: z.ZodType<
        ConnectorServiceUpdateResponseExpanded,
        z.ZodTypeDef,
        Inbound
    > = z
        .object({
            "@type": z.string().optional(),
        })
        .catchall(z.any())
        .transform((v) => {
            const { "@type": atType, ...additionalProperties } = v;

            return {
                ...(v["@type"] === undefined ? null : { atType: v["@type"] }),
                additionalProperties,
            };
        });

    export type Outbound = {
        "@type"?: string | undefined;
        [additionalProperties: string]: unknown;
    };

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        ConnectorServiceUpdateResponseExpanded
    > = z
        .object({
            atType: z.string().optional(),
            additionalProperties: z.record(z.any()),
        })
        .transform((v) => {
            return {
                ...v.additionalProperties,
                ...(v.atType === undefined ? null : { "@type": v.atType }),
            };
        });
}

/** @internal */
export namespace ConnectorServiceUpdateResponse$ {
    export type Inbound = {
        ConnectorView?: ConnectorView$.Inbound | undefined;
        expanded?: Array<ConnectorServiceUpdateResponseExpanded$.Inbound> | null | undefined;
    };

    export const inboundSchema: z.ZodType<ConnectorServiceUpdateResponse, z.ZodTypeDef, Inbound> = z
        .object({
            ConnectorView: ConnectorView$.inboundSchema.optional(),
            expanded: z
                .nullable(
                    z.array(z.lazy(() => ConnectorServiceUpdateResponseExpanded$.inboundSchema))
                )
                .optional(),
        })
        .transform((v) => {
            return {
                ...(v.ConnectorView === undefined ? null : { connectorView: v.ConnectorView }),
                ...(v.expanded === undefined ? null : { expanded: v.expanded }),
            };
        });

    export type Outbound = {
        ConnectorView?: ConnectorView$.Outbound | undefined;
        expanded?: Array<ConnectorServiceUpdateResponseExpanded$.Outbound> | null | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, ConnectorServiceUpdateResponse> =
        z
            .object({
                connectorView: ConnectorView$.outboundSchema.optional(),
                expanded: z
                    .nullable(
                        z.array(
                            z.lazy(() => ConnectorServiceUpdateResponseExpanded$.outboundSchema)
                        )
                    )
                    .optional(),
            })
            .transform((v) => {
                return {
                    ...(v.connectorView === undefined ? null : { ConnectorView: v.connectorView }),
                    ...(v.expanded === undefined ? null : { expanded: v.expanded }),
                };
            });
}
