/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase } from "../../../internal/utils";

/**
 * DirectoryServiceDeleteRequest is the request message for deleting a directory. It uses URL values for input.
 */
export class DirectoryServiceDeleteRequest extends SpeakeasyBase {}
