workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    my-source:
        inputs:
            - location: openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/conductor-one/conductorone/my-source
targets:
    conductorone-ts:
        target: typescript
        source: my-source
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/conductor-one/conductorone/my-source-typescript-code-samples
            labelOverride:
                fixedValue: Typescript (SDK)
            blocking: false
